app/component/ItineraryTab.js, app/component/StreetModeSelector.js, app/component/StreetModeSelector.scss, app/component/StreetModeSelectorButton.js, app/component/StreetModeSelectorButton.scss, app/component/SummaryNavigation.js, app/component/SummaryPage.js, app/configurations/config.default.js, app/routes.js, app/util/geo-utils.js
- Cycling itinerary search
- Bug fixes to walk itinerary search
=> DT-3500: Cycling itinerary search

app/component/StreetModeSelector.scss
-  fix streetmode selector height on mobile devices 
=> DT-3500: fix streetmode selector height on mobile

app/store/FavouriteStore.js
=> DT-3693: Favourite route list not working when there is unexisting route in favourites.

sass/themes/lappeenranta/_theme.scss
- Use primary color for links and buttons in Lappeenranta theme
=> style: use primary color for links and buttons in lappeenranta

app/component/SummaryPage.js
=> DT-3696: Summary page crashes when origin and destination is the same

app/component/FavouritesContainer.js, app/component/IndexPage.js, digitransit-component/packages/digitransit-component-favourite-bar/index.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/README.md, digitransit-component/packages/digitransit-component-favourite-editing-modal/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-editing-modal/helpers/translations.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/index.js, digitransit-component/packages/digitransit-component-favourite-modal/index.js, digitransit-component/packages/digitransit-component/index.mjs, digitransit-component/packages/digitransit-component/package.json, yarn.lock
- Add favourite deleting modal.
- Translation fixes for favourite-modal and favourite-editing-modal.
- Move favourite specific functionalites from IndexPage to FavouritesContainer.
=> DT-3667: Favourite editing: Remove favourite

app/client.js, app/component/DisruptionInfo.js, app/component/DisruptionInfoButtonContainer.js, app/component/FavouritesContainer.js, app/component/FuzzyTripLink.js, app/component/IndexPage.js, app/component/MessageBar.js, app/component/OriginDestinationBar.js, app/component/SummaryPlanContainer.js, app/component/TripLink.js, app/component/WithSearchContext.js, app/component/map/VehicleMarkerContainer.js, app/component/map/non-tile-layer/CityBikeMarkerContainer.js, app/component/map/popups/CityBikePopupContainer.js, app/component/map/popups/ParkAndRideFacilityPopupContainer.js, app/component/map/popups/ParkAndRideHubPopupContainer.js, app/component/map/popups/StopMarkerPopupContainer.js, app/component/map/popups/TerminalMarkerPopupContainer.js, app/component/map/tile-layer/TileLayerContainer.js, app/server.js, app/util/DTSearchContextInitializer.js, app/util/getRelayEnvironment.js, test/unit/DisruptionInfo.test.js, test/unit/component/FuzzyTripLink.test.js, test/unit/component/TripLink.test.js, test/unit/component/map/VehicleMarkerContainer.test.js, test/unit/component/map/tile-layer/TileLayerContainer.test.js, test/unit/component/map/tile-layer/non-tile-layer/StopMarker.test.js, test/unit/helpers/mock-context.js
- Update to use ReactRelayContext from legacy context
=> Update to use ReactRelayContext from legacy context

app/configurations/config.tampere.js
- Adds a new feedId to Tampere config
=> chore: include tampereDRT in tampere config's feedIds

app/component/BusLeg.js, app/component/FerryLeg.js, app/component/ItineraryCircleLine.js, app/component/ItineraryLegs.js, app/component/ItineraryTab.js, app/component/RailLeg.js, app/component/SubwayLeg.js, app/component/TramLeg.js, app/component/TransitLeg.js, app/component/itinerary.scss, app/translations.js, build/schema.json
- Indicate whether a user should change vehicles or stay in the same vehicle
=> DT-3662: Indicate whether a user should change vehicles or stay in the same vehicle

digitransit-component/packages/digitransit-component-datetimepicker/helpers/translations.js
- Added some swedish translations for the datetime picker. However, these and many other translations should be rechecked by a proper Swedish translator.
=> fix: add some missing sv translations for timepicker

app/component/SummaryPage.js
- Hide purely walk itineraries from main results
=> DT-3683: Hide purely walk itineraries from main results

app/configurations/config.default.js
- Fix max zoom level. It was wrong previously because of -1 offset.
=> Fix max zoom level conf

app/component/CustomizeSearchNew.js
- fix:  add label to settings window close button
=> DT-3634: add label to settings window close button

digitransit-component/packages/digitransit-component-datetimepicker/helpers/dateTimeInputIsSupported.js, digitransit-component/packages/digitransit-component-datetimepicker/package.json
- Fixes SSR for mobile datetime picker
=> fix: add a check for SSR in datetime picker

app/component/SummaryPage.js, app/configurations/config.default.js, server/server.js
- Adds a config parameter for disabling weather info and temporarily disables it
=> chore: temporarily disable weather info

app/component/map/Map.js, app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js, app/component/map/tile-layer/TileLayerContainer.js, app/component/map/tile-layer/VectorTileLayerContainer.js, app/component/stops-near-you.scss, app/routes.js
- Map for stops near you page
- test url for example: `/lahellasi/BUS/Urho%20Kekkosen%20katu%201%2C%20Helsinki%3A%3A60.168992%2C24.932366`
=> DT-3670: Basic map layout for stops near you

app/component/CityBikeNetworkSelector.js, app/component/customize-search.scss
=> DT-3684: Use same font size for selecting citybike networks as other settings

app/component/RouteMapContainer.js
- Check correct vehicle by comparing start time and direction
=> DT-3699: Selecting a departure to follow on line page sometimes focuses on wrong departure

app/component/CustomizeSearchNew.js, app/component/RightOffcanvasToggle.js
- fix: set focus correctly when opening and closing settings window
=> DT-3632: set focus correctly when opening and closing settings window

app/component/SummaryPage.js, app/routes.js, app/util/geo-utils.js, app/util/planParamUtil.js
- feat: only query walk and bike plans if distance is short enough
=> DT-3671:  only query walk and bike plans if distance is short enough

app/component/CustomizeSearchNew.js
- fix: settings window closing on mobile
=> DT-3632: fix settings window closing on mobile

app/component/RoutePage.js
- Buses are shown on first page load
=> DT-3698: Buses not showing on map on first page load

app/component/RouteMapContainer.js
- Fix map focusing on wrong vehicle on line page.
- There was an additional bug here that did not come up in next, need to test if this is reproducible in next
=> DT-3699 master

app/component/map/tile-layer/TileContainer.js, app/util/mapIconUtils.js
- Add correct scaling for new map icons on mobile
=> DT-3720: Stop markers don't scale well on mobile

app/component/StopsNearYouPage.js, app/component/route.scss, app/component/stops-near-you.scss
- Fix back button styles from near you page bleeding into route and stop page and make route page button follow design more closely
=> DT-3721: Back button positioning broken on desktop

app/component/SearchSettingsDropdown.js
- Make settings dropdown scroll down when opened
=> DT-3706: make settings dropdown scroll down when opened

app/component/SummaryPage.js, app/routes.js, app/util/planParamUtil.js
- fix:  remove unnecessary parameters and data from route queries
=> DT-3708: remove unnecessary parameters and data from route queries

app/component/SummaryPage.js
- Hide walk only itineraries from map when main search results are shown.
=> DT-3723: Selected itinerary doesn't match what is shown on map

app/component/CityBikeNetworkSelector.js, app/component/CustomizeSearchNew.js, app/component/Toggle.js, app/component/customize-search.scss, app/component/customizesearch/AccessibilityOptionSection.js, app/component/customizesearch/TransferOptionsSection.js, app/component/customizesearch/TransportModesSection.js, app/component/toggle.scss
- Change settings toggles to use correct labeling pattern
- Add form, fieldset, legend elements to settings form for better accessibility
=> DT-3651: Settings buttons accessibility

app/component/SummaryPage.js
- fix: summary page crashing on empty itinerary
=> DT-3730: fix summary page crashing on empty itinerary

app/component/DepartureListContainer.js, app/component/DepartureRowContainer.js, app/component/NearbyRoutesPanel.js, app/component/RouteAlertsContainer.js, app/component/RoutePage.js, app/component/RouteScheduleContainer.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/map/popups/StopMarkerPopup.mockdata.js, app/util/planParamUtil.js, build/schema.json, test/unit/component/DepartureRowContainer.test.js, test/unit/util/planParamUtil.test.js
- Bring changes from #3387 to master
=> refactor: remove usage of deprecated GraphQL fields and parameters

app/component/DisruptionBanner.js, app/component/StopsNearYouPage.js, app/component/stops-near-you.scss, app/routes.js
- POC disruption info banner
- Shows the first alert with the highest severity level if the severity level is higher than 'info'
=> DT-3390: Disruption info banner

app/component/route.scss
=> DT-3727: fix pattern selector overflow

app/component/RouteMapContainer.js, app/component/map/non-tile-layer/StopMarker.js
- fix: trip information infinite loop
=> DT-3725: fix trip information infinite loop

digitransit-component/packages/digitransit-component-favourite-bar/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-bar/package.json
=> DT-3719: fix own places plus button on small screen sizes

app/component/map/tile-layer/Stops.js
- Invisible stops removed from stops near you view
=> DT-3736: Invisible clickable stops in stops near you view

app/component/customize-search.scss
- fix: search settings title css selector
=> DT-3738: fix search settings title css selector

app/component/CityBikeStopNearYou.js, app/component/map/Line.js, app/component/map/Map.js, app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js, app/component/map/map.scss, app/component/map/tile-layer/TileLayerContainer.js, app/component/map/tile-layer/VectorTileLayerContainer.js, app/routes.js
- Route shapes for routes that go through the nearest stops are shown on the map in stops near you view
=> DT-3399: Show route lines (shapes)

app/component/AppBarHsl.js, app/component/LocalStorageEmitter.js, app/routes.js, package.json, yarn.lock
- Start using `SharedLocalStorageObserver` and `useSharedLocalStorageEmitter`.
=> Shared local storage

server/passport-openid-connect/Strategy.js, server/passport-openid-connect/openidConnect.js
=> DT-3739: Fix single sign on

server/passport-openid-connect/openidConnect.js
=> feat: add samesite attribute to session cookie

digitransit-component/packages/digitransit-component-favourite-editing-modal/index.js
- Fix bug where editing and deleting favourites wasn't working.
=> fix: deleting and editing favourites

digitransit-component/packages/digitransit-component-datetimepicker/helpers/styles.scss, digitransit-component/packages/digitransit-component-datetimepicker/package.json
- Add scrollbar to date and time inputs in datetimepicker
=> DT-3744: Add scroll bar to day/time selector

app/component/FavouritesContainer.js, digitransit-component/packages/digitransit-component-favourite-bar/index.js, digitransit-component/packages/digitransit-component-favourite-bar/package.json
=> DT-3751: Favourite order doesn't always update after reorder

app/component/CityBikeStopNearYou.js, app/component/DepartureRow.js, app/component/StopNearYouDepartureRowContainer.js, app/component/StopNearYouHeader.js, app/component/StopsNearYouContainer.js, app/component/stops-near-you.scss
- Accessibility improvements to near you page
- Add proper headings to stop cards and mark them as list
=> DT-3758: Near you page accessibility improvements

app/component/map/MapWithTracking.js
- Fixed an issue where locate me button didn't work when pressed
=> DT-3678: Locate me button in stopsNearYouMap doesn't work

app/component/map/StopsNearYouMap.js
- Zooms out the map if no stops are near you.
=> DT-3753; Auto zoom 'Stops near you' map content when stops are not near you

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/helpers/select.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/styles.scss
=> DT-3775: Style tuning in autosuggest-panel and favourite-bar

app/component/map/ItineraryLine.js, app/component/map/non-tile-layer/LegMarker.js
=> DT-3728: fix route knot points obscuring route label

app/action/FavouriteActions.js, app/component/FavouriteRouteContainer.js, app/component/FavouritesContainer.js, app/component/map/route/TripMarkerPopup.js, app/store/FavouriteStore.js
=> DT-3777: FavouriteStore cleaning

app/component/StopPageMap.js, app/stopRoutes.js, test/unit/component/StopPageMap.test.js
=> DT-3755: walk routing to selected stop

server/server.js
=> feat: use id_token when fetching favourites

app/configurations/config.default.js
=> fix: http to https

app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js, app/store/PositionStore.js
=> DT-3722: useFitBounds broke the locate me functionality

app/configurations/config.default.js
- Updated timezoneData for moment
=> DT-3786-master Update timezone data

app/configurations/config.default.js
- Updated timezoneData for moment
=> DT-3786 Update timezone data

app/component/OriginDestinationBar.js, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
=> DT-3780: Favourites aren't showing correctly on Itinerary page

app/component/StopPageMap.js, app/component/map/IndexPageMap.js, app/component/map/MapWithTracking.js
- Fixed an issue where StopPage's locate me button didn't work at all
- Removed bunch of old unnesessary code
- Started working torwards a new way of adding props to MapWithTracking
Refactor is still in progress but this is a good checkpoint. 
=> DT-3791: refactor mapWithTracking part 1

app/component/map/IndexPageMap.js, app/component/map/MapWithTracking.js
=> WIP: Dt 3791 part 2

app/component/StopNearYou.js, app/component/StopNearYouHeader.js, app/component/StopsNearYouContainer.js, app/component/stops-near-you.scss
- Railway, bus and subway stations are now displayed as single entries in the stops near you view
=> DT-3788: Show stations near you instead of stops near you

app/component/ItinerarySummaryListContainer.js, app/translations.js
=> DT-3672: update header texts in cycling and public itinerary search

app/component/StopPageMap.js, app/component/map/IndexPageMap.js, app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js, test/unit/component/map/MapWithTracking.test.js
- Move focusPointLogic further to parent components
- FitBounds is working in stop page
- Fixes in indexPageMap
=> DT-3791 part 3: MapWithTracking refactor

app/component/map/StopsNearYouMap.js
- fix: stopsnearyou loading loop
=> DT-3847 part 2: Fix loading loop

app/component/AppBarContainer.js, app/component/AppBarHsl.js, package.json, yarn.lock
- Updated hsl.fi banner
- added login functionality
=> DT-3808: Login functionality

app/component/RouteMapContainer.js
- Prevent "white map" when trip is in future
=> DT-3790: render map if trip is in future

digitransit-component/packages/digitransit-component-favourite-bar/README.md, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/package.json, digitransit-component/packages/digitransit-component-favourite-editing-modal/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-editing-modal/src/index.js, yarn.lock
- Add favourite-bar and favourite-editing-modal loading states
=> Add favourite-bar and favourite-editing-modal loading states

app/component/FavouritesContainer.js, app/component/IndexPage.js, app/component/WithSearchContext.js, app/store/FavouriteStore.js, digitransit-component/packages/digitransit-component-autosuggest-panel/README.md, digitransit-component/packages/digitransit-component-autosuggest/README.md, digitransit-component/packages/digitransit-component-dialog-modal/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-dialog-modal/src/index.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/src/index.js
- Use loading states in favourite-bar and modals.
- Fix bug where favourites were updated unnecessarily in favourite-editing-modal.
- Fix dialog-modal styles.
- Define appElement in withSearchContext HOC.
=> DT-3854: Use favourite loading states

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js
- When pressing enter on search-field then directs to first suggestion
=> DT-3824: pressing enter on mobile

app/component/StopNearYouHeader.js, app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js
- Correct zooming on stops near you map
- Walk routing to two nearest stations works properly now
=> DT-3714: Handling no nearby stops situation

app/component/StreetModeSelectorButton.js
=> fix: crash

app/component/StreetModeSelector.scss, app/component/StreetModeSelectorButton.js, app/component/StreetModeSelectorButton.scss, app/component/StreetModeSelectorWeatherLabel.js
- Tweaked Streetmode buttons to mach current design
=> DT-3762: Streetmode button tweaks

app/configurations/config.hsl.js
=> refactor: remove static messages from hsl

digitransit-component/packages/digitransit-component-favourite-editing-modal/src/index.js
=> DT-3859: Update reordered favourites to backend after closing favourite-editing-modal

app/component/MessageBar.js
=> DT-3861: Fix gps blocked icon color

app/component/StopsNearYouPage.js, app/component/stops-near-you.scss
- Remove unwanted scrollbar from stops near you page
=> DT-3862: Remove unwanted scrollbar from stops near you page

app/component/StopNearYouDepartureRowContainer.js
- Use uuid for departure row keys to ensure uniqueness
=> DT-3868: Duplicate departure rows in stops near you view

app/util/fetchUtils.js, server/server.js
- Don't cache user information or it's favourites.
=> DT-3848: User login / logout issues

app/component/ItineraryPageMap.js
- Removed unnecessary onMapCenter from ItineraryPageMap
=> DT-3812: Fix a bug where clickin map icon on itinerarypage navigates to stop page

app/component/map/SelectFromMapPageMap.js
- LocationPopup removed
- pin relocates to defaultLocation when moving
=> DT-3869: SelectFromMap issues

app/component/map/SelectFromMapPageMap.js
- Marker color changed to black when LocationMarker was moved in SelectFromMap. This issue is now fixed
=> DT-3869: Marker color issue fix in SelectFromMap

app/server.js
- Fixes issue where pages that rendered Error404 component returned 200 status code instead of 404 which caused potential for cache to be corrupted with Error404 pages instead of the real assets in a load balancing setup where there were old and new versions of the UI running at the same time. 
- Check that the implementation matches the design, when such one …
=> fix: return 404 status from loading Error404 component

app/component/BikeRentalStationContent.js
- City bike page link now functional
=> DT-3879: City bike page link

app/component/navigation.scss
=> fix: summary page header

digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss
- Add 5 min intervals to timepicker dropdown when current time is selected
- Change cursor toinput style cursor when timepicker is editable
- Select text in timepicker input when dropdown is opened
=> DT-3853: Time picker options update

app/component/ItineraryPageMap.js, app/component/SummaryPage.js
- Zoom all route not just start point
=> DT-3840: zoom all route not start point

app/component/FavouritesContainer.js, app/component/IndexPage.js, app/component/SummaryPage.js, app/component/customizesearch/AccessibilityOptionSection.js, app/component/customizesearch/StreetModeSelectorPanel.js, app/component/map/non-tile-layer/StopMarker.js, app/util/citybikes.js
- Added analytics event for new features
=> DT-3432: add analytics

app/component/CustomizeSearchNew.js, app/component/SearchSettingsDropdown.js, app/component/customize-search.scss, app/component/customizesearch/WalkingOptionsSection.js, app/translations.js
- Add a settings toggle to avoid walking
- Toggle will set the walkReluctance option for routing
=> DT-3851: Avoid walking toggle to settings menu

app/component/map/map.scss
- Top bar no longer renders in front of the mobile search
=> DT-3899: Mobile search in Stops near you view is broken

app/component/navigation.scss, app/component/route.scss
- Stop page back arrow position fixed
- Back arrow position is consistent between different pages
=> DT-3905: Wrong Back arrow position in Stop page

app/component/stop.scss, app/component/summary-row.scss, digitransit-component/packages/digitransit-component-suggestion-item/src/helpers/styles.scss, sass/base/_elements.scss, sass/themes/default/_theme.scss
=> DT-3814: contrast fixes for texts

app/component/StopsNearYouSearch.js
- Location change doesn't close stops near you search
=> DT-3900: Location change closes stops near you search

app/translations.js
=> DT-3914: stops near you header translation

sass/themes/hameenlinna/_theme.scss
- Add missing top-bar-color definition for hameenlinna
=> fix: add missing top bar color definition for hameenlinna

app/component/FavouritesContainer.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-dialog-modal/README.md, digitransit-component/packages/digitransit-component-favourite-modal/package.json, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/desktop.scss, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/mobile.scss, yarn.lock
- Pull request without random garbage
=> DT-3860: styling search boxes part 2

digitransit-component/packages/digitransit-component-autosuggest/src/index.js
=> DT-3919: Update placeholder text to match design

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/summary.scss
- fix: remove additional settings link from bike and public search results
=> DT-3796: remove additional settings link from bike and public search results

app/component/MobileView.js, app/component/map/Map.js, app/component/map/MapContainer.js, app/component/map/MapWithTracking.js, app/component/map/map.scss
- Map locationing button and copyright and scale elements move when bottom sheet is scrolled
- Some lag is visible when buttons move. This is smoothed with css animation
=> DT-3864: Map buttons when bottom sheet is scrolled

digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss
- Add flexible size for nearby stops buttons.
=> DT-3920: Nearby stops button bar without citybike

app/component/SummaryGeolocator.js
- preventing spinner to spin forever
=> DT-3804: Entering itinerary page with geolocation as destination or origin breaks navigation

app/component/map/StopsNearYouMap.js
=> DT-3929: Add search location marker into Stops near you view

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js
- Walk and biking buttons are not displayed if the user has selected wheelchair from the settings
- Walk-only itineraries hidden from the summary
=> DT-3799: Removing walking routes from wheelchair users

app/component/BackButton.js
- Fixing where back button redirects
=> fix: goBack

app/component/IndexPage.js, app/component/front-page.scss
=> DT-3763: scrollbar to left panel

app/component/StopPageMap.js, yarn.lock
- Fixed issue described in title
=> DT-3936: Map zooms too far in Stop page

digitransit-component/packages/digitransit-component-favourite-modal/package.json, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/mobile.scss
=> DT-3907: button position on ipad

app/component/OriginDestinationBar.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js
- Fixed  issues where multiple empty viaPoint crashed the ui
=> DT-3918: ViaPoint errors

app/component/map/Map.js
- Move buttons outside of leaflet map so click events on button don't propagate to map elements.
=> DT-3943: Clicking location button on mobile activates click handlers on map

app/component/map/map.scss
- Fix bottom sheet z-index value so it is under top bar and top bar menu
=> DT-3945: Z index for bottom sheet and top bar menu

app/component/IndexPage.js, app/component/TopLevel.js, app/component/map/MarkerPopupBottom.js, app/component/map/non-tile-layer/StopMarker.js, app/component/map/popups/LocationPopup.js, app/component/map/tile-layer/TileLayerContainer.js, app/configurations/config.default.js, app/configurations/config.hsl.js, app/routes.js, app/util/path.js, server/passport-openid-connect/openidConnect.js, server/server.js
- Added indexPath conf option for configuring in which path index page can be found
=> DT-3831 Redirect plain 'next-dev.digitransit.fi' address to 'dev.hslfi.hsldev.com'

app/component/map/tile-layer/TileLayerContainer.js
=> Fix location popup issue

app/store/localStorage.js, package.json, yarn.lock
=> Update shared-local-storage to 0.3.0

app/component/MobileView.js, app/component/itinerary.scss, app/component/map/map.scss, app/component/route.scss, app/component/stop-cards.scss, app/component/stop.scss, app/component/stops-near-you.scss
- Style fixes for bottom sheet, location button and zoom buttons
- Make bottom sheet style definitions more consistent 
=> DT-3956: Bottom sheet style fixes

digitransit-component/packages/digitransit-component-favourite-modal/src/index.js
=> fix: don't save defaultaname, add gid to adding callback

app/component/AppBarHsl.js, app/store/FavouriteStore.js, app/store/localStorage.js
=> DT-3497: clear local storage when user logs out

app/component/ItineraryLegs.js, app/component/ItinerarySummaryListContainer.js, app/component/ItineraryTab.js, app/component/StreetModeSelectorWeatherLabel.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/util/legUtils.js
- rewrite earlier/later logic
- fix streetMode selection
- remove unnecessary alert data from some queries
=> DT-3934: fix earlier/later functionality

app/component/StreetModeSelector.js, app/component/SummaryPage.js
- fix: make streetmode selector render only once with all data
=> DT-3965: Make streetmode selector render only once with all data

app/component/Favourite.js, app/component/FavouriteBikeRentalStationContainer.js, app/component/FavouriteRouteContainer.js, app/component/FavouriteStopContainer.js, app/translations.js
- Show login modal if user not logged in when trying to save favourite
=> DT-3949: show login modal if user not logged in

app/component/StreetModeSelector.js
- fix itineraries spinner in ios safari
- Tested on iPhone 12 safari via ngrok
=> DT-3973: fix itineraries spinner in ios safari

app/component/IndexPage.js, app/component/WithSearchContext.js
- Fixes navigateTo calls from indexPage
- Fix pathname parsing for setting locations from autosuggest for non-hsl configurations
=> DT-3970 Favourite button selection does not work in reittiopas

app/component/SummaryPage.js
- fix ui crashing when opening invalid itinerary from a link
=> fix: ui crashing when opening invalid itinerary from a link

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js
- fix: dont show error messages before finished loading
=> DT-3968: fix dont show error messages before finished loading

app/component/SummaryPage.js
- Show full itinerary on map when clicking itinerary details
=> DT-3959: show full itinerary on map when clicking itinerary details

app/component/customizesearch/BikingOptionsSection.js, app/component/customizesearch/WalkingOptionsSection.js
- fix:  values not listed in the settings dropdowns no longer crash ui
=> DT-3982: values not listed in the settings no longer crash ui

app/component/BackButton.js, app/configurations/config.hsl.js
- Pass language parameter to ROOTLINK if locale is not 'fi' 
=> DT-3978: pass language parameter to ROOTLINK

app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/util/planParamUtil.js
- fix: change the number of itineraries on mobile to 5
=> DT-3983: change the number of itineraries on mobile to 5

package.json, yarn.lock
=> DT-3980: Update hsl-fi site header

app/component/ItinerarySummary.js, app/component/ItineraryTab.js, app/component/itinerary.scss
=> DT-3967: Text overflow in a bike+public suggestion

app/component/StopNearYou.js, app/component/StopNearYouDepartureRowContainer.js, app/component/StopsNearYouContainer.js, app/component/stops-near-you.scss
- Platform number is shown with stations
=> DT-3981: Platform numbers to Nearby stops view

app/component/Favourite.js, app/component/FavouriteBikeRentalStationContainer.js, app/component/FavouriteRouteContainer.js, app/component/FavouriteStopContainer.js, app/component/FavouritesContainer.js, app/component/IndexPage.js, app/component/OriginDestinationBar.js, app/component/StopsNearYouPage.js, app/component/StopsNearYouSearch.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
- Don't show favourites anywhere if user is not logged in or allowLogin is false
=> DT-3989: Don't show favourites anywhere if user is not logged in

app/component/map/map.scss
- Zoom button styles are not broken in firefox
=> DT-3904: Zoom button styles broken in firefox

digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
=> DT-3993: Stop and route autosuggest broken with no favourites stops/stations

app/component/stops-near-you.scss
- Adjusted overflow rules for stops near you page
=> DT-4002: Stops near you stop/route autosuggest list size should not be affected by the number of stops

app/configurations/config.default.js, app/configurations/config.hsl.js
=> DT-4006: Remove citybikes from new reittiopas

app/configurations/config.default.js, app/configurations/config.hsl.js, app/configurations/config.matka.js
=> DT-4005: Remove citybikes from old reittiopas

app/component/ItineraryPageMap.js, app/component/SummaryPage.js, app/component/map/Map.js
=> DT-3960: Fix map recenter issue in mobile

app/component/SummaryPage.js, app/configurations/config.default.js, app/util/planParamUtil.js
- Slightly change default walkSpeed to match old UI's default
- Use higher maxWalkDistance for public+bike options
- Set disableRemainingWeightHeuristic true when public+bike options have viapoints
=> DT-4003 Check that routing parameters are the same as in old UI

app/component/ItineraryPageMap.js
- Itinerarypagemap checks if the breakpoint changes.
=> DT-4011: Changing orientation with tablet crashes the itinerary view

app/component/IndexPage.js, app/configurations/config.hsl.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js, digitransit-component/packages/digitransit-component/package.json
- Fixes an issue in indexpage that desktop shows both select from own locations and all favourites in the suggestion list
- Fixes an issue where selecting select from own locations list would show unrelevant results
=> DT-4008: Select from own locations shows wonky results

app/component/SummaryPage.js
- Painting order of itineraries
=> DT-4001: The drawing order incorrect on the map after ckicking later departures

server/passport-openid-connect/Strategy.js, server/passport-openid-connect/openidConnect.js, server/server.js
=> DT-3997: Refresh access token frequently

app/configurations/config.hameenlinna.js, app/configurations/realtimeUtils.js
- Add config for hämeenlinna
- Update waltti mqtt address
=> Update waltti realtime configurations

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js
- fix:  show appropriate error when query fails on itinerary page
=> DT-3992: show appropriate error when query fails

app/configurations/realtimeUtils.js
=> chore: update waltti mqtt address

app/configurations/config.kuopio.js
- Add F zone to kuopio zone mapping
=> chore: update kuopio zone mapping

app/component/AppBarLarge.js, app/component/IndexPage.js, app/component/MainMenu.js, app/component/OriginDestinationBar.js, app/component/StopsNearYouContainer.js, app/component/StopsNearYouPage.js, app/component/TopLevel.js, app/component/map/StopsNearYouMap.js, app/config.js, app/configurations/config.default.js, app/store/FavouriteStore.js
- Fix issue where favourites are not shown in autosuggests for logged in users in IndexPage before view is rerendered
- Replace usage of showLogin with allowLogin
- Simplify logic for deciding if favourites should be shown
=> DT-4039 Favourites don't show up in autosuggests before some rerender

app/component/DisruptionBanner.js, app/component/IndexPage.js, app/component/StopsNearYouPage.js, app/configurations/config.hsl.js, digitransit-component/packages/digitransit-component-traffic-now-link/package.json, digitransit-component/packages/digitransit-component-traffic-now-link/src/index.js
- feat: language support for traffic now link
=> DT-4026: language support for traffic now link

app/component/IndexPage.js
- Update shouldUpdate check that prevented IndexPage from updating when favourite store's status changed
=> fix: update shouldUpdate check

app/component/DesktopView.js, app/component/ItinerarySummaryListContainer.js, app/component/StreetModeSelector.js, app/component/StreetModeSelectorShimmer.js, app/component/StreetModeSelectorWeatherLabel.js, app/component/SummaryNavigation.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/navigation.scss, app/component/streetmodeselector.scss, app/component/streetmodeselectorbutton.scss, app/component/streetmodeselectorshimmer.scss, app/component/summary-row.scss, app/component/summary.scss, sass/_main.scss
=> SummaryPage ux improvements

app/component/ItinerarySummaryListContainer.js, app/component/summary.scss
=> Mobile loading animation is not needed, remove it

app/component/summary-row.scss
- Highlight the active row on the summary view (desktop)
=> DT-4033: Highlight the active row on the summary view (desktop)

app/component/SummaryPage.js
- feat: add loading spinner back to itinerary summary container
=> DT-4045: add loading spinner back to itinerary summary container

app/component/BackButton.js, app/component/CardHeader.js, app/component/RoutePage.js, app/component/RoutePatternSelect.js, app/server.js
- Remove some unnecessary things that were causing warnings
- Fix route page pattern changing for SSR
=> DT-4040 UI server crashes at certain URLs

app/component/map/MapContainer.js, app/component/map/MapWithTracking.js, app/component/map/withGeojsonObjects.js
- Move drawing of geoJSON layers (including ticket zones) to a separate wrapper component
- Wrapper is rendered for all pages with maps
=> DT-4025: Show ticket zones in all maps

app/component/Duration.js, app/component/Loading.js, app/component/StreetModeSelectorButton.js, app/component/SummaryRow.js, app/component/WalkDistance.js, app/translations.js
=> DT-3759: Accessibility improvements in itinerary suggestions page

app/component/DatetimepickerContainer.js, digitransit-component/packages/digitransit-component-datetimepicker/README.md, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/index.js
- fix: leaving now datepicker button on itinerary page
=> DT-4016: fix leaving now datepicker button on itinerary page

app/component/map/MapWithTracking.js
- Zooming disables focusing on own location
=> DT-4024: Zooming or scrolling while zooming on map doesn't reset focusing on own location

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/navigation.scss, app/component/summary.scss, sass/base/_helper-classes-after-foundations.scss
=> Summary page bottom loading ux improvements

app/component/ItineraryPageMap.js, app/component/SummaryPage.js, app/component/map/Map.js
- Fixes an issue, where ui would crash if user navigates back to itinerary view from stop page, when bicycle and transit mode is selected
=> DT-4012: Frozen itinerary view after back navigation

app/component/ItineraryPageMap.js, app/component/SummaryPage.js
- cycling and walking route zooms to full route instead of starting
- not to show vehicles if only walking or biking
=> DT-4022: Cycling and walking route zooms to starting point

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js
- Filter itineraries that don't contain public transit from bike+public suggestions
- There used to be a more complicated filtering logic but all logic was removed at some point. Also seemingly the old logic was buggy and it would remove all itineraries if one had only WALK/BICYCLE legs
- Add more validation to prevent summary page from crashing
- Check that …
=> DT-4058 Bike suggestion button is shown but the itinerary is not and DT-4057 Selecting bike+public in some cases crashes UI

app/component/StopsNearYouPage.js
- Show favourites on search field when user has logged in
=> DT-4035: Stops near you entry location search improvements

app/component/SummaryPage.js
=> DT-4020: Map link on itinerary page does not work

app/component/StopsNearYouPage.js
=> DT-4035v2: fix for DT-4035

app/component/BicycleLeg.js, app/component/itinerary.scss
- Added a link to last stop page.
=> DT-4062: Last stop of bike+public itinerary provides no link to stop page

server/passport-openid-connect/openidConnect.js
=> fix: temporary fix for checking if user is authenticated

app/component/SummaryPage.js, package.json, yarn.lock
- Use suncalc-library to calculate sunrise and sunset
=> DT-4027: More advanced logic for deciding when it's dark

app/component/SummaryPage.js, app/util/planParamUtil.js
- fix: mode settings affect bike+public suggestions
=> DT-4034: mode settings affect bike+public suggestions

app/component/map/Map.js, app/component/map/StopsNearYouMap.js, app/component/map/tile-layer/VectorTileLayerContainer.js
- Removes park and ride icons from stops near you map
=> DT-4042: Remove park and ride icons from "Stops near you" page

app/component/ItinerarySummaryListContainer.js, app/translations.js
- Header of "bike to vehicle" itineraries
=> DT-4038: Take your bike with you on the train/metro -header incorrect

app/component/404.js
- Direct to either ROOTLINK or /indexPath from 404 page
=> DT-4071 404 page frontpage link should point to hsl.fi

app/component/ZoneIcon.js, test/unit/component/map/tile-layer/TileLayerContainer.test.js, test/unit/component/map/tile-layer/non-tile-layer/StopMarker.test.js
- Don't render circle zone icon when zone is unknown
=> DT-4072 Zone icon for non-hsl area is broken

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
=> DT-4064: Focus change from stop/route autosuggest to location autosuggest requires double-click

app/component/BicycleLeg.js, app/component/ItineraryPageMap.js, app/component/ItineraryTab.js
- Ride+public crash after clicking around different itineraries
=> DT-4069: Ride+public crash after clicking around different itineraries

app/util/planParamUtil.js
- Take wheelchair into account in query filters
- Actually use includeBikeSuggestions setting
=> DT-4075 Bike query filter does not work properly

app/component/SummaryRow.js, app/component/summary-row.scss
- Fixed clipping issue with route numbers on Samsung internet
- Improved route number rendering logic
=> DT-4053: No route number in itinerary summary leg

app/component/customizesearch/BikingOptionsSection.js, app/component/customizesearch/WalkingOptionsSection.js, app/util/planParamUtil.js
- feat: round walk/bikespeed to closest option
=> DT-4015: round walk/bikespeed to closest option

app/component/SummaryPage.js
- fetch second query (walk, bike and bike+public) only if origin and destination differs
=> DT-4063: bike+public shows up sometimes when origin and destination are same

app/component/AppBarHsl.js, app/component/Favourite.js, app/component/FavouriteBikeRentalStationContainer.js, app/component/FavouriteRouteContainer.js, app/component/FavouriteStopContainer.js, server/passport-openid-connect/openidConnect.js
- Adding encoded url to login-link (favourite's star-button and login-button)
- refactoring login modal on favourite
=> DT-4043: User is not returned to same near you stops page after login

app/component/WithSearchContext.js
=> DT-4073: Favourite terminal is added to old searches if selected from nearby stops search

app/configurations/config.lahti.js, app/configurations/realtimeUtils.js
- Use vehicle positions for Lahti
=> DT-4066-next Enable TripUpdate & VehiclePosition -interfaces in Lahti

app/configurations/config.lahti.js, app/configurations/realtimeUtils.js
- Use vehicle positions for Lahti
=> DT-4066 Enable TripUpdate & VehiclePosition -interfaces in Lahti

app/component/map/SelectFromMapPageMap.js
- no more centering on zooming, zoom levels
=> DT-4080: Select from map in mobile is hard to use

app/component/Geolocator.js, app/routes.js, app/util/path.js
- Added geolocator for indexpage
=> DT-4082: Front page error with /POS path if geolocation is not allowed yet

app/component/RouteNumber.js, app/component/SummaryRow.js, app/component/summary-row.scss
- Icons for walking and waiting are always shown if the amount of legs is low enough
=> DT-3975: Legs with no content in itinerary summary

app/configurations/config.hameenlinna.js, app/configurations/config.lahti.js
- remove mention about zones from lahti and hameenlinna tooltips
=> next fix: remove mention about zones from lahti and hameenlinna tooltips

app/component/SummaryPage.js
- Hotfix for the issue. Will need a complete refactoring to be done later.
=> DT-4086: Walk/bike itinerary map does not obey user navigation.

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js
- Fix problem with mobile search bars in hsl.fi
- Was cause by react-modal appElement not being set correctly
=> DT-4084: Mobile search error

app/component/ItinerarySummaryListContainer.js
- fix: changing arriveBy crashes ui
=> DT-4096: fix changing arriveBy crashes ui

.travis.yml, digitransit-search-util/packages/digitransit-search-util-distance/index.js, digitransit-search-util/packages/digitransit-search-util-distance/package.json
- Automate npm publish process and use distance.js to test it.
=> DT-4108: Automate shared npm package release process

app/component/RoutePage.js
- remove duplicate route number
=> DT-4105: Route number rendering broken

app/component/FilterTimeTableModal.js, app/component/stop.scss
- Reveal back button with new design
=> DT-4103: Back arrow missing from Stop view/Timetable/Choose routes selector in mobile

.travis.yml
- Remove deployment from travis.yml for now
=> fix: remove deploy from travis.yml, because it doesn't work

app/component/TopLevel.js
- Don't attempt to fetch user info when local storage emitter is loaded
=> DT-4077 Remove api call from localStorage emitter

app/routeRoutes.js, app/routes.js, app/util/oldParamParser.js, app/util/path.js
- Fix redirects from routeRoutes
- Redirect from /from/to/<TAB_NEARBY> to /from/to/
- Redirect from /from/to/<TAB_FAVOURITES> to /from/to/
- Redirect from /from/to to /<PREFIX_ITINERARY_SUMMARY>/from/to when from and to are defined even when indexPath is defined to be something else than '/' and from and to are defined
- Redirect from /<PREFIX_ITINERARY_SUMMARY>/from to /from/-
- Use indexPath in oldParamParser
- Test the functionality by running the UI locally …
=> DT-4083 Redirect commonly used paths to new reittiopas

.travis.yml
- Test automatic deploy with distance module
=> Travis.yml test

app/component/DateWarning.js, app/component/ItineraryTab.js, app/component/SummaryRow.js, app/component/itinerary.scss, app/component/summary-row.scss, app/util/timeUtils.js
- New style for future route suggestion dates (e.g. search is done near midnight and results are in the next day)
=> DT-4106: Add date to itinerary suggestions

app/component/RouteNumber.js
- Show nothing instead of 0 in travel legs
- Removed duplicate code
=> DT-4013: 0 minute travel legs

app/component/IntermediateLeg.js, digitransit-component/packages/digitransit-component-datetimepicker/README.md, digitransit-component/packages/digitransit-component-dialog-modal/README.md, digitransit-component/packages/digitransit-component-favourite-bar/README.md
- Stop specific arrival times to itinerary view
=> DT-4100: Show stop specific arrival times in itinerary view

app/component/ItinerarySummaryListContainer.js
- Alert icons are displayed on itinerary summaries
=> DT-4124: Alert icons not visible on itinerary suggestions page

app/util/mqttClient.js
- Don't use headsign in topic subscription if it contains /
=> DT-3917 Tampere, route short name of vehicle position dots are constantly changing 

app/component/WithSearchContext.js, app/store/FutureRouteStore.js, digitransit-component/packages/digitransit-component-autosuggest/src/index.js, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js, digitransit-search-util/packages/digitransit-search-util-helpers/index.js, digitransit-search-util/packages/digitransit-search-util-query-utils/README.md, digitransit-search-util/packages/digitransit-search-util-query-utils/index.js, digitransit-store/packages/digitransit-store-future-route/README.md, digitransit-store/packages/digitransit-store-future-route/src/index.js
The application contained a few places where there were hardcoded Finnish URL paths. This PR removes them and replaces them the constants or with function parameters.
Tests were also adjusted.
=> Remove hardcoded paths

app/component/IntermediateLeg.js, app/component/SummaryRow.js, app/component/TransitLeg.js
- Real time indication to itinerary page
=> DT-4120: Real time indication in itinerary page

app/component/StopsNearYouContainer.js, app/component/StopsNearYouPage.js, app/component/map/StopsNearYouMap.js, app/routes.js
- Refactor rendering of near you page to be more in line with other pages
- This might fix the back button issue, but difficult to confirm locally
- 
=> DT-4076: Fix stops near you back arrow

app/component/DepartureTime.js
=> DT-4122: real time indication in route page

app/component/AlertList.js, app/component/RouteScheduleContainer.js, app/component/route.scss, app/component/stop.scss, app/routeRoutes.js
- Adding map to timetable and disruptions view
- Scrolling of list on timetable and disruptions view
=> DT-4104: Mobile back arrow missing from route view's timetable and disruptions view

digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json, digitransit-search-util/packages/digitransit-search-util-helpers/package.json, digitransit-search-util/packages/digitransit-search-util-query-utils/package.json, digitransit-store/packages/digitransit-store-future-route/package.json
- Newest shared components to npm
=> DT-4131: Newest shared components to npm

app/component/DepartureListContainer.js, app/component/DepartureRow.js
- Juuri nyt- tab marked as a table
- Didn't touch the Timetable tab as we do not have a final design for it
=> DT-3819: Stop page accessibility fixes

app/component/navigation.scss
=> DT-4129: Itinerary settings clipping error in mobile

app/component/DepartureListContainer.js, app/component/stop.scss
=> DT-4119: Realtime indication broken in Stop page

app/component/RouteScheduleHeader.js
- Destination name is now correct when printing
=> DT-4128: Route / timetable / print prints wrong header

app/component/RoutePage.js
- Send redirect instead of server side navigation when user opens a route page that does not exist
- The redirect is to a page that does not exist. Should we have a page that lists all routes?
=> DT-4087 Replace all instances of potential server side navigation with redirect exception

app/component/customize-search.scss, app/component/navigation.scss
=> DT-4150: Mobile content clipping on Route-page

app/component/StopsNearYouPage.js, digitransit-search-util/packages/digitransit-search-util-query-utils/index.js, digitransit-search-util/packages/digitransit-search-util-query-utils/package.json
- Alerts with severityLevel 'WARNING' are shown in stops near you page and front page
=> DT-4126: Change stops near you alert filtering rules

app/store/ViaPointStore.js
- Change emit() to emitChange() in ViaPointStore
=> DT-4135: Via point is lost when navigating back from itinerary view

digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Itinerary page suggests own locations again
=> DT-4151: Itinerary page does not always suggest own locations

app/component/DisruptionBanner.js
- Only add alerts with unique description
=> DT-4135: Filter identical alerts in stopsnearyou view

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Tab keycode triggers blur in digitransit-component-autosuggest
=> DT-4159: Inaccessible search breaks accessibility of several pages

app/component/StopsNearYouContainer.js, app/translations.js
- Screen reader now announces when the stop listing is updated by the user
=> DT-4136: Stops near you page dynamic content accessibility

digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.scss
- No more highlighted suggestions on mobile
=> DT-4153: Mobile search quirks

app/component/AlertList.js, app/component/BackButton.js, app/component/Favourite.js, app/component/Icon.js, app/component/PatternStopsContainer.js, app/component/RouteAlertsRow.js, app/component/RoutePage.js, app/component/RoutePatternSelect.js, app/component/RouteScheduleContainer.js, app/component/RouteScheduleTripRow.js, app/component/RouteStop.js, app/component/RouteStopListContainer.js, app/component/route.scss, app/translations.js
=> DT-3818: Line page accessibility fixes

.github/workflows/next-dev-pipeline.yml
- Send a message regarding published packages to slack
=> ci: slack integration for package publishing

app/component/SummaryPage.js, app/component/map/Map.js, app/component/map/SelectFromMapPageMap.js
- Fix wrong zoom level in itinerary view
- Stop the map props leak from SelectFromMapPageMap
=> DT-4172: Wrong zoom level in desktop itinerary view

digitransit-component/packages/digitransit-component-favourite-modal/package.json, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/DesktopModal.js, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/MobileModal.js, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/translations.js, digitransit-component/packages/digitransit-component-favourite-modal/src/index.js
- accessibility improvements to add favourite modal
=> DT-3821: accessibility improvements to add favourite modal

app/component/StopsNearYouContainer.js
- Show more- button is now hidden when no more stops are available
=> DT-4097: Stops near you page when all stops are shown in the listing

app/component/RoutePage.js, app/component/route.scss
- fix: make route page tabs selectable via keyboard
=> DT-4167: make route page tabs selectable via keyboard

app/component/IconWithIcon.js, app/component/RouteAlertsRow.js, app/component/route.scss, sass/base/_base.scss
- The icon is styled according to design
=> DT-4163: Disruption tab picto is off

app/component/MessageBar.js, app/component/MessageBarMessage.js, test/unit/component/MessageBar.test.js
- Error notices trigger an alert to screen reader users so that the error content is read out loud
=> DT-4139: Accessible error notices

app/component/map/GenericMarker.js, app/component/map/GeoJSON.js, app/component/map/IconMarker.js, app/component/map/LocationMarkerWithPermanentTooltip.js, app/component/map/SpeechBubble.js, app/component/map/non-tile-layer/LegMarker.js
- fix: dont pass focus to map items
=> DT-4168: Dont pass focus to map items

digitransit-util/packages/digitransit-util-day-range-allowed-diff/package.json, digitransit-util/packages/digitransit-util-day-range-pattern/package.json, digitransit-util/packages/digitransit-util-enrich-patterns/package.json, digitransit-util/packages/digitransit-util/package.json, yarn.lock
- Remove unnecessary publish scripts from shared component's package.json
=>  Remove yarn login

app/component/ItinerarySummaryListContainer.js, app/component/SummaryRow.js, app/component/WaitLeg.js, app/component/WalkLeg.js, app/component/summary-row.scss, app/translations.js, sass/base/_elements.scss
- Platform/track shown on itinerary suggestions
- Correct font-weight on departure times
=> DT-4156 & DT-4182: Show platform/track on itinerary suggestion

app/component/SummaryPage.js
=> DT-4186: fix direct link to bikeAndVehicle crashes page

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js, digitransit-component/packages/digitransit-component-suggestion-item/package.json, digitransit-component/packages/digitransit-component-suggestion-item/src/index.js
- Make add favorite buttons usable with keyboard
- Add focus style to autosuggest x button
- Autosuggest items no longer get clipped when using custom text spacing
=> DT-3820: Front page accessibility fixes

app/util/queryUtils.js
- Parse undefined intermediate points 
=> DT-4204: Unfinished middle point with screen size change

app/component/AlertList.js
=> DT-4170: Inform screen readers of 'No disruptions' state in route page

digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-editing-modal/package.json, digitransit-component/packages/digitransit-component-favourite-editing-modal/src/index.js, digitransit-component/packages/digitransit-component-favourite-modal/package.json, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/DesktopModal.js, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/MobileModal.js, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/desktop.scss, digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/mobile.scss
=> DT-4209: Favourite component

app/client.js, app/component/AppBarContainer.js, app/component/AppBarHsl.js, app/component/IndexPage.js, app/component/SummaryPage.js, app/component/SummaryPageContainer.js, app/routes.js, app/stopRoutes.js, test/unit/AppBarHsl.test.js
- Use createInitialFarceRouter so SSR results are used in client side rendering too
- Avoid rendering different content SSR vs client
- Refactor SummaryPage to be loaded from a container through QueryRenderer so the same component can be used in SSR too to avoid issues
- Refactor app bar rendering
- Check that the implementation matches the design, when such …
=> DT-4184 Improvements to server side rendering

app/component/RouteHeader.js, app/component/RouteNumber.js, app/component/map/map.scss, app/component/map/route/TripMarkerPopup.js, sass/base/_base.scss
=> DT-4164: map vehicle popup styles are off

app/component/RouteAlertsRow.js, app/component/route.scss, test/unit/component/RouteAlertsRow.test.js
=> DT-4181: bad link style

app/component/front-page.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-editing-modal/src/index.js, digitransit-component/packages/digitransit-component-favourite-modal/src/index.js, digitransit-component/packages/digitransit-component-traffic-now-link/package.json, digitransit-component/packages/digitransit-component-traffic-now-link/src/helpers/styles.scss
=> DT-4211: hsl.fi and reittiopas.hsl.fi look different

app/component/StreetModeSelectorButton.js
=> DT-4078: Metro icon is black (ipad & chrome) 

digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js
- moving shimmer to above button
=> DT-4215: Favourite component - shimmer

digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/styles.scss
=> DT-4215-b: Favourite component - shimmer

app/component/AppBarHsl.js
=> DT-4224: Language changing issues

app/component/map/SelectFromMapPageMap.js
- Scale control hidden when using desktop fromMap modal
=> DT-4236: fix scale control showing under confirm button

app/component/SummaryPage.js, app/translations.js
- Add accessibility alert when biking and walking results are loaded
=> DT-4147: Indicator when walking/biking results are loaded

app/component/Icon.js
- Default outline set to 0 for icons
=> DT-4214: don't highlight icons

digitransit-component/packages/digitransit-component-favourite-modal/src/helpers/MobileModal.js
=> DT-4226: Border of name field in create/edit favorite dialog disappears in mobile

config/rollup.config.js, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.scss, digitransit-component/packages/digitransit-component-autosuggest/src/index.js, package.json, yarn.lock
- Use react-modal always on mobile search.
- Fix scroll position resetting when mobile search is closed.
=> DT-4217: Mobile search resets scrolling

app/component/StopsNearYouContainer.js, app/component/map/StopsNearYouMap.js, app/util/sortUtils.js
- Favourites from only the initially loaded stop list will be prioritized if they are close enough to the user or the current location.
=> DT-3841: Favorite stops listing logic in "Nearby stops" view

app/component/RouteStop.js
- no more crashing when stoptime is undefined (tested with route 453 @ 10:00 (Leaves is empty and Next 17:05)
=> DT-4235: Route page crashes on route 455

digitransit-component/packages/digitransit-component-favourite-bar/src/helpers/translations.js, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js
- Describe what the favourite buttons do to screen readers
=> DT-4220: Announce selection of a favourite to screen readers

app/component/stop-cards.scss
=> DT-4257: Zone icon overlaps with terminal page header text

sass/base/_base.scss
=> DT-4255: Login modal breaks underlying page layout on mobile

app/component/DatetimepickerContainer.js, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileDatepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobilePickerModal.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileTimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/utils.js, digitransit-component/packages/digitransit-component-datetimepicker/src/index.js, package.json, yarn.lock
- Add new datetimepicker for mobile according to design
- Add placeholder code for future Ab testing of new design
- Currently old version is shown by default. New version can be tested with variable testVariant in DatetimepickerContainer.js
- Version 0.4.1 of digitransit-component-datetimepicker is old version and 0.5.0 is new one …
=> DT-4155: New departure/arrival time selection

digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.scss, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Fix selecting suggestion by pressing enter.
=> DT-4252: Mobile search accessibility

app/component/AppBarContainer.js, app/component/TopLevel.js
- Fixed this issue with non-hsl desktop layout, however didn't do anything about mobile as the top navigation menu structure will change
=> DT-4199 Clicking top menu logo does not clear side bar error

app/component/DepartureListContainer.js, app/component/DepartureRow.js, app/component/stop.scss
- Show canceled trips as canceled on stop and terminal pages
=> DT-4263 Terminal page does not indicate canceled departures in 'Right now' tab

app/component/ItineraryPageMap.js, app/component/RouteMapContainer.js, app/component/RoutePage.js, app/component/SummaryPage.js, app/util/patternUtils.js, test/unit/component/RoutePage.test.js
- Route page compares pattern's active dates with current date.
- SummaryPage checks that searched time is in 12h range to show vehicles
- ItineraryPageMap checks the prop from SummaryPage for showing vehicles
=> DT-4161: Route page shows vehicles when route is inactive

app/component/CardHeader.js, app/component/map/tile-layer/MarkerSelectPopup.js, app/component/map/tile-layer/SelectParkAndRideRow.js, app/component/map/tile-layer/TileLayerContainer.js, test/unit/component/map/tile-layer/MarkerSelectPopup.test.js
- Icon color on park and ride -popup (using config's primary color)
=> DT-4239: Parkride popup icon is black

app/component/StopsNearYouPage.js
- Modal won't get rendered briefly when entering the page
=> DT-4123: Fix near you page location modal rendering

app/component/RouteNumber.js
- Don't use same colour for route number bar and text in summary page
=> DT-4277 Route numbers are not shown in summary page

app/component/WeatherDetailsPopup.js
- Weather description texts were missing for night time icons. This pull request fixes that issue.
=> DT-4274: Missing weather description text(s)

app/component/RoutePage.js
- Start mqtt client when navigating to trip view from some other view
=> DT-4273 No vehicles shown when navigating to trip page from another view

digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/index.js
=> DT-4281: Stops near you ignores reittiopas origin

app/component/route.scss
- Don't put alert icon and departure time on different rows
=> DT-4275 Trip page layout breaks with alerts

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.scss
- minimum font size must be 16px on input otherwise zooming happens (iOS)
=> DT-4284: Mobile search is zoomed in on iOS 

app/component/navigation.scss
- Remove extra line in summary page, when time or date box is clicked.
=> DT-4288: Strange extra line in summary page

app/component/StopNearYou.js, app/component/StopNearYouHeader.js
=> DT-4280: Broken stop links in stops near you page

app/component/FuzzyTripLink.js, app/component/RouteHeader.js, app/component/TripLink.js, app/configurations/realtimeUtils.js, app/util/mqttClient.js, app/util/timeUtils.js, test/unit/util/mqttClient.test.js, test/unit/util/timeUtils.test.js
- Adds some validation for missing trip information
- Fixes issue where UI was expecting HSL HFP topic structure to use 29 hour clock but actually it uses 24 hour
- Formats times into 24 hour format in vehicle popups
=> DT-4258 Route page crashes at midnight

app/component/SearchSettingsDropdown.js, app/component/searchSettingsDropdown.scss
- show km/h for walking speed options
=> DT-4254: show kmh for walking speed options

app/component/BicycleLeg.js, app/component/EndLeg.js, app/component/TransitLeg.js, app/component/ViaLeg.js, app/component/WaitLeg.js, app/component/WalkLeg.js
- Links work with NVDA on
- Added screenreader descriptions for buttons
=> DT-4279: Itinerary detail view accessibility bugs

app/component/StopsNearYouPage.js
=> DT-4829: Stops near you does not remember geolocation permission

digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
=> DT-4306: Stop & route search in hsl.fi does not obey language selection

app/component/IndexPage.js, digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-traffic-now-link/package.json, digitransit-component/packages/digitransit-component-traffic-now-link/src/helpers/styles.scss
=> DT-4305: hsl.fi dev and next-dev still look different

app/component/SummaryPage.js
=> DT-4301: Selecting bike+public doesn't reset highlighted itinerary index

app/component/summary-row.scss
=> DT-4196: Not enough padding on the left for citybike legs with non-hsl configs

app/component/bubble-dialog.scss, app/component/stop.scss
=> DT-4285: Stop page layout with virtual monitor link

app/action/PositionActions.js, app/component/StopsNearYouPage.js
- Better gelocationing for safari in stopsNearYou
=> DT-4289 part 2

app/component/map/GeoJSON.js
=> DT-4314: Jyvaskyla UI crashes when map is zoomed

app/component/navigation.scss
=> DT-4316: Some pages cannot be scrolled on mobile

app/component/map/map.scss, app/component/map/tile-layer/SelectStopRow.js, app/component/map/tile-layer/Stops.js, app/store/MapLayerStore.js, app/util/mapIconUtils.js
- icon and color of ferry terminal
- icon when selecting from popup
- popup size
=> DT-3691: Ferry terminals on map

app/component/AppBarContainer.js, app/routeRoutes.js
- Using normal Title instead RouteTitle and always shows logo (mobile)
=> DT-4319: Route page header layout is broken in Waltti

app/component/LangSelect.js, app/component/navigation.scss, test/unit/component/LangSelect.test.js
=> DT-4196: Language selection does not work properly in waltti

app/component/map/map.scss
=> DT-4331: Extra whitespace on frontpage map location popups

app/component/map/map.scss
=> popup-fix: (DT-4331: Extra whitespace on frontpage map location popups)

app/component/IndexPage.js, app/component/OriginDestinationBar.js, app/util/apiUtils.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
- Bring focuspoint back to search
=> DT-4212: User location reference is never passed to search

app/component/route.scss
=> DT-4324: Change disruptions tab display on route page if there are no active disruptions

app/component/CardHeader.js, app/component/StopCardHeader.js, app/component/StopCardHeaderContainer.js
=> DT-4325: terminal page heading missing info

app/configurations/config.default.js, server/server.js
=> DT-4333: Fares don't work on local development

server/passport-openid-connect/openidConnect.js
=> DT-4346: Redis session length is too long

app/component/StopPageTabs.js, app/component/stop.scss
- Use router.replace instead of navigation history in stop page tabs
=> DT-4339: Inconsitent navigation

digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
=> DT-4342: fast use of enter breaks search

app/component/BackButton.js, app/component/DesktopView.js, app/component/IndexPage.js, app/component/ItineraryPageMap.js, app/component/ItineraryTab.js, app/component/SummaryNavigation.js, app/component/SummaryPage.js, app/util/queryUtils.js, digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-control-panel/src/index.js
- Try navigation using router.push from onclick handler, maybe it works better than found Link
- Make back button simpler and add option to pop last path section (fixes navigation from direct itinerary links)
- Simplify index page and stopsnearyou button rendering
- Fix broken via point adding from itinerary map
- Remove dead prop from Stopsneayou buttons
=> Refactor back button usage and some other stuff

app/component/TransitLeg.js, app/component/itinerary.scss
=> DT-4345: show zone icons for single zone transit legs

app/component/TransitLeg.js
- show unknown zone icon for single zones - see f.ex. riihimäki -> hyvinkää
=> DT-4345: show unknown zone icon for single zones

app/component/SummaryPage.js, app/component/SummaryPlanContainer.js
=> DT-4355: Navigating to bike and public itineraries that don't exist leads to unhandled error

digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js
- Fixed onClick and closing also with esc
=> DT-4354: Favorite dropdown control only opens the menu

app/component/map/GenericMarker.js
=> DT-4352: Popup broken in walk and bike itinerary maps

app/component/StreetModeSelectorWeatherLabel.js, app/component/SummaryPage.js
- not showing weather iconId is NaN
=> DT-4372: NAN value for weather icon

.github/workflows/next-prod-pipeline.yml
- Changed DOCKER_DEV_TAG from next to latest
=> DT-4341: Fix incorrect github action flow for next-prod

app/component/map/StopsNearYouMap.js, app/component/map/tile-layer/Stops.js, app/util/mapIconUtils.js, static/assets/svg-sprite.default.svg, static/assets/svg-sprite.hsl.svg
- Highlight terminals on map
- Highlight terminals/stations instead of stops in stopsNearYou
=> DT-4330: Highlight terminals

app/component/AppBarHsl.js, server/passport-openid-connect/openidConnect.js
- Fix bug where sessions of unauthenticated users were saved to redis. 
- Fix bug where login couldn't return to url with multiple query params.
=> DT-4346 part2

digitransit-component/packages/digitransit-component-abtesting/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss
- Small style changes for consistency between digitransit and hsl.fi
=> DT-4419: Apply timepicker AB testing to hsl.fi

digitransit-component/packages/digitransit-component-abtesting/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss
- set font size to 16 on mobile inputs to prevent problems on safari
=> DT-4440: New timepicker scales hsl.fi frontpage in iPhone

digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-bar/src/index.js
- Fix favourite bar localization.
=> DT-4443: Shared component localization broken again

digitransit-component/packages/digitransit-component-abtesting/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobilePickerModal.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/translations.js
- Add some missing translations
=> DT-4451: Fix languages for new datetimepicker

digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss
=> DT-4442: Stops near you icons don't fit in desktop

app/component/StopsNearYouPage.js, app/component/map/MapWithTracking.js, app/component/map/StopsNearYouMap.js, app/util/stopsNearYouUtils.js
- Walk routing is no longer done and previous routes are removed from the map when user updates map center
- Walk routing is done again if user returns the map back to their geolocation
=> DT-4436: Change walking routes and location marker logic in nearby stops

digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-suggestion-item/package.json, digitransit-component/packages/digitransit-component-suggestion-item/src/index.js
=> DT-4457: Favorite bar dropdown crashes when favorites are included in it

app/component/CityBikeNetworkSelector.js, app/util/citybikes.js, app/util/planParamUtil.js, test/unit/util/planParamUtil.test.js
- Add support for citybike network settings from old settings that always had network name in uppercase letters in localstorage
=> DT-3990 City bike networks settings are not compatible between ui versions

app/component/BikeRentalStationContent.js
- Redirect to /pyoraasemat so 404 page is rendered if bikerental station page is missing
=> DT-4200 Entering a bike rental station page that does not exist should be handled gracefully

app/component/BicycleLeg.js, app/component/ViaLeg.js, app/component/WalkLeg.js, app/component/map/GenericMarker.js, app/component/map/PointFeatureMarker.js, app/component/map/PopupHeader.js, app/component/map/map.scss, app/component/map/popups/LocationPopup.js, app/component/map/tile-layer/TileLayerContainer.js, app/util/otpStrings.js, sass/base/_base.scss, test/unit/component/map/PointFeatureMarker.test.js
- New design for location popups
=> DT-4335: Redesign map popup

app/component/StopsNearYouFavorites.js, app/component/StopsNearYouPage.js
- Favorites added or removed on other tabs get updated to the favorite tab
=> DT-4450: When in mobile nearByStops adding favorites should work without refresh

app/component/DepartureRow.js, app/component/StopNearYouHeader.js, app/component/StopsNearYouContainer.js
- Use tripHeadsign if headsign is not available. 
- Fixed undefined stop code error.
=> DT-4459: Missing route names on stops near you page

app/component/StopsNearYouMapContainer.js, app/component/map/StopsNearYouMap.js
- Map now works when active stops are not immediately found
=> DT-4476: Stops near you map crashes in ferry mode

app/component/MobileItineraryWrapper.js, app/component/StopsNearYouFavorites.js, app/component/StopsNearYouPage.js, app/component/SummaryPage.js, sass/base/_elements.scss
- Set a max height for non visible swipe tabs to limit the scrollable content
=> DT-4477: Empty space at the bottom of itinerary suggestions

app/util/colorUtils.js
- Fix LightenDarkenColor function as it did not work if returned r value was between 0 and 9.
- This bug was also in other waltti instances, such as Kuopio.
=> DT-4482: Tampere's hover color is invisible

app/configurations/config.hsl.js, app/configurations/config.matka.js
=> DT-4461: Use different URLs for espoo/helsinki and vantaa citybike networks

app/component/DateSelect.js, app/component/TimetablePage.js, test/unit/component/DateSelect.test.js
=> DT-4466: Modify the date range of the date selector in Stop view's timetable tab

app/component/StopsNearYouPage.js, app/configurations/config.hsl.js
- Bike stations are visible on map
- Stops near you pages include bike station view
- No citybike routing available yet
- Hide unfinished Favorites tab from stops near you
=> Configuration for preliminary bike season release

app/component/stop.scss, app/component/stops-near-you.scss
…p and stop near you pages
- Fix long route numbers did not fit inside route number container.
=> DT-4454: Route number does not always fit

app/component/route.scss
- Selector will now grow vertically with long names
- Also fixed problems with really long names in desktop (DT-4499)
=> DT-4498: Route pattern selector overflows in small mobile devices

app/component/navigation.scss
- Fix logo height - "The height of the logo is 30 px on mobile and 40 px on Desktop."
=> DT-4502: Fix waltti navbar logo height

app/component/RouteStop.js, app/component/TripRouteStop.js, app/component/route.scss
- Style tuning to match design
=> DT-4462: Fix the styles of route view's stops tab

app/component/DepartureTime.js
-  use minutesToDepartureLimit to show minutes
=> DT-4504: Showing minutes in Stop view

app/component/SummaryPage.js
- first selectable date is 9.8.2021
=> DT-4493: Modify the date range selector in itinerary view

app/component/RouteScheduleContainer.js
- first selectable date is 9.8.2021
=> DT-4468: Modify the date range of the date selector in Route view's timetable tab

app/component/RouteAlertsContainer.js, app/component/RoutePage.js, app/component/RoutePatternSelect.js, app/component/RouteScheduleContainer.js
- setting initial date to 9.8.2021
=> DT-4511: Query lines 9.8, not now, when entering route view

app/component/streetmodeselectorshimmer.scss, app/component/summary.scss
=> DT-4512: Autosuggest results are shown behind itinerary suggestions in itinerary page

app/component/ItineraryPageMap.js
=> DT-4491: Extra back button in itinerary details

app/component/stop.scss
=> fix: stop page route select modal overlay z-index

app/component/stop.scss
=> DT-4516: Useless scrollbar in stop page timetable tab

app/component/RouteStop.js, app/component/TripRouteStop.js, digitransit-component/packages/digitransit-component-abtesting/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileDatepicker.js
- Fix datetimepicker handling of summer time transition
- Problems also happened on android and desktop but iOS was most noticeable
- Also temporarily disable walking time display on route page
=> DT-4509: New date picker has errors in iOS

app/configurations/config.default.js
- Increased walking and cycling limits
=> DT-4480: Increase walking and cycling limits

app/component/RouteAlertsContainer.js, app/component/RoutePage.js, app/component/RoutePatternSelect.js, app/component/RouteScheduleContainer.js
=> DT-4515: Route page / disruption tab crashes always

app/component/navigation.scss, app/configurations/config.hsl.js, package.json, yarn.lock
- new site header
- fix citybike link
=> Some minor changes and fixes

app/component/BikeRentalStationContent.js
- Render citybike purchase link only in client to make sure it's meant for right language
=> DT-4519 Wrong language in citybike links

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-favourite-editing-modal/package.json, digitransit-component/packages/digitransit-component-favourite-modal/package.json, digitransit-component/packages/digitransit-component-icon/package.json, digitransit-component/packages/digitransit-component-icon/src/assets/subway.svg, digitransit-component/packages/digitransit-component-suggestion-item/package.json, digitransit-component/packages/digitransit-component-traffic-now-link/package.json
- Metro icon svg had height and width assigned. Those are removed and metro button icon is fine now.
=> DT-4520: Icon in stops near you metro button is too small

app/configurations/config.lappeenranta.js, app/configurations/config.matka.js
- Enabled citybikes for lappeenranta
- Enabled hsl area citybike networks for matka
- Updated hsl aread citybike network URLs
***NOTE: availability information should be configured on a network basis before lappeenranta citybikes can be enabled for matka*** 
- Merge …
=> DT-4472 Citybikes for opas.matka.fi

app/component/SwipeableTabs.js
- Fixed navigating swipeable tabs with tab
- Refactoring of limiting navigation to inactive tabs
=> DT-4500: swipeable tab navigation fix

app/component/RouteStop.js, app/component/RouteStopListContainer.js, app/component/TripRouteStop.js, app/component/TripStopListContainer.js, app/configurations/config.default.js, test/unit/component/RouteStopListContainer.test.js, test/unit/component/TripStopListContainer.test.js
- Remove all code related to showing distance to nearest stop in route page
- The element was hidden already before in a hotfix 
=> DT-4497: Route view shows NaN time 

app/component/SummaryPage.js
=> DT-4526: Bike and public options shimmer remains forever if settings are changed

app/component/SummaryPlanContainer.js
=> DT-4531: Itinerary suggestion scroll height persists from summary page

app/component/RoutePatternSelect.js, app/component/route.scss
- Fix display long subtitles
- Hide special routes subtitle if there are no special routes
- did not fix: clicking dropdown again does not close it
=> DT-4517: Route variant selector issues

app/component/SwipeableTabs.js
- Set focusables on component mount
=> DT-4536: Swipe navigation bug

app/component/SummaryPlanContainer.js
=> DT-4543: Mobile itinerary view not accessible from summary page

app/configurations/config.default.js
=> DT-4541: Remove timetable pdf urls from tampere stop views

app/configurations/config.default.js
=> DT-4541-master: removed links to tampere pdf timetables

app/component/StreetModeSelector.js
=> DT-4545: next-waltti crashes on itinerary search

app/component/SummaryPage.js
=> DT-4534: Back button behavior in itinerary details page

app/configurations/config.walttiOpas.js
- Remove hard-to-maintain area polygon definitions from waltti opas
- Add Salo feedId and a default endpoint to waltti opas
=> feat: add Salo to walttiOpas

app/component/StopsNearYouFavouritesContainer.js
- Add lat and lon to bikeStations query so distance can be calculated
=> DT-4569: Favorites near you view does not sort bike stations by distance

app/configurations/config.hsl.js
=> DT-4577: Update citybike links

app/component/SummaryPage.js
- crash was because of trying to use array spread operator on non iterable element (undefined)
=> DT-4572:  fix crash on reloading bike + public view

app/component/StopsNearYouPage.js
=> DT-4570: Stops near you view ignores 100m distance threshold in map navigation

app/component/StopsNearYouPage.js
=> DT-4571: Search box appears/disappears with delay when swiping stops near you tabs

app/component/RoutePatternSelect.js
=> DT-4350-hotfix: Prevent crashing if no pattern

app/component/map/PopupHeader.js, app/component/map/popups/LocationPopup.js
- Add zone next to the "Selected location" text in map popups that don't have an address.
=> DT-4522: Add zone information to selected location popups

app/component/Icon.js, app/component/RouteNumber.js, app/component/summary-row.scss, sass/base/_elements.scss
=> DT-4581: Show the bike count of the pickup station in itinerary summary

app/configurations/config.tampere.js, app/util/mqttClient.js
- Don't use headsigns that contain / in topic subscriptions
- Tampere static message updates
=> DT-4190 part 3 Bring all relevant changes from master to next

app/component/SwipeableTabs.js, app/component/itinerary.scss
- Static position for swipe navigation in desktop views
=> DT-4567: Static position for swipe navigation in desktop views

app/component/BikeRentalStationContent.js, app/component/StopsNearYouPage.js
=> DT-4594: Bike station page for waltti crash 

app/component/SwipeableTabs.js, app/component/stops-near-you.scss
=> DT-4597: White space under summary view title

app/component/RoutePatternSelect.js
- No dropdown if there is two or less variants. And no direction change button if only one variant.
=> DT-4599: Route page shows a dropdown when there are only 2 main variants

app/component/StopPageMap.js, app/component/map/tile-layer/CityBikes.js, app/util/mapIconUtils.js
- Black text on yellow availability badge
- Highlight citybike map icon when selected
=> DT-4574: update drawing of citybike stops on map

digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss
=> DT-4601: Stops near you buttons have wrong cursor style

.stylelintrc.json, app/component/DatetimepickerContainer.js, app/component/QuickSettingsPanel.js, app/component/front-page.scss, app/component/quickSettingsPanel.scss, digitransit-component/packages/digitransit-component-datetimepicker/README.md, digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss, digitransit-component/packages/digitransit-component-datetimepicker/src/index.js, yarn.lock
- Change datetimepicker to use new design
- Also change react-autosuggest library to react-select
- Some small changes are still coming in another ticket
=> DT-4535: Update Time picker on desktop

app/component/DepartureListContainer.js, app/component/DepartureRow.js, app/component/RouteStop.js, app/component/route.scss, app/component/stop.scss
- Remove redundant linear gradient
- Drop off only- info is displayed on its own row
=> DT-4521: Stop addresses are cut short in firefox route page

app/component/BikeRentalStationContent.js
- Missing bike rental station is handled more gracefully.
=> DT-4614: Missing bike rental station is not handled gracefully

app/component/map/StopsNearYouMap.js
- Only query one walking route
- Don't query walking route in bus or tram view unless first stop in the list is a favorite
=> DT-4583: Nearby stops: Walking routes

app/component/LoadingPage.js, docs/ZIndex.md
- fix: loading icon behind map
=> DT-4593: fix route page loading spinner

app/component/stops-near-you.scss
=> DT-4602: Stops near you view is broken in Turku

app/component/route.scss
- removed useless control elements from print view
- made the timetable actually visible in the print view
=> DT-4611: fix route page printable timetable

digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss
- Small style fixes
- Compatibility for hsl.fi
- Some accessibility fixes
=> DT-4609: Datetimepicker fixes

digitransit-component/packages/digitransit-component-control-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/src/helpers/styles.scss
=> DT-4607: Stops near you alert icon is too large

app/component/RoutePage.js, app/component/RoutePageControlPanel.js, app/component/RouteScheduleContainer.js, app/component/route.scss
=> DT-4622: Static title and print buttons in stop timetable page

app/component/AppBar.js, app/component/LoginButton.js, test/unit/AppBar.test.js
=> DT-4631: Login redirect for waltti

digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/styles.scss
- Fixed. This issue happened in fact on itinerary page and on indexpage, if user has route / stop suggestions open
=> DT-4627: Icons on date time picker move when scrolling on Itinerary page 

app/configurations/config.hsl.js, app/configurations/config.waltti.js, server/passport-openid-connect/Strategy.js, server/passport-openid-connect/openidConnect.js, server/server.js
=> DT-4633: OIDC fixes for waltti ui

app/component/RouteScheduleContainer.js, app/component/route.scss
=> DT-4634: fix broken route view timetable styles on mobile

app/component/route.scss, app/component/routeScheduleDropdown.scss
=> DT-4637: route view timetable layout bug

app/component/route.scss
- Fixed a bug where printable timetable did not show all the departures but instead cut the list in half
=> DT-4646: route page printable timetable bug

app/component/DepartureTime.js, app/component/RoutePage.js, app/component/TripRouteStop.js, app/component/TripStopListContainer.js, app/component/route.scss
- fixed layout problems described in the ticket/figma
- still to be done: indicate route left behind with gray color on map and possibly a dynamic divider between header and content
=> DT-4613: Route page layout fixes

app/component/StopsNearYouContainer.js, app/component/StopsNearYouPage.js, app/component/stops-near-you.scss, app/translations.js
- Add a banner if no stops are found
=> DT-4618: Stops near you page if no stops are found for some reason

app/configurations/config.waltti.js
=> DT-4656: enable message bar alerts in waltti instances

app/component/CityBikeLeg.js, app/component/Icon.js, app/component/IconWithIcon.js, app/component/RouteNumber.js, app/component/city-bike.scss, app/component/itinerary.scss, app/component/map/ItineraryLine.js, app/component/map/map.scss, app/component/map/non-tile-layer/CityBikeMarker.js, app/util/legUtils.js, app/util/mapIconUtils.js, sass/base/_elements.scss
- Better accessibility for Citybike capacity color
- Some styling tweaks and fixes for citybike capacity badge
=> DT-4610: Citybike capacity color accessibility

app/configurations/config.tampere.js
=> DT-4659: enable tram routing in tampere instance
