app/client.cjsx, app/component/map/map.cjsx
When user does:
1) Open map
2) Move map 
3) Click stop icon
4) Move to stop page
5) click back
Map is now in different zoom and place than in step 4. We should keep map in same zoom level and location in these kind on cases.
=> Map page and back button

app/config.default.coffee, app/config.hsl.coffee, docs/Installation.md, package.json, webpack.config.js
Relates closely to: https://github.com/HSLdevcom/digitransit-deploy/pull/48
1) Read Installation.md 
2) Try to e.g. "npm run dev --digitransit-ui:SERVER_ROOT=http://testing.digitransit.fi"
3) Check with chrome developer tools that requests go to "testing"
We still need to improve deployment script so that correct backends are used
=> Configuration support for test and dev environments DT-242

app/component/util/not-implemented.scss
Makes the "not implemented" popup display title,icon, links also in non hsl version
=> Use color variable name that is visible also in non hsl version

server/server.js
Live reload still does not work but atleast you can access (and manually refresh) the app from ip other than 127.0.0.1
=> Allow accessing dev-mode-app with ip other than localhost

app/component/departure/departure.scss
Overwrite leaflet svg z-index for vehicle icon. Otherwise disruption icon drops below vehicle icon.
[DT-556](https://digitransit.atlassian.net/browse/DT-556)
=> DT-556 Disruption info icons are not displayed correctly in popup

app/component/map/map.scss
This currently disables the “cursor: pointer” rule for some reason, but
is the only way to get clicks bubbling trough on Firefox.
=> DT-645: Add pointer-events: none for stops

app/component/disruption/disruption-info.cjsx
Reduces the number of queries done while initially loading the front
page from two to one. When opening the modal, another query is done to
fetch full alert information as required by the modal contents.
See [DT-450](https://digitransit.atlassian.net/browse/DT-450).
=> feat: only include modal when it should be open

app/component/departure/departure-list-container.cjsx, app/component/departure/departure-time.cjsx, app/component/departure/departure.cjsx, app/component/departure/departure.scss, app/queries.js, build/schema.json, sass/themes/default/_theme.scss, sass/themes/hsl/_theme.scss
[DT-490](https://digitransit.atlassian.net/browse/DT-490)
- Styles may be improved still a bit, however they also need to be changed quite much when the new two tabs design is implemented.
- There is a mode for mocking in the demo.
- Deployment of new GraphQL cancelation info is required for this branch to work.
=> Dt 490 show disruption info in routing results

app/component/departure/departure.scss
- Add negative margin so that the time padding can be increased
- Make the stop-card version of departure list still use regular padding
See [DT-680](https://digitransit.atlassian.net/browse/DT-680)
=> feat: enlargen padding of departure list canceled time background

app/component/departure/next-departures-list.cjsx, app/component/favourites/favourite-route-list-container.cjsx, app/component/route/nearby-route-list-container.cjsx
Improve sorting of departures in nearby and favourites tabs. Sometimes the sort was off in the times.
Previously the object passed to NextDeparturesList was not the row object so sorting was tricky. Now container components, favourite and nearby containers, pass full row objects.
=> feat: improve sorting by passing row objects

app/component/itinerary/transit-leg.cjsx, app/translations.coffee
* Show the destination name together with the alight text, not on the next line.
* If transit mode is AIRPLANE, do not show the alight text
=> Display destination name together with alight text. Hide alight text if airplane

app/component/front-page/front-page-panel.cjsx, app/component/map/map.cjsx, app/util/jankmeter.js
DT-836
Windows phone support is pretty bad with map tracking; the events just don't seem to fire reliably and even then the requestAnimationFrame seems to fire only once. Debugging this should wait for Win10 dev laptop.
=> DT-836 Measure frame jank in map and nearby routes

app/component/map/map.scss, sass/themes/default/_theme.scss, sass/themes/hsl/_theme.scss
Make it possible to configure the font and weight for leaflet markers.
=> Use configured font from theme in leaflet-container

app/component/map/map.scss, sass/base/_helper-mixins.scss
See #600 
Not using mixin @font-book as we meed to set font weight differently in the map in our theme.
=> Use mixin and include for font style in map container

package.json
=> try and kill children on exit, also run webpack dev server with forever

app/action/PositionActions.js
The problem occured, when inside([pos.lon, pos.lat], config.areaPolygon)
evaluated to true == User location was outside of the configured area
polygon. E.g. when users outside of Helsinki area would go to a site using
HSL config.
The bug was caused by trying to import defaults from EndpointActions.js,
when there are none.
=> Fix setOriginToDefault bug.

app/component/map/line.cjsx, app/config.default.coffee, app/config.hsl.coffee
Make thickness of itinerary lines in map configurable without breaking existing possibility to set `thin` true or false.
Styles for markers will be a separate pull request.
=> Make it possible to configure the thickness of itinerary line

package.json
When running digitransit-ui in dev mode like this `npm run dev` and pressing `CTRL-C` to stop it, the terminal window / shell is killed as well. (At least, this happens with terminator and zsh)
This PR tries to fix that, by only killing child processes and not the parent process, using `pkill`
=> Attempt to not kill parent process when pressing CTRL-C

test/flow/script/run-ui-tests.sh
=> disable ie

sass/themes/default/_theme.scss
Fixes issue https://digitransit.atlassian.net/browse/DT-1106
Seems to already work for HSL theme. Changing the default theme button hover background color for now. It should be further improved when improving "matka.fi" colors next week.
=> style: tune default theme button hover color

app/component/util/DesktopWrapper.js, app/config.default.coffee, app/config.hsl.coffee
=> Make it configurable to use the DesktopWrapper

app/component/map/generic-marker.cjsx, app/config.default.coffee, app/config.hsl.coffee, app/config.joensuu.coffee
… the zoom level. Only for non-tile map.
=> Hide generic marker text at certain zoom levels

test/flow/script/run-ui-tests.sh
The real issue I had running the local tests was caused by this: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3280
(even though running selenium alone worked fine)
Still, some improvements to the script should be made to avoid misleading messages like `unary operator expected`
…oid unary operator expected message. More verbose output.
=> Minor improvements to the ui test script

app/component/search/SearchInputContainer.js
DT-465 was an old bug report and probably things have changed many times since then. 
I was not able to reproduce the favourite problem at all.
For the other half I am not sure if the original problem is still there. I however fixed the  SearchInputContainer so that now it is not possible to select entry with Enter key if there are no suggestions present. Before the fix this was a problem with other browsers too.
=> do not allow selecting top suggestion if there are no suggestions

app/util/leg-text-util.js
=> Only use M for subway if shortName not available

app/config.default.coffee, app/config.hsl.coffee, app/config.joensuu.coffee, app/util/feedback.coffee
=> Make it configurable wether to allow the feedback popup

app/component/itinerary/ItineraryPlanContainer.js
Small fix to enable the "bullets" below the tab bar to be clicked. The invisible button was of a wrong size.
=> fix: size to auto

test/visual/components.js
=> Increase tolerance for non-deterministic visual tests

app/config.default.coffee, app/config.hsl.coffee, app/config.joensuu.coffee, app/meta.js
Make values in head tags configurable.
=> Make head tags configurable

app/component/map/tile-layer/SelectStopRow.js
Performing the following steps...
1. Click a stop cluster on the map
2. A popup appears allowing you to select a stop
3. The selectable stop row contains the first route number and additional route numbers departing from that stop
...this PR solves the following bug:
The list of additional route numbers contains the first route number as well (e.g. "7B, in addition: 7B")
=> Fix stop popup additional patterns

app/component/front-page/front-page-panel.scss
The front page tabs should open on top of the menu bar.
=> fix: z-index

app/util/geo-utils.js
This bug was probably born when the utilities were converted from CS to ES. Comparison operations like “a < b < c” are always evaluated sequentially in ES. Thus, the function never reached past the second condition, since true < 1000 = true.
=> fix geo-utility displayDistance bug

test/visual/components.js
=> Fix visual test syntax

test/flow/nightwatch.json
when this is integrated the downloaded firefox binary needs to be added to path in snap
`PATH="./firefox:$PATH"`
=> fix local firefox testing

app/config.hsl.js, app/config.joensuu.js, app/config.turku.js
=> Set default language to finnish for hsl, joensuu and turku configs

Dockerfile, app/server.js, package.json, static/svg-sprite.hsl.svg
Makes the docker build faster and resulting image smaller.
Fixes one svg file.
Fixes the server to really only use files from _static. 
- [?] doesn't break anything (passes `npm run test-local` and `npm run test-browserstack`)
- some randomness noticed
- [?] design is as expected. NOTE! visuals are compared using HSL theme (`CONFIG=hsl npm run dev`).
- [-] all new strings visible to users are
* [-] added to translations file
* [-] are translated to English, Finnish and Swedish (if not, add translations-needed label to PR)
- [-] all changed components
* [-] have examples
* …
=> Tune docker build

app/component/OriginSelector.js, app/component/Splash.js, app/component/splash.scss
=> Fix splash styles on firefox

app/component/CustomizeSearch.js
Set the default value of each slider to the respective
query parameter values if available
=> Initialize routing parameter sliders properly

app/component/IndexPage.js
=> Fix tab stats

.gemini.conf.json
=> Restrict parallel tests for gemini

webpack.config.js
=> Do not cache index page in ServiceWorker for now

app/component/route.scss
This only manifests itself when the disruption list for a route is scrollable. ITC the alert triangles remained absolutely positioned with the viewport and did not scroll with the list.
=> Fix layout bug where disruption icon is absolute-postioned to wrong container

app/component/summary.scss
If no route was found the “no route  found” message caused the page to be scrollable sideways on mobile.
=> Fix layout bug if no route found

app/component/DisruptionInfoButtonContainer.js, app/component/MainMenu.js
Disruption info button renders without the icon when there are no alerts (i.e. also when loading).
=> feat: always show disruption info button

app/translations.js
“Till hållplats” is too long to fit where it is used, replace with “Avstånd”
=> Replace swedish translation of 'to-stop' message

app/component/AboutPage.js, app/configurations/config.default.js, test/flow/page_object/about.js
Changes to AboutPage to make it more configurable. Each project is independent and adding translations to translations.js for hardcoded values make less sense. This change makes it possible to have several headers and more paragraphs beneath that. Added a configurable link as well. I have only changed config.default.js to demonstrate setup.
=> changes to About page to make it more configurable

README.md, app/client.js, app/configurations/config.lahti.js, docs/Themes.md, webpack.config.js
If CONFIG env var is set, npm build collects only the defined theme together with the default theme into the build. 
Custom configurations no longer require a matching scss theme, but  automatically use the default styles in absence of the scss  theme folder.
This PR includes https://github.com/HSLdevcom/digitransit-ui/pull/1404
=> Allow building with a selected theme

app/configurations/config.default.js
'digitransit' which was ment for matka.fi matched all waltti cities.
Also reittiopas will be present in many domain names.
Reordering the regex array fixes the problem.
=> Reorder piwik id mapping to avoid accidental matches

test/flow/tests/itinerary-search/itinerary-search.js
Because labeling conventions tend to change. Helsingin rautatieasema
is uniquely defined without the city name at the end.
=> Expect only defined name, not full label

app/component/OriginSelector.js
Favourites are also in the oldSearches list. This fix filters oldSearches before being added to the OriginSelector.
Console.log of - favourites and oldSearches in `app/component/OriginSelector.js`
=> NRP-1155: remove favourite duplicates in splash/origin selector  

app/component/AgencyInfo.js
The root cause is a data issue, but it doesn’t hurt to have some degree of sanity on our side. If we have an external link component it should never direct you to a relative path.
=> Fix agency links without protocol

app/component/map/Map.js, app/config.default.js
Today scale (referenced as scaleBar) and zoom control for Map have hard-coded positions.
This PR includes flexibility to configure these positions. Naturally, positions are defaulted to hard-coded values.
=> (Map-controls) Make scale and zoom position for map configurable

app/component/SummaryPlanContainer.js
Fixes an issue with url encoding searches, when the user clicks on items in SummaryPage.
Example that fails in our case, cannot handle slash.
'Harstad/Narvik Lufthavn, Evenes' -> 'Tromsø Lufthavn, Tromsø'
=> NRP-1344: fixes issue where searches are not url encoded

app/action/EndpointActions.js, app/component/GeopositionSelector.js, app/component/SplashOrChildren.js, app/store/EndpointStore.js
Delayed response for setting user's initial geolocation no longer closes the splash screen, if user has already started defining a location using the search modal.
- If user enters an address, it will be used as the start point
- If user closes the search modal without entering an address, geolocation will be used immediately after closing the modal.
=> Don't cancel user's search interaction by a geolocation change

app/component/CustomizeSearch.js, app/component/ResetCustomizedSettingsButton.js, app/component/Slider.js, app/routes.js
Fixes the functionality of the sliders in IE11 and allows the user to reset their settings. Note: React has issues with firing events in IE11 so the onChange is necessary in order to let the settings return to their default positions after reset. As a flipside this causes more load on the servers but since value is the attribute used in controlling sliders remotely, it's the best solution for the time being.
=> Ie11 slider reset fix

app/component/RouteMapContainer.js, app/component/map/Line.js
We have recently experienced this bug.
When investigated more closely, it was found out that one of the coordinates was lat: {lat: null lon: null}
This pull request fixes a possibility for such an issue by performing a check on the data before drawing the line.
=> Fixed the empty coordinate bug

app/component/stop.scss
This fixes a small styling issue that lead to a UI bug on larger mobile viewports, such as iPad.
=> Prevent stop page tabs from wrapping to multiple rows

server/hotLoadServer.js, webpack.config.js
Because that causes a CONNECTION_REFUSED error when the browser is not running
in the same host as the UI server.
=> Don't use localhost in dev server paths

app/client.js
Try to ease problem solving by passing piwik id to otp queries so that we can correlate ui logging with OTP
=> Pass piwik id to otp requests

app/component/IndexPage.js
From JIRA description: "Without location selected, the Nearby tab should include suggestions for locations. See layout: https://zpl.io/a4A7P Map would be in minimized mode (layout has it in maximized mode).
"
Displays Map in minimized mode, nearby is always default.
=> DT-2139: As a user without origin location detected, index page (start screen) should always display Nearby ("Lähelläsi") tab.

app/component/route.scss
This should fix the following bug
=> Fix route timetable scroll bug on MS Edge

app/configurations/config.hsl.js, app/configurations/waltti.js, server/reittiopasParameterMiddleware.js
Too old routing time in url (also in old reittiopas style url)
is now dropped, because router cannot find routes in the past.
Time limit is configurable, currently the default is 30 days.
=> Validate route request's time parameter

app/routes.js
Quick fix to prevent failed js and css fetches to be treated as successful index page urls.
=> Catch invalid paths

app/component/FavouritesPanel.js
Favourites panel ignored changes from favourite location editing.
Any change was displayed usually after 30s delay i.e. when time store
changed its value.
=> Update favorite locations panel when locations change

app/util/searchUtils.js
Old searches to stops stored the timetable link selection action with the search data all the way to the local storage. Attempt to pick such an old search in adding/editing a favourite place moved the application
suddenly and confusingly to the stop page. Fixed by resetting old search item state when composing a new search.
=> Reset state of old stop searches

app/component/search.scss
Change positioning from fixed to absolute.
This stop autosuggest panel from moving with the page if the page has scrolling.
=> Autosuggest panel positioning

app/component/OriginDestinationBar.js
Search parameters like departure time and transport type choices were removed when via point was removed from search form.
=> Removal of via point changed search parameters

app/routes.js, app/util/scroll.js
Steps to reproduce:
- Resize browser to mobile size (320x568)
- Search for `rauta`
- Select any suggestion
- Click origin select again, scroll to the bottom of the page and select one of the suggestions
Expected: 
Result:
=> Hsl-fi-75: scroll to top of the page on origin/destination select

app/component/ItinerarySummary.js
The purpose of this pull request is to fix the incorrect walking distance total shown in the mobile view. This previously used the backend-provided walkDistance field. Now the functionality is similar to e.g. PrintableItineraryHeader.
Bug report:
=> mobile-view-walk-distance-fix

app/configurations/config.default.js, app/configurations/config.hsl.js, app/util/planParamUtil.js
- Separate matka/hsl default values
- 'Ealier' button generated a query where filtering variable was not set
=> Itinerary filtering fixes

app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/util/modeUtils.js, app/util/planParamUtil.js, app/util/queryUtils.js, test/flow/page_object/customizeSearch.js, test/unit/queryUtils.test.js, yarn.lock
The purpose of this pull request is to recover from a partly invalid intermediatePlaces url parameter.
Previously the UI would crash if the parameter `intermediatePlaces=+` was provided. This is no longer the case.
In addition, some unit testing logic was added to the functionality.
=> DCW-21: fix for handling invalid intermediatePlaces query parameter

app/component/ItineraryLegs.js, app/component/TransitLeg.js, app/component/itinerary.scss, sass/base/_zindex.scss
The purpose of this pull request is to fix a z-index problem with the itinerary icons being drawn on top of the search panel autosuggest dropdown menu.
In addition, some `div` elements were changed to use `React.Fragment` to avoid polluting the DOM with a bunch of useless `div`s.
The only change made to itinerary.scss is at line 106: `transform: scale(1); // start a new z-index context here`. The rest of it is just formatting changes.
Screenshot:
=> Fix overlapping itinerary icons

app/component/OriginSelector.js
React doesn't patch up all elements on page anymore and therefore origin selector icons wasn't updated in browser. See https://github.com/facebook/react/issues/10591
=> Don't render origin selectors on server side

app/client.js, app/component/AppBarSmall.js, app/component/DisruptionInfo.js, app/component/MainMenuContainer.js, test/unit/DisruptionInfo.test.js
The purpose of this pull request is to prevent an iOS PWA installation from completely breaking up upon re-entering the app. This does not fix the underlying problem with the mismatch between client and server side rendering results. Further work for a complete fix is still required.
In addition, some empty `div`s were removed from the markup.
Link to the relevant JIRA ticket: https://digitransit.atlassian.net/browse/DT-2654
Related discussion: https://github.com/facebook/react/issues/10591
=> DT-2654: iOS PWA partial fix

app/component/SummaryPlanContainer.js
Correct logic was skipped this way:
if(true == 'true') { // local var vs URL param value
// do the right thing
}
Also, clear the spinner correctly.
=> Search Earlier routes with 'Arrive By' option now works correctly

.npmrc, package.json
Fixed package.json to use exact versions.
Added save-exact setting to prevent similar mistakes in the future (https://docs.npmjs.com/misc/config#save-exact). yarn supports that setting too.
=> Exact versions by default 

app/store/localStorage.js, app/util/modeUtils.js, app/util/planParamUtil.js, test/unit/localStorage.test.js, test/unit/modeUtils.test.js, test/unit/planParamUtil.test.js
Changed the way customized settings are handled. Now an empty modes list from localStorage will be overridden by default modes.
=> Do not return an empty modes list

app/component/map/map.scss, app/component/street-mode-selector-popup.scss, sass/base/_elements.scss, sass/base/_zindex.scss
Previously the popup was drawn partially out of the screen area. This also prevents the fullscreen toggle button from being drawn over the menu.
Screenshots:
Link to the JIRA task: https://digitransit.atlassian.net/browse/DCW-43
=> DCW-43: Fixed the street mode popup overflow issue in the mobile view

app/component/DTEndpointAutosuggest.js, test/unit/DTEndpointAutosuggest.test.js, test/unit/helpers/mock-router.js
The purpose of this pull request is to enable the use of current position in via points. Previously this would crash the UI. Now the current location gets properly mapped through geocoding into a valid address.
Relevant JIRA task: https://digitransit.atlassian.net/browse/DT-2648
Screenshot:
=> DT-2648: added handling for current location in via points

app/component/map/map.scss, app/component/route.scss, app/component/stop.scss, app/component/timetable.scss, sass/base/_base.scss
The purpose of this pull request is to enable Firefox to print all timetable pages. The printing problem was due to display:flex being set to the container elements. This should not affect other browsers' printing capabilities.
This was previously part of the branch DT-2284, but that may be discarded altogether.
=> Fix firefox timetable printing

app/component/DTSearchAutosuggest.js, app/util/searchUtils.js, test/flow/tests/itinerary-search/citybike.js, test/unit/searchUtils.test.js
The purpose of this pull request is to reorder the combined results returned from geocoding and graphql apis.
Rules:
- if search is done with numeric input, lines with numeric shortnames will be shown first
- a direct address layer match will be shown first (match done by comparing search string with the address's label and name, ignoring diacritics and case)
- station layer has been given preference over addresses, venues and streets
- stop layer has been downgraded (when compared to default), and they are always shown last
- gtfshsl source has been given preference over openstreetmap and openaddresses sources
- finally, results are ordered by confidence within the same bracket
Each of these cases has a unit test to further clarify the expected functionality.
Related JIRA ticket: …
=> DT-2216: search suggestion list reordering

.travis.yml
Re-enable test coverage. It was disabled in #2360. It's should be fixed now #2392.
=> re-enabled test coverage

app/util/searchUtils.js, package.json, yarn.lock
The purpose of this pull request is to fix the TypeError on IE11 due to missing 'normalize' function. The bug results in no suggestion entries being shown for IE11.
Related Sentry entry: https://sentry.hsl.fi/sentry/digitransit-ui/issues/42910/
=> Regression: fix TypeError on IE11 due to missing 'normalize' function

app/component/SummaryPage.js
This pull request adds default bounding coordinates for the map shown on SummaryPage. The bounds are based on the coordinates of "from", "to" and "default" endpoints, depending on which of these are available. This prevents the SummaryPage view from crashing if there is no geolocation information available in the url.
The next step would be to add retrieving the coordinates for "from" and "to" endpoints in case this information is missing.
One of the related Sentry entries: https://sentry.hsl.fi/sentry/digitransit-ui/issues/1311
=> Add default map bounding coordinates to SummaryPage

app/component/DesktopView.js, app/component/ItinerarySummaryListContainer.js, app/component/ItineraryTimePicker.js, app/component/SummaryNavigation.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/TimeNavigationButtons.js, app/component/navigation.scss, app/component/summary.scss, test/unit/component/SummaryPlanContainer.test.js, test/unit/helpers/mock-relay.js
The purpose of this pull request is to make the whole main content wrapper scrollable if need be. This prevents the scrollable list from being squished to nothing on the desktop view with multiple via points and lots of routes.
In addition:
- the routes list should now always show the ealier/now/later buttons (but disabled, if no routes are available)
- some PropTypes were updated to better reflect the reality
=> DCW-51: make the left content wrapper scrollable

app/util/oldParamParser.js, test/flow/tests/redirect/search-from-hsl.js
Route equests from hsl.fi use + sign (hex %2b) as a separator between address components. This seems to confuse geocoder parsing. Fixed by converting + into blank space.
=> Fix route search redirection from hsl.fi 

app/component/SummaryNavigation.js, app/component/summary.scss
The purpose of this pull request is to prevent IE11 from rendering the routing results on top of the summary navigation component.
Screenshot:
=> Fix routing results overlap in IE11

app/component/AppBarLarge.js, app/component/Modal.js, test/unit/AppBarLarge.test.js, test/unit/component/Modal.test.js
The purpose of this pull request is to re-enable the close icon link pointer events. This should allow the user to close the modal dialog.
=> Enable pointer events for the modal close icon link

app/component/PrintableItineraryHeader.js, package.json, test/unit/PrintableLeg.test.js, test/unit/helpers/init.js, yarn.lock
The purpose of this pull request is to prevent any kinds of errors and warnings from creeping into the unit test suites. If something gets output to console.warn or console.error it automatically results in the unit test not passing.
=> Make console warnings and errors throw in unit tests

test/unit/component/SaveCustomizedSettingsButton.test.js
The change to making console warnings throw results in the master build not succeeding. The purpose of this pull request is to provide a context object that passes PropType validation in order to not log any warnings to the console.
=> Remove console warnings from unit tests

app/component/departures-table.scss
The purpose of this pull request is to make the time columns align once again. Previously this would not work if the next departure time was missing.
Screenshot:
=> Fix nearby departures column alignment

app/component/StyleGuidePage.js
The purpose of this pull request is to disable showing fullscreen components in the component listing. Previously showing these components would effectively break the purpose of that list.
=> Do not include fullscreen components in the styleguide component list

app/store/OldSearchesStore.js, app/util/suggestionUtils.js, test/unit/OldSearchesStore.test.js, test/unit/util/suggestionUtils.test.js
The purpose of this pull request is to improve the label-based matching of routes when querying old searches. Previously the rich version was used instead of the plain-text one resulting in gtfsIds not getting updated for routes.
=> Improve saved route search label comparison

app/component/ItineraryLegs.js, test/unit/component/ItineraryLegs.test.js
The purpose of this pull request is to prevent the UI from crashing if an itinerary contains no legs. Instead, an empty container will be rendered. This may happen when the legs are really short (a few seconds in duration). However, recent changes in OTP should usually prevent this from happening in the first place.
Screenshot:
=> DT-2819: Added a check and test for an empty itinerary legs array

app/util/timeUtils.js, test/unit/util/timeUtils.test.js
The purpose of this pull request is to fix the unit test logic to not consider dayOfYear as this will fail when the end of the range is at the beginning of the following year.
=> Fix timeUtils unit test

app/component/RoutePageMeta.js, app/component/StopPageMeta.js, app/component/SummaryPageMeta.js, app/util/metaUtils.js
The purpose of this pull request is to fix the server side rendering of page metadata.
=> DT-2601 regression fix: wrap window usage inside isBrowser check

app/util/manifestUtils.js, test/unit/util/manifestUtils.test.js
The purpose of this pull request is to disable adding the used protocol to the configured asset url. The configured url should contain this information already meaning that the resulting url is invalid.
=> Stop appending the protocol to the configured asset url

app/component/RouteAlertsContainer.js, app/component/RouteAlertsRow.js, app/component/StopAlertsContainer.js, app/component/StopPageTabContainer.js, app/component/route.scss, app/stopRoutes.js, test/unit/component/StopAlertsContainer.test.js, test/unit/component/StopPageTabContainer.test.js, test/unit/test-data/StopAlertsContainer.data.js
The purpose of this pull request is to enable showing the disruptions tab for terminals.
Screenshot:
=> Disruptions tab for terminals

app/component/Timetable.js, app/component/TimetableContainer.js, app/component/TimetableRow.js, app/component/timetable.scss, app/component/util.scss, app/constants.js, build/schema.json, test/unit/TimetableRow.test.js, test/unit/component/Timetable.test.js, test/unit/component/TimetableRow.test.js
The purpose of this pull request is to show canceled departures in the timetable view for a selected date. Previously these would just be hidden altogether.
This pull request includes a required update to the graphql schema file.
Screenshot:
=> Timetable shows canceled departures

app/component/StopCardContainer.js
The purpose of this pull request is to enable showing canceled departures in the stop popup on the map. This is part of ticket DT-2833 (https://digitransit.atlassian.net/browse/DT-2833).
Screenshot:
=> Stop popup shows canceled departures on the map

app/component/RouteScheduleContainer.js, app/component/RouteScheduleTripRow.js, app/component/RoutesAndPlatformsForStops.js, app/component/StopAlertsContainer.js, app/component/StopPageContentContainer.js, app/component/stop.scss, app/translations.js, test/unit/component/RouteScheduleContainer.test.js, test/unit/component/RouteScheduleTripRow.test.js, test/unit/component/RoutesAndPlatformsForStops.test.js, test/unit/component/StopAlertsContainer.test.js, test/unit/component/StopPageContentContainer.test.js
The purpose of this pull request is to add a "no departures" indicator for stops. This indicator is shown on the "right now" and "routes, platforms" tabs.
In addition, the route timetable view will now also highlight canceled departures.
Screenshots:
=> DT-2833: add a "no departures" indicator for stops

app/configurations/config.hsl.js, app/store/MessageStore.js, test/unit/store/MessageStore.test.js
The purpose of this pull request is to make the configured HSL static messages show after other messages in the carousel. Added filtering for empty static messages (these will cause a lot of error logging for no good reason). Added unit tests.
=> DT-2886: changed the priority of configured static messages

app/util/oldParamParser.js, test/unit/oldParamParser.test.js
The purpose of this pull request is to fix a bug in how the geocoding result for an incoming query was handled. A result containing a forward slash would be included in the url as-is thus breaking the UI. This functionality is used by hsl.fi itinerary search box.
Example: the url http://www.reittiopas.fi/?from_in=helsinki&to_in=saapuvat+lennot&when=now&timetype=departure will resolve to https://reittiopas.hsl.fi/reitti/Helsinki::60.166641,24.943537/Saapuvat%20/%20Arrivals%202A,%20Vantaa::60.318573,24.968032/
=> Fix: geocoding result containing a forward slash was not encoded

app/configurations/config.jyvaskyla.js
The purpose of this pull request is to change the feedback link address for Jyväskylä.
JIRA link: https://digitransit.atlassian.net/browse/DT-2884
=> DT-2884: changed Jyväskylä's feedback link address

app/configurations/config.kuopio.js
The purpose of this pull request is to update the app bar link address for Kuopio. The previous link points to a non-existent url.
JIRA link: https://digitransit.atlassian.net/browse/DT-2885
=> DT-2885: changed Kuopio's app bar link address

webpack.config.babel.js
Google font "directory" shouldn't be cached because its contents change over time and it makes caching the actual font content difficult because users can have different versions of the font directory.
=> Don't cache google font root

app/util/mapIconUtils.js, test/unit/util/mapIconUtils.test.js
The purpose of this pull request is to fix the alert badge size shown on hi-dpi screens.
Screenshot (before):
Screenshot (after):
=> Fix: added support for tile scaleratio on hi-dpi screens

app/component/map/tile-layer/TileLayerContainer.js, test/unit/component/map/tile-layer/TileLayerContainer.test.js
The purpose of this pull request is to fix a bug that prevented a popup from showing on the map when clicking at the same location again after showing the popup once. This was related to reordering the class members and the handler becoming undefined.
=> Regression: fixed a bug related to the map popups not reopening when clicked.

app/component/CustomizeSearchNew.js, app/component/SaveCustomizedSettingsButton.js, app/component/SummaryNavigation.js, app/component/customize-search.scss, app/configurations/config.default.js, app/store/localStorage.js, app/util/planParamUtil.js, app/util/queryUtils.js, build/schema.json, test/unit/localStorage.test.js, test/unit/util/planParamUtil.test.js, test/unit/util/queryUtils.test.js
- Fix removal of preferred and unpreferred routes from settings after they have been saved to localstorage
- Add useUnpreferredRoutesPenalty GraphQL parameter for giving higher penalty to unpreferred routes than OTP's default value as currently using unpreferred routes did not seem very effective
- Check that the implementation matches the design, when such …
=> Unpreferred routes penalty

app/component/map/GeoJSON.js, app/component/map/PointFeatureMarker.js, app/component/map/tile-layer/CityBikes.js, app/util/mapIconUtils.js, test/unit/component/map/GeoJSON.test.js, test/unit/component/map/PointFeatureMarker.test.js
The purpose of this pull request is to enable scaling of custom icons included in geojson. The scaling functionality mimics that of city bike stations, with the two icon sets being fairly equal in size at a given zoom level.
This can be tested using Turku's configuration.
Screenshots:
=> Support for auto-scaling custom geojson icons

app/component/MessageBar.js, app/component/navigation.scss
The purpose of this pull request is to fix the layout under (mobile) Firefox. The message bar would overflow the viewport causing unnecessary horizontal scrolling. This problem manifested itself when the zones message was shown in Finnish.
Relevant JIRA ticket: https://digitransit.atlassian.net/browse/DT-2966
Screenshot:
=> DT-2966: Message bar layout fix for Firefox

app/component/ItinerarySummaryListContainer.js, app/component/SummaryRow.js, app/util/alertUtils.js, test/unit/component/DepartureRowContainer.test.js, test/unit/component/SummaryRow.test.js, test/unit/util/alertUtils.test.js
The purpose of this pull request is to include route and stop service alerts when showing the disruption indicator in the itinerary summary view. Previously only service alerts related to trips were taken into consideration.
In addition, the service alert validity period handling logic was revised - now all timestamps should be in seconds.
Related JIRA ticket: https://digitransit.atlassian.net/browse/DT-2975
Screenshots:
=> DT-2975: Service alert handling for itinerary summaries

app/component/map/map.scss
The purpose of this pull request is to add a small halo effect to from/to/via etc. icons that are shown on the map. This makes them easier to see visually and it was part of the initial UI design.
Relevant JIRA ticket: https://digitransit.atlassian.net/browse/DT-2959
Before:
After:
=> Added a small halo effect for the icons on map

app/server.js
DT-2872 (PR #2673) (commit a7d88b98cf120b5279d2a2aec406d59391187f27) replaced Piwik with Google Tag Manager.
One regression to the piwik embed is, that if piwik was not configured it wouldn't be included in the page. Now, Google Tag Manager Code is always included, even when the `GTMid` is overridden in a specific configuration file with `''` or `null`.
This PR reintroduces the previous functionality for GTM: only if `GTMid` is set, the tag manager code is included.
=> write Google Tag Manager script tag only if GTMid is set in the config

app/component/TripStopListContainer.js, test/unit/component/TripStopListContainer.test.js
The purpose of this pull request is to fix a regression in the trip route view. The selected vehicle was not properly highlighted due to an error in handling the component's properties.
Screenshot:
=> Regression: fix for the selected vehicle not being properly highlighted

app/component/map/tile-layer/CityBikes.js, app/util/mapIconUtils.js
The purpose of this pull request is to change the way it is shown that there are no bikes available at a citybike station.
Relevant JIRA ticket: https://digitransit.atlassian.net/browse/DT-2992
Previous:
Next:
=> DT-2992: Indicate no bikes available with a zero value

app/component/ItineraryTimePicker.js, test/unit/component/ItineraryTimePicker.test.js
The purpose of this pull request is to fix a bug in the ItineraryTimePicker component that prevented users from easily changing the hour and minute values of the requested itinerary's start (or end) time.
The reason for this regression remained somewhat obscure: presumably the componentWillReceiveProps lifecycle method was not previously called but this has been changed unbeknownst to us.
=> DT-3027: fixed not being able to change the hour and minute values

app/component/map/tile-layer/SelectCityBikeRow.js, app/util/citybikes.js, test/unit/component/map/tile-layer/MarkerSelectPopup.test.js, test/unit/component/map/tile-layer/SelectCityBikeRow.test.js, test/unit/util/citybikes.test.js
The purpose of this pull request is to show the correct icon for a citybike station when there are multiple selection options listed in the popup. This can be reviewed using scooter network data currently available from the development api.
Screenshot:
=> DT-3037: show correct citybike network icon on the map layer multi-selection popup

app/component/AlertList.js, app/component/RouteAlertsRow.js, app/component/route.scss, app/util/alertQueries.js, app/util/alertUtils.js, build/schema.json, test/unit/component/RouteAlertsRow.test.js, test/unit/util/alertUtils.test.js
The purpose of this pull request is to show a link to an external resource for service alerts if the url is available. This can be previewed using the style guide page for the component RouteAlertsRow.
Screenshot:
=> DT-3033: display a url link for service alerts

app/component/AlertList.js, app/component/MessageBar.js, app/component/RouteStop.js, app/component/StopCardHeader.js, app/component/StopCardHeaderContainer.js, app/component/TripRouteStop.js, app/component/TripStopListContainer.js, app/component/map/tile-layer/Stops.js, app/util/alertUtils.js, test/unit/component/AlertList.test.js, test/unit/component/MessageBar.test.js, test/unit/component/RouteStop.test.js, test/unit/component/StopCardHeader.test.js, test/unit/component/TripRouteStop.test.js, test/unit/util/alertUtils.test.js
The purpose of this pull request is to prevent any service alerts from showing if they are currently not active. In addition, the same filtering logic was included to the top banner as it was previously missing.
=> DT-3045: do not display future service alerts

app/component/AlertList.js, app/component/RoutePage.js, app/component/RoutePatternSelect.js, test/unit/component/AlertList.test.js, test/unit/component/RoutePage.test.js, test/unit/component/RoutePatternSelect.test.js
The purpose of this pull request is to enable showing service alerts that are otherwise duplicates but have different severity levels. This case may happen if there is an informational service alert before an actual service alert (e.g. a notification of a planned outage of some sort).
This pull request also fixes a problem with the route pattern selection not showing up in Safari for some routes. In addition, a problem with invalid route pattern ids crashing the UI was fixed.
Screenshot:
=> Fixes: severity level duplicates, pattern selection

app/util/mapIconUtils.js, test/unit/util/mapIconUtils.test.js
The purpose of this pull request is to increase the size of platform numbers shown in the stop markers on the map. This size works best with platform codes consisting of one and two letters. Provided that the font and letters are narrow, three letters may work as well.
Single letter:
Two letters:
Longer text:
=> DT-3038: Increased the size of platform numbers

app/component/TransitLeg.js, app/component/WalkLeg.js, test/unit/WalkLeg.test.js, test/unit/component/TransitLeg.test.js
The purpose of this pull request is to show a service alert icon at the "from" stops in the itinerary overview. This will be shown if there is an active service alert at the stop specified, it is independent of the route that passes by that stop.
Screenshot (TransitLeg):
Screenshot (WalkLeg):
=> DT-3057: add service alert icon to "from" stops in the itinerary overview

app/component/RoutePatternSelect.js, test/unit/component/RoutePatternSelect.test.js
The purpose of this pull request is to fix a regression introduced in a previous pull request related to handling routes with only two patterns. The problematic situation happens when there are no trips for any of the patterns that are driven today.
Example route: https://reittiopas.hsl.fi/linjat/HSL:6911X/pysakit/HSL:6911X:0:01
=> Fix: regression when opening a route without a trip for today

app/component/itinerary.scss
- Agency_fare_url is now usable with long route names
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3082
=> DT-3082: With a long route name, agency_fare_url link is not usable

app/component/RoutePage.js, app/component/StopPageTabContainer.js, app/component/route.scss, app/component/stop.scss
- When there's an active disruption, the icon in the Route and Stop views will be shown as a red disruption icon
- When there's an active service alert, the icon in the Route and Stop views will be shown as a blue info icon
- When there are no active alerts at all, the icon will be a grey info icon
- JIRA Link: https://digitransit.atlassian.net/browse/DT-2995 …
=> DT-2995: Show alert or notification icon for disruptions tab when not empty (stop and route views)

app/component/AppBarContainer.js, app/component/RouteNumber.js
- Route and stop pages display now correct header after refresh in mobile.
- [DT-3001](https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3001)
=> Dt 3001: Stop and Route pages display wrong header in mobile

app/component/RoutePatternSelect.js, test/unit/component/RoutePatternSelect.test.js
The purpose of this pull request is to enable rendering correct html content when there is just a single pattern available for selection.
Example route: https://jyvaskyla.digitransit.fi/linjat/LINKKI:9422/pysakit/LINKKI:9422:1:01
Related ticket: https://digitransit.atlassian.net/browse/DT-3086
=> DT-3086: use correct html format for a single pattern

app/component/map/MapWithTracking.js, test/unit/component/map/MapWithTracking.test.js
- Map is centered around the destination point when origin point is not selected and when destination point is selected from route or stop page.
- [DT-3081](https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3081)
- Check that the implementation matches the design, when such one is defined in a …
=> DT-3081: map is now centered correctly when selecting destination point

app/component/map/MapWithTracking.js
- JIRA Link: https://digitransit.atlassian.net/browse/DT-3085
- Enabled location icon even when the user's origin point is the same as their location. 
=> DT-3085: Display origin icon on top of the user location icon when selecting own location as origin

app/component/DTAutosuggestPanel.js, app/component/OriginDestinationBar.js, app/component/SummaryNavigation.js, app/component/map/MarkerPopupBottom.js
- Input fields' routing requests work now similarly as choosing origin or destination point from the map.
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-2986
=> DT-2986: routing requests use now time query when using input fields

server/reittiopasParameterMiddleware.js, test/unit/reittiopasParameterMiddleware.test.js
- Added support providing a language parameter in searches, when url parameters are formed in 3rd party site (such as hsl.fi or My Helsinki)
- Jira ticket: https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3096
=> Dt 3096: Add support providing a language parameter in searches

app/component/map/ItineraryLine.js, app/configurations/config.matka.js
- Added matkahuolto feed ids to matka config
- Fixed issue where matkahuolto data crashed ui due to missing stop code in graphiql
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&selectedIssue=DT-3060
=> DT-3060: Add Matkahuolto GTFS data to dev.digitransit.fi

app/component/RoutePage.js, app/component/RoutePatternSelect.js, test/unit/component/RoutePatternSelect.test.js
- Removed the part of code that hid the pattern selector on route page when there were no trips for the current date
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3111 
-
=> DT-3111: Pattern selector missing from stop page stops and disruptions tabs

app/component/RouteAlertsRow.js, test/unit/component/RouteAlertsRow.test.js
- Adds a http:// prefix to links that are lacking it to allow external linking
=> DT-3137: Clicking an external link on the disruption info doesn't redirect 

app/component/AlertList.js, app/component/DisruptionListContainer.js, app/util/alertUtils.js, test/unit/test-data/dt3138.js, test/unit/util/alertUtils.test.js
- Fixed the amount of disruptions/service alerts to correspond to the amount of unique headers
=> DT-3138: The amount of disruptions and service alerts in the tab doesn't match the list

.eslintrc.js, app/component/DisruptionInfo.js, package.json, test/unit/DisruptionInfo.test.js
- Fixes the problem with disappearing disruption modal on refresh
=> DT-3171: Opening Disruptions modal and refreshing page makes the modal disappear

app/configurations/config.hsl.js
area polygons seem to have identical first and last point. This is not necessary.
=> Do not close polygons in data

app/component/SummaryPage.js, app/configurations/config.tampere.js, app/util/timeUtils.js, test/unit/util/timeUtils.test.js
- Tampere wants to show trip itineraries for the next 60 days. Other cities will use 30 days by default.
=> DT-3175: Show trip itineraries for the next XX days

app/util/mqttClient.js, test/unit/util/mqttClient.test.js
- Only display one location per hsl metro train instead of displaying one for each carriage
=> Only process vehicle position updates of hsl metro with seq value 1

app/configurations/config.default.js
- Increase default OTP timeout to better match what timeouts there are for routing
=> Increase default timeout for OTP to better match OTP processing times

app/component/route.scss
- Fix issue where route pattern selector showed two arrow indicators
=> DT-3287: Route pattern select shows two arrow indicators

package.json, yarn.lock
- Downgrading favicons-webpack-plugin because of a hidden deprecation that removed iconstats files. This dependency can be upgraded after https://github.com/jantimon/favicons-webpack-plugin/pull/166 is merged in some form but it will require some code changes in our end.
- Check that the implementation matches the design, when such one is defined in a Jira …
=> fix: temporarily downgrade favicons-webpack-plugin

app/configurations/config.matka.js
- Services at beta.vayla.fi are moving to tyokalu.navici.com. It means that Matka.fi needs new config for yleisviestipalvelu.
=> chore: New location for Matka.fi yleisviestipalvelu

app/util/mqttClient.js, test/unit/util/mqttClient.test.js
- Adds fallback mode when HFP message has non-standard mode
=> fix: use bus as fallback mode if the message mode is non-standard

app/component/StopPageTabContainer.js, test/unit/component/StopPageTabContainer.test.js
- Fixing tab text by using routes' mode instead of stop's vehicleMode. 
=> DT-3387: vehicleMode stop field from OTP should not be used in UI

app/routes.js
- Ensures that 404 is returned for missing files from /js/, /css/ and /assets/ subdirectories instead of just for the missing files from those root paths.
- This problem did not affect the new version of routes but could have potentially caused issues in the future if queries were caught by some other path than the general 404 path. …
=> fix: return 404 for missing js, css and asset paths that contain /

server/server.js
- There was a potential risk that when BASE_CONFIG env was used that OTP would be unresponsive at launch and when tickets are refetched after launch, they would not be patched into CONFIGs that were already cached
=> fix: exit server if availableTickets can't be fetched with BASE_CONFIG

app/component/PatternStopsContainer.js, app/component/RouteListHeader.js, app/component/RouteStop.js, app/component/RouteStopListContainer.js, app/configurations/config.default.js
Based on MFDZ issue [#167](https://github.com/mfdz/digitransit-ui/issues/167): in our region there are small differences between routes which are handled as totally different ones, and so next departure is set to the next day (which is not true).
- added new config variable `displayNextDeparture` to config.default.js with the value `true`
- modified corresponding components of the Route panel in order to make show / display the "Next" column
- If true:
- If false:
We were a bit unsure about the config key - what do you think, should it be a subkey of something or would you prefer another name?
- …
=> Add opportunity to disable "next" column in Route panel

app/server.js, server/server.js
When relay 1.6.0 encounters a GraphQL parsing error it doesn't seem to return a failed promise or at least a synchronous exception but it schedules an exception to be thrown later: https://github.com/facebook/relay/blob/v1.6.0/packages/react-relay/classic/util/throwFailedPromise.js
For example, you can provoke a parsing error by setting the triangle factors of the bike routing in the URL to add up to more than 1.0.
When the page is rendered with `react-isomorphic-relay-router` then this leads to a server crash as the exception is thrown completely outside the ordinary request/response cycle and there is no handler for it.
- This pull request does …
=> fix: handle uncaught relay parsing error globally

app/component/DepartureRowContainer.js, app/component/NearbyDeparturesList.js
Follow on #3230 we added the option to switch off the "next" departure column in the Near you panel at the front page. It uses the same variable as the first PR, `displayNextDeparture` from the config file.
If true:
If false:
=> Feat: toggle next departure column in Near you panel

app/component/map/popups/TicketSalesPopup.js, app/component/map/tile-layer/MarkerSelectPopup.js, app/component/map/tile-layer/SelectTicketSalesRow.js, app/component/map/tile-layer/TicketSales.js, app/component/map/tile-layer/TileLayerContainer.js, app/configurations/config.hsl.js, app/util/mapLayerUtils.js, test/unit/util/mapLayerUtils.test.js
Update ticket sales props. A new version of the HSL ticket sales dataset has been released in which the data schema for ticket-sales vector tiles changes. This commit replaces the old prop values with new values of the updated dataset.
Corresponding changes to the hsl-map-server: https://github.com/HSLdevcom/hsl-map-server/pull/70
New dataset: https://public-transport-hslhrt.opendata.arcgis.com/datasets/hsln-myyntipisteet/data
Following schema values have been replaced with new ones:
FID -> NID_fi
TYYPPI -> Tyyppi
NAME -> Name_fi
OSOITE -> Address_fi
'HSL Automaatti MNL' -> Monilippuautomaatti
'HSL Automaatti KL' -> Kertalippuautomaatti
- This pull …
=> refactor: update ticket sales props

app/server.js
This fixes occasional errors when refreshing page on some itinerary summary page. An error (RRNLBatchMiddlewareError: Server does not return response for request at index 0.
R) was rendered instead of continuing the render process. 
- Catches error from fetching relay's cache so UI does not render the relay error which can block SSR from working properly.
- …
=> fix: catch error from fetching relay cache

app/component/SummaryPage.js, app/routes.js
- Renders placeholder summary page while waiting for itineraries instead of a full page loader (client side rendering)
- Removed SSR of summary page, instead returns a loader gif from server
- Because routing parameters don't exist to the extent in the URL anymore, SSR would in many cases do an itinerary search with different parameters than client
- Removed unused ITINERARYFILTERING_DEFAULT export from SummaryPage
- Removed mostly hidden map render on mobile in summary page with no itineraries selected
- Map was occasionally briefly shown during re-renders …
=> DT-3431 and DT-3482 part 1, Optimize Itinerary page rendering for geolocated routes

app/component/IndexPage.js, app/component/front-page.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/helpers/styles.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-control-panel/helpers/styles.js, digitransit-component/packages/digitransit-component-control-panel/index.js, digitransit-component/packages/digitransit-component-control-panel/package.json
- Text sized and paddings to be same as in HSL.fi's mobile page
=> DT-3618: mobile's front page to match with HSL.fi's front page

app/component/RouteScheduleContainer.js, app/routeRoutes.js
- Fixes issue where switching back to timetables of an already viewed pattern in route page timetable view showed always an empty list
- The state handling and react lifecycle usage is still a bit of a mess but perhaps slightly less of a mess now
- Merge the pull …
=> fix: pattern switching on route timetable view

app/component/RouteMapContainer.js
- Map now only focuses on vehicle when it is first selected and will not follow it.
- When vehicle popup is open, the map will still partially follow the popup
=> DT-3430: Map should not constantly center on a vehicle

app/component/OriginDestinationBar.js, app/component/WithSearchContext.js, app/component/map/MarkerPopupBottom.js, app/util/path.js
- When 'depart now' is selected in timepicker, url param 'time' is now set to current time only once both origin and departure are selected and the actual route search is made 
- This allows the time in to keep updating in UI if one of origin or departure is selected …
=> DT-3701: Selecting origin or destination in front page disable realtime update of departure time

app/component/StreetModeSelector.scss
- Fix street mode container height on Safari
- Tested on Browserstack, Safari 13.1
=> DT-3704: Street mode selector container looks off in safari

digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js
- Previously searched terminals without gtfs information don't come up in stop and route search
=> DT-3724: Terminal searched as a favourite location does not work in stop search

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/translations.js
- Showing info when only bike or walk itinerary is available.
=> DT-3676: info instead of error when only bike or walk

digitransit-component/packages/digitransit-component-autosuggest-panel/helpers/styles.scss, digitransit-component/packages/digitransit-component-autosuggest-panel/index.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/index.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/helpers/styles.scss, digitransit-component/packages/digitransit-component-favourite-editing-modal/index.js, digitransit-component/packages/digitransit-component-favourite-editing-modal/package.json, package.json, yarn.lock
- Add react-sortablejs library for sorting favourites and via points.
- Fix bug where mobile search wasn't closed after selecting location.
=> DT-3741: Reordering favourites or via points doesn't work on iphone

app/component/map/MapWithTracking.js
- Fix back button from near you page resulting in a broken map
- This happened because user was already geolocated when coming from near you page and front page map did not handle that correctly
=> DT-3745: Front page link from Stops near you view partly broken

app/component/AppBarHsl.js
- Change top bar hsl link url to use correct language
=> DT-3710: Site header links should navigate to uusi.hsl.fi with correct language

digitransit-search-util/packages/digitransit-search-util-query-utils/index.js
100 route suggestions is enough for all route searches in HSL area. 100 is a sensible upper limit for searching from a scrolled list. All matching routes are shown.
=> chore: accept much more matching routes

app/component/AdminForm.js, app/configurations/config.default.js, digitransit-search-util/packages/digitransit-search-util-query-utils/schema.json
- Change default optimization for bicycle routing from QUICK to GREENWAYS for OTP queries.
- Add more verbose description for GREENWAYS optimization in search-utils
Previous default preset QUICK resulted in some quick and legal but not preferable (unsafe) bicycle routes. By using optimization preset GREENWAYS, cycleways are preferred vs. cycling on a street. The GREENWAYS optimization is currently used in "Suosi kevyen liikeenteern reittejä" search option in `digitransit-ui:master`
GREENWAYS optimization was missing description. GREENWAYS prefers cycleways even more by treating them "safer"(=preferrable) than they are based only on OSM network attributes  
- Changes are documented or they are self …
=> DT-3787: Prefer cycleways by default in bicycle routing

app/component/map/popups/TicketSalesPopup.js, app/component/map/tile-layer/MarkerSelectPopup.js, app/component/map/tile-layer/SelectTicketSalesRow.js, app/component/map/tile-layer/TileLayerContainer.js
Update ticket sales props. A new version of the HSL ticket sales dataset has been released in which the data schema for ticket-sales vector tiles changes. The new data is served by hsl-map-server via Digitransit Map API. This commit replaces the old prop values with new values of the updated dataset.
New ticket sales point dataset which is served as vector tiles by hsl-map-server: https://opendata.arcgis.com/datasets/79fe2db71b254edda68c47d2629a962e_0.geojson
The new dataset is currently served only by hsl-map-server:dev. 
Production release needs a timed production release of hsl-map-server.
- …
=> DT-3805: update ticket sales points props

app/component/ItineraryPageMap.js, app/component/MobileView.js, app/component/RouteMapContainer.js, app/component/TopLevel.js, app/component/map/IndexPageMap.js, app/component/map/Map.js, app/component/map/MapBottomsheetContext.js, app/component/map/MapContainer.js, app/component/map/map.scss, app/component/route.scss, app/component/stops-near-you.scss, sass/base/_zindex.scss
- Make bottom sheet that is shown on top of map in mobile views draggable and consistent on all pages.
- This is a first version, some improvements need to be made on future tickets
- Map should now focus correctly on page load and not be obscured by bottom sheet.
- There is a bug where bottom sheet is not correctly placed to middle of page on near you page, maybe this has to do with server side rendering? Resolve this in another ticket
- Test the functionality …
=> DT-3715: Design how mobile bottom sheet type areas should function

app/component/map/map.scss
- Fix bottom sheet not being set to middle of screen on near you page and summary page. Cause for this is that the content on those pages sometimes takes a while to load and sheet position is set asyn before that. Fix it by padding the sheet with some blank content
- …
=> fix: bottom sheet initial position on near you and summary page

digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileDatepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileTimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/mobileDetection.js
- For itinerary search, use native datetime picker for Android instead of separate date picker and time picker.
- Remove "today" label for departure/arrival time when datetimepicker is closed and today is selected. 
=> DT-3874 and DT-3830

app/component/navigation.scss, sass/themes/default/_theme.scss, sass/themes/hsl/_theme.scss, sass/themes/joensuu/_theme.scss, sass/themes/jyvaskyla/_theme.scss, sass/themes/kotka/_theme.scss, sass/themes/kouvola/_theme.scss, sass/themes/kuopio/_theme.scss, sass/themes/lahti/_theme.scss, sass/themes/lappeenranta/_theme.scss, sass/themes/mikkeli/_theme.scss, sass/themes/oulu/_theme.scss, sass/themes/rovaniemi/_theme.scss, sass/themes/salo/_theme.scss, sass/themes/tampere/_theme.scss, sass/themes/turku/_theme.scss, sass/themes/walttiOpas/_theme.scss
- Use different primary color for waltti-opas and use the old primary color as secondary color
- Make top bar color configurable and use secondary for it in waltti opas config
=> feat: use different primary color for walttiOpas and conf top bar color

app/component/IconWithIcon.js, app/component/SummaryRow.js, app/component/summary-row.scss
- Itinerary bars render correctly in firefox
- Disruption icon placement in mobile
=> DT-3928: Itinerary summary bars render incorrectly in firefox

app/component/MobileView.js
- Bottom sheet position no longer resets when map param changes
- This might be a temporary change only. Root cause for this bug is that near you page handles map rendering a little differently than other pages. This could be refactored later.
=> DT-3933: Near you page resets bottom sheet position

app/configurations/config.default.js, build/schema.json, digitransit-search-util/packages/digitransit-search-util-query-utils/schema.json
- Use same default walk speed as in old reittopas (1.38 --> 1.22 m/s) 
=> DT-3952: Use same default walk speed as in old reittopas

webpack.config.babel.js
- Prevents service worker from caching txt files (license information)
- We probably don't even need to include those files in the build in the first place
=> fix: exclude txt files from service worker

app/component/WithSearchContext.js
- Fixes so that location selection modal is not reshown when user navigates back from stops near you view
=> DT-3946 Navigating back from stops near you opens location modal again and other navigating issues

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Fix "your own places" button sometimes not showing on initial load in search field
- This mainly affects the situation when page is fully reloaded (or coming from hsl.fi)
- It is difficult to test this locally, so probably need to test again after merging to next 
- …
=> DT-3939: Select from your places doesn't show up in itinerary page at first when coming from hsl.fi

app/component/SummaryPage.js
- no more filtering "bike to vehicle"-itineraries when longest bike leg < 500
=> DT-4044: no more filtering bike to vehicle itineraries when longest bike leg < 500

app/component/map/Map.js, app/component/map/map.scss, app/configurations/config.default.js, app/configurations/config.hsl.js
As discussed in #3670 I've added the ability to set a custom map attribution.
Here is how it looks like:
I've used lodash's `get` method to get the config variable as I didn't want to rely on the field `config.map` being present, but maybe that's not in line with how the rest of the config vars are being read. Let me know if you would like me to change it.
Closes #3670 .
- Test the functionality by running the UI locally with all popular browsers available in …
=> Add ability to set attribution text in configuration

app/component/StreetModeSelector.js, app/component/SummaryPage.js, app/component/SummaryPlanContainer.js, app/component/summary.scss
- Show vehicles for earlier and later itineraries
- Show vehicles when examining some itinerary that was not highlighted in the summary view
- Also don't show vehicles that are not related to the itinerary
- Always show earlier/later button that is on the top of the list smaller than the earlier/later button that is on the bottom of the list
- If user searches for more itineraries that will be put on the top of the list, reset highlighted itinerary index
- Test …
=> DT-4017 Vehicles for earlier/later departures are never shown on map and DT-4048 Reset itinerary index after earlier/later searches

app/component/SummaryPage.js, app/component/map/IndexPageMap.js, app/component/map/Map.js, app/component/map/MapWithTracking.js, app/component/map/SelectFromMapPageMap.js, app/component/map/StopsNearYouMap.js, app/component/map/popups/LocationPopup.js, app/component/map/tile-layer/TileLayerContainer.js, app/component/map/tile-layer/VectorTileLayerContainer.js, app/translations.js, digitransit-component/packages/digitransit-component-autosuggest/src/helpers/MobileSearch.js
- 3 states for location popup: 'none', 'reversegeocoding', 'all'
- Show itinerary search related popup buttons only in pages where they make sense
- Recent PR for German translations did not pass eslint, fixed
=> fix: consistent location popups, reorder german translations

digitransit-component/packages/digitransit-component-datetimepicker/package.json, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js
- Insert colon automatically in time picker if user skips typing it
=> DT-4030: Enter departure/arrival time without colon

app/component/map/non-tile-layer/StopMarker.js
- Only send SelectMapPoint analytics event on StopMarker click instead of doing it on every render
=> DT-4065 Opening summary page can cause multiple selectMapPoint analytics events

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Fixed issue described in title
=> DT-4074: If user uses or has used own location as location in autosuggest, mobile search keeps reseting list position

app/component/StopsNearYouPage.js
- Own places show up on the first click 
=> DT-4088: Select from own locations does not show up in stops near you entry autosuggest

app/component/ItinerarySummaryListContainer.js, app/component/SummaryPage.js
- bike+vehicle correct heading if only bikeAndPublic itineraries and no bikeAndPark
- reduced unnecessary renders on changing view to bike+vehicle by removing unnecessary state from summaryPage: 
streetmode
- reverted summaryRow key prop (duplicate key lead to "ghost" itineraries on bike+vehicle view)
- renamed variable correctly in ItinerarySummaryListContainer 
- Test the functionality by running the UI locally with all popular browsers available in your …
=> DT-4070: bike+public view bugs and optimizations

app/component/PatternStopsContainer.js, app/component/RouteListHeader.js, app/component/RouteStop.js, app/component/RouteStopListContainer.js, app/configurations/config.default.js, package.json, yarn.lock
It has been done previously in #3230 for the old UI and we'd like to use this feature on the next branch too.
- added new config variable `displayNextDeparture` to config.default.js with the value `true`
- modified corresponding components of the Route panel in order to make show / display the "Next" column
- If true:
- If false:
- Check that the implementation matches the design, when such one is …
=> Add opportunity to disable "next" column in Route panel on Next

app/component/StopCardHeader.js, app/component/map/popups/LocationPopup.js, app/configurations/config.lahti.js, app/configurations/config.oulu.js, app/util/mapIconUtils.js
- Allow custom font size scaling for location popup zone
- Check that the zone belongs to one of the configured feedIds before showing it in location popup
- Configure custom font sizes for lahti zones
- Fixes location popup and stop page font size issues
- Merge the …
=> DT-4111 Scale map popup zone icon font size based on text length

app/component/SummaryPage.js, app/component/SummaryPlanContainer.js
- fix: filter out only walking suggestions from earlier/later itineraries
- Refactor earlier/later itineraries logic to be more clear: data now flows from parent to child and child component does not update parents state, also itineraries are now combined into one only once in summaryPage
- Check that the implementation matches the design, when such one is …
=> DT-4109: filter out only walking suggestions from earlier/later itineraries

app/component/DatetimepickerContainer.js, digitransit-component/packages/digitransit-component-autosuggest/src/index.js, digitransit-component/packages/digitransit-component-datetimepicker/README.md, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/Datetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/DesktopDatetimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileDatepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/helpers/MobileTimepicker.js, digitransit-component/packages/digitransit-component-datetimepicker/src/index.js, digitransit-component/packages/digitransit-component-dialog-modal/README.md, digitransit-component/packages/digitransit-component-favourite-bar/README.md
Since we operate in a different time zone the hardcoded `Europe/Helsinki` is causing the date time picker to display the incorrect time. This PR allows users of the component to set the time zone via props. As requested in #3747, it is completely backwards-compatible and defaults to the Finnish time zone.
I have some reservations about calling `setDefault` over and over (as it is effectively a global variable), but it was the least painful change I could make. It also allows for easier review.
While checking if this works as expected I noticed a weirdness in the current implementation that existed before this pull request.
When using the `hsl` config with a timezone other than `Europe/Helsinki` (I'm on `Europe/Berlin`) and selecting a time, the component correctly interprets "now" as …
=> Allow time zone to be passed to components as props

app/component/ItineraryTab.js, app/component/TransitLeg.js, app/component/itinerary.scss, app/util/alertUtils.js
- feat: disruption info to itinerary view
- Note: testing this might be difficult so I included a testLeg with alert which can be used to replace the leg on line 255 in TransitLeg.js, alternatively one can somehow edit the data that graphQL provides
[testLeg.txt](https://github.com/HSLdevcom/digitransit-ui/files/5603512/testLeg.txt) …
=> DT-4092: disruption info to itinerary view

app/component/IndexPage.js, app/component/OriginDestinationBar.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js
- FilteredResults function was available in StopsNearYou. Added that to AutosuggestPanel as well
- Added stops to mobile front page
- Added filter to remove favouriteStops in mobile.
=> DT-4157: Favorite stops are available in itinerary page mobile search

app/component/SummaryPage.js, app/routes.js, app/util/modeUtils.js, app/util/planParamUtil.js, test/unit/util/planParamUtil.test.js
- Refactor itinerary request with all modes to use default modes from config and to already take these modes into account in planParamUtil
=> DT-4138 Configured transit modes should be taken into account when fetching with all modes

app/config.js
Do not show login menu when login is not possible
=> fix: no login if it is doomed to fail

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- Add mobileLabel property to digitransit-component-autosuggest.
- Add originMobileLabel and destinationMobileLabel properties to digitransit-component-autosuggest-panel.
=> DT-4218: Add property to define mobile search label

app/component/Geolocator.js
Location resolver no longer removes destination POS from url, if origin is also POS.
=> fix: resolve itinerary searches of type /POS/POS/ properly

app/configurations/config.default.js, app/configurations/config.hsl.js, app/configurations/config.waltti.js, app/server.js
- Use next- prefix for map endpoints if MAP_PATH_PREFIX env is not defined
- Allow changing waltti map endpoints with MAP_PATH_PREFIX env
- Change default server side relay timeout limit from 1 second to 3 seconds
=> feat: use next- map endpoint prefix by default

app/component/WithSearchContext.js, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-autosuggest/src/index.js
- 'Nykyinen sijaintisi' was not cleared from search input at activation
- If reverse geocoding failed,  search assigned default address 'Nykyinen sijaintisi' only at first selection. Next time user applied current location during the same session, the address (and search input) was left empty, which appeared quite confusing.
- Some old dead state management code removed
=> Fix some geolocation related bugs

app/component/SummaryPage.js
- Refetch walking and cycling suggestions when query parameters change
<b>There is still an issue where these suggestions fetched from cache show no itineraries error instead of the itineraries. This can be replicated for example by doing an itinerary search and then adding and removing a viapoint and clicking one of these suggestions. That issue should be fixed in some future pull request that probably should do a bit more refactoring as well</b>
- Test the …
=> DT-4287 Walking/cycling suggestions are not updated after via point is added

app/component/SummaryPage.js
- Changed loading logic so that loading in summaryPage doesn't pop up too early.
=> DT-4245: Summary page content should not be rendered when user directly opens an itinerary

app/component/bubble-dialog.scss, app/component/map/map.scss, app/component/navigation.scss
This fixes the display of the layer switcher so that it can be activated without the bubble moving beyond the edge of the visible area. It also moves the bubbles underneath each other.
=> [next] Fix display of layer switcher button

app/component/TransitLeg.js
The original link caused redirect which added doubled path ../hairiot/hairiot/... .Removing / from the link end fixed this, and correct URL was created, but redirect still rendered white page although the path was correct.
The only way to the the link working was to set exactly correct url which does not need redirects.
=> fix: working link to route disruptions

app/util/planParamUtil.js, test/unit/util/planParamUtil.test.js
- Make sure citybike (BICYCLE_RENT) mode is not in bikepark modes as currently they can't be used together and currently the citybike could be used instead of bikepark in results
=> DT-4313 Citybikes should not be used for bike park itineraries

app/component/map/StopsNearYouMap.js, app/component/map/tile-layer/Stops.js, app/util/mapIconUtils.js
- Hide stops with no upcoming traffic from stops near you map
- This causes map to zoom farther away to see nearest stop, especially on ferry page
- Also draw the icon for highlighted nearest stops on smaller zoom levels than before
- At or below zoom level 12 icon is still hidden because map service does not return stops data at that level …
=> DT-4127: The Show more button works strangely on The closest ferry piers near you view

app/component/SummaryPage.js
- Hide street mode selector after loading fails
=> DT-4338: Street mode selector area remains in loading state even after queries fail

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-suggestion-item/package.json, digitransit-component/packages/digitransit-component-suggestion-item/src/index.js
- Favourite bar uses SuggestionItem without layer attribute. This fix will take that into consideration.
=> Hotfix for suggestionitem

app/util/otpStrings.js
In the past, existence of key value locationState.type === 'CurrentLocation' was used
(for some obscure reason) to decide if locationing was already attempted.
So, recent addition of that key to location state at store initialization
broke geolocationing process. Now, the decision is made using the location status key,
which obviously makes sense.
=> fix: read location state from location state

app/util/path.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-component/packages/digitransit-component-favourite-bar/package.json, digitransit-component/packages/digitransit-component-suggestion-item/package.json, digitransit-component/packages/digitransit-component-suggestion-item/src/index.js
- Use labelId when selecting favourite bike rental station, instead of id
- If no localadmin is present in data, don't show anything about it. (Was showing undefined in label)
- Corresponding package updates
=> DT-4487: Favourite bike rental stations are broken in search

app/component/SwipeableTabs.js
- Fix a bug where swiping in stops near you page sometimes fails to change the page. Happens on iOS and Android
- I did not find the root cause, but this fixes the biggest problem.
- This might be a bug in the react-swipe library or it might be caused by some weird rendering bugs in the stops near you page
- The swipe animation still randomly fails sometimes but now the tab will always be changed correctly
- Test the functionality by running the UI locally with …
=> DT-4501: Stops near you swiping is unreliable in iPhone + Safari

app/component/DisruptionBanner.js, app/component/DisruptionBannerAlert.js, app/component/stops-near-you.scss
- Add header to disruption banner alert.
- Header is shown if alert's header text is shorter than 120 characters and alert description text doesn't include header text.
=> DT-4537: Add header to disruption banner alert

app/util/gtfsRtParser.js, app/util/mqttClient.js, sass/themes/tampere/_theme.scss, test/unit/util/gtfsRtParser.test.js
- Use custom color for trams in Tampere config
- Parse mode from gtfsrt mqtt topic
- Override normal feedId in mqtt subscription topics with topicFeedId
- Its purpose is to allow different mqtt topic for Tampere's tram testing while the regular uses normal realtime data
- Can be tested by adding env `REALTIME_PATCH="{\"tampere\": {\"topicFeedId\": \"tampereTram\"}}"`
- Test the functionality by running the UI locally with all popular browsers available in your …
=> DT-4503-master Tampere tram color and realtime

app/util/gtfsRtParser.js, app/util/mqttClient.js, sass/themes/tampere/_theme.scss, test/unit/util/gtfsRtParser.test.js
- Use custom color for trams in Tampere config
- Parse mode from gtfsrt mqtt topic
- Override normal feedId in mqtt subscription topics with topicFeedId
- Its purpose is to allow different mqtt topic for Tampere's tram testing while the regular uses normal realtime data
- Can be tested by adding env `REALTIME_PATCH="{\"tampere\": {\"topicFeedId\": \"tampereTram\"}}"`
- Test the functionality by running the UI locally with all popular browsers available in your …
=> DT-4503 Tampere tram color and realtime

app/configurations/config.default.js
- Set maxNearbyStopAmount to 5 for default configs so 5 stops are fetched initially at stop near you page.
=> DT-4505: Different amounts of stops in stops near you page in different configs

app/component/StopsNearYouPage.js, app/configurations/config.lappeenranta.js, app/translations.js
- General start using citybike information POC for Waltti cities in stops near you page
- Lappeenranta's city bike url languages was mixed up: sv pointed to english site and vice versa.
=> DT-4596: Add Start using citybike link instead of buy link in Waltti configs in stops near you page

app/component/DepartureListContainer.js, app/component/PatternLink.js, app/component/PatternRedirector.js, app/component/RouteAlertsRow.js, app/component/RouteHeader.js, app/component/RoutePageControlPanel.js, app/routeRoutes.js, digitransit-component/packages/digitransit-component-autosuggest-panel/package.json, digitransit-component/packages/digitransit-component-autosuggest/package.json, digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json, digitransit-search-util/packages/digitransit-search-util-helpers/index.js, digitransit-search-util/packages/digitransit-search-util-helpers/package.json, digitransit-search-util/packages/digitransit-search-util-query-utils/package.json, test/unit/component/RouteAlertsRow.test.js
- Refactored route page entry so that instead of using sort=no, giving a pattern in the URL now means that no sort should happen. Leaving out the "pattern", i.e. the `routeId:0:01` means that the best fit pattern will be picked. It's also possible to leave out the tab name.
- Updated route page links to use the new logic
- Check that the implementation …
=> DT-4332 Route page pattern redirects

app/component/SummaryPlanContainer.js, app/component/summary.scss
- Add extra whitespace to later departures button on ios safari (affects other ios browsers as well)
- Tested on iPhone 12 through localtunnel
=> DT-4590: extra whitespace for safari

build/schema.json, digitransit-search-util/packages/digitransit-search-util-query-utils/schema.json
- Remove deprecated fields/parameters/types from graphQL schema because they are not included in the OTP2 API
=> chore: remove deprecated fields from schema
