app/component/navigation/index-navigation.scss
app/component/navigation/summary-navigation.cjsx

Css selectors were on the wrong level

Fix offcanvas togle icon position on summary page

---

app/action/route-search-action.coffee
app/component/itinerary/bottom-navigation.cjsx
app/component/itinerary/end-leg.cjsx
app/component/itinerary/itinerary-summary.cjsx
app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/itinerary.scss
app/component/itinerary/ticket-information.cjsx
app/component/itinerary/transit-leg.cjsx
app/component/itinerary/walk-leg.cjsx
app/page/itinerary.cjsx
package.json
sass/main.scss
sass/theme/_hsl-theme.scss

Out of scope for this item:
- Printing (just add button on page)
- Share route (just add button on page)

Route page

---

app/action/route-search-action.coffee
app/component/itinerary/bottom-navigation.cjsx
app/component/itinerary/end-leg.cjsx
app/component/itinerary/itinerary-summary.cjsx
app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/itinerary.scss
app/component/itinerary/ticket-information.cjsx
app/component/itinerary/transit-leg.cjsx
app/component/itinerary/walk-leg.cjsx
app/component/map/itinerary-line.cjsx
app/component/map/map.cjsx
app/page/itinerary.cjsx
app/page/summary.cjsx
package.json
sass/main.scss
sass/theme/_hsl-theme.scss

Route page - map

---

app/component/map/map.cjsx
app/component/map/stop-marker-container.cjsx
app/page/stop-map.cjsx
app/page/stop.cjsx

Fix minor issues with map page

---

app/action/itinerary-search-action.coffee
app/client.cjsx
app/component/map/map.cjsx
app/component/route/route-header-container.cjsx
app/component/route/route-header.cjsx
app/component/route/route-stop-list-container.cjsx
app/page/stop.cjsx
app/page/summary.cjsx
app/store/itinerary-search-store.coffee

Open page before loadAction finishes and add data after it has been recieved

Increase responsiveness

---

app/component/map/stop-marker-container.cjsx
app/component/map/stop-marker-popup.cjsx

Fix issues with popups having no context available and for conflicting keys on stop labels.

Fix react warnings

---

acceptance-tests/component/map/map-location.feature
app/component/icon/icon.cjsx
app/component/map/dynamic-popup.cjsx
app/component/map/map.cjsx
app/component/map/route-marker-popup.cjsx
app/component/map/stop-marker-popup.cjsx
app/component/search/search-two-fields.cjsx
app/component/stop-cards/departure-list-container.cjsx
app/component/stop-cards/stop-tabs.cjsx
app/page/summary.cjsx
app/util/otp-strings.coffee
server/server.js

I've reviewed the commits not done by me, but the first three could use a quick look.

Minor improvements

---

app/component/search/search-two-fields.cjsx
app/translations.coffee

Pull request
for issue: https://digitransit.atlassian.net/browse/DT-131
title: Search field text changes

improve texts

---

app/component/favourites/favourite-stop-card-list-container.cjsx
app/component/map/map.scss
app/component/map/stop-marker-container.cjsx
app/component/map/stop-marker-layer.cjsx
app/component/map/stop-marker-popup.cjsx
app/component/map/stop-marker.cjsx
app/component/stop-cards/nearest-stop-card-list-container.cjsx
app/component/stop-cards/stop-card-container.cjsx
app/component/stop-cards/stop-card-header.cjsx
app/component/stop-cards/stop-card-list.cjsx
app/component/stop-cards/stop-card.cjsx
app/component/stop-cards/stop-cards.scss
app/queries.js
sass/base/_elements.scss

[DT-104 Map stop bubble shows next departures](https://digitransit.atlassian.net/browse/DT-104)

Show stop card in departures

---

app/app.coffee
app/client.cjsx
app/component/favourites/favourites-panel.cjsx
app/component/front-page/front-page-panel.cjsx
app/component/itinerary/bottom-navigation.cjsx
app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/ticket-information.cjsx
app/component/itinerary/transit-leg.cjsx
app/component/itinerary/walk-leg.cjsx
app/component/map/stop-marker-container.cjsx
app/component/navigation/index-navigation.cjsx
app/component/search/search-two-fields.cjsx
app/component/stop-cards/stop-card-list.cjsx

Cleaning code to make it more coffeescripty

Coffee cleaning

---

app/component/departure/departure.cjsx
app/component/departure/departure.scss
app/component/icon/icon.css
app/component/route/route-list-container.cjsx
app/component/stop-cards/departure-list-container.cjsx
app/component/stop/stop-reference.cjsx
app/component/stop/stop.scss
app/page/style-guidelines.cjsx
app/queries.js
app/util/get-selector.js
sass/main.scss

[DT-255 Nearby routes: add stop number](https://digitransit.atlassian.net/browse/DT-225)
Adds a component called StopReference that implements the showing of the stop number in a Departure. This new component is taken into use in the RouteListContainer in use in the nearby routes tab.
Also includes the component documentation and a small refactoring thereof.

DT-225 Nearby routes: add stop number

---

app/component/search/autosuggest.cjsx
test/config/nightwatch.json
test/locations.js
test/script/run-ui-tests.sh

In addition to process killing, I Made also made small modifications to autosuggest and ui-tests.

Improve and fix ui tests

---

app/component/itinerary/itinerary.scss
app/component/itinerary/ticket-information.cjsx
app/component/navigation/default-navigation.cjsx
app/component/navigation/offcanvas-menu.cjsx
app/component/util/not-implemented-link.cjsx
app/page/route.cjsx
app/page/stop.cjsx
app/page/style-guidelines.cjsx

-fix off canvas localisation bug for 'en'
-add link for 'buy ticket'
-move dialog placeholder upper in hierarchy

Notimplemented improvements

---

app/component/front-page/no-location-panel.cjsx
app/translations.coffee

Remove duplicate translation key

---

app/component/route/route-header-container.cjsx
app/page/route.cjsx

https://digitransit.atlassian.net/browse/DT-255

Show 404-not-found when looking at route page with illegal id

---

server/server.js

Use common error handling + raven error-handling middleware to report more context
This is related to https://digitransit.atlassian.net/browse/DT-257

Improve node sentry

---

app/component/route/route-list-container.cjsx
app/component/route/route.scss

Stop number as in here:
https://slack-files.com/files-tmb/T03HA371Q-F0C4RQYN6-3a1f5b11dd/hsl_reittiopas_ios_etusivu_linjat_vrk-vaihtuu_1024.png

Adds stop number label to nearby stops

---

app/page/summary.cjsx
app/translations.coffee

and send a message to Sentry too
Sentry demo https://app.getsentry.com/digitransit/digitransit-ui/group/89493325/

DT-258 show a message when OTP cannot plan

---

webpack.config.js

Production mode still uses testing server (matka)

Use dev API server when running dev

---

app/component/map/navigation-map.cjsx
app/store/service-store.coffee

Fix
- reference to mock position object
- LocationActions -> PositionActions
And  refactor

Mock position fixes

---

package.json
test/config/nightwatch.json

When there are test failures, Nightwatch running in Mocha mode does not exit with nonzero code. 
Enable a new feature from the fork until a fix is released and/or pull request merged.
Fork with fix:
https://github.com/Macroz/nightwatch
Pending pull request:
https://github.com/nightwatchjs/nightwatch/pull/722

Nightwatch fixes

---

app/store/service-store.coffee

Add window.mock.geolocation.demo function to walk to rautatieasema in small steps. Maybe be improved for other demo capabilities.

Demo tracking

---

app/component/navigation/index-navigation.scss
app/component/navigation/time-selectors.cjsx

-removes overlap from 1+
-shows all data on iphone4

tweak widths a little bit so that ne vavigation is more readable

---

app/component/search/autosuggest.cjsx

related to: DT-481, marks railway stations with station icon in suggestions

use stations icon for stations in suggestions

---

app/config.default.coffee
app/config.hsl.coffee

Reverts HSLdevcom/digitransit-ui#305

Revert "DT-492 Load maps from multiple subdomains"

---

test/api/browser-upgrade.js
test/config/nightwatch.json
test/route-page.js
test/search.js
test/stops-tab.js

multiple fixes:
-some recent changes made the stops-tab test to fail
-the iphone emulator did not start properly
-use client api constant for wait timeouts so it's easier to pump it up

Test fixes

---

app/component/search/search-field.cjsx

https://app.getsentry.com/digitransit/digitransit-ui/issues/106011762/

fix for "ReferenceError: PositionActions is not defined"

---

app/page/stop.cjsx
app/server.cjsx

Change in Relay broke server rendering of at least trip, stop and route page.

Fix trip, stop, route page

---

app/store/itinerary-search-store.coffee
app/store/local-storage.coffee

session storage is not available in mobile safari private browsing mode

fix for 'DOM Exception 22'

---

test/api/browser-upgrade.js

Check if more information can be added to tests to connect Snap and Browserstack

Test log session and commit

---

app/component/map/map.cjsx
app/component/map/map.scss
app/component/map/place-marker.cjsx
sass/themes/default/_theme.scss
sass/themes/hsl/_theme.scss

Implement [DT-537](https://digitransit.atlassian.net/browse/DT-537) so that the blue marker is used except when in the summary and trip maps.

Dt 537 blue marker

---

app/component/search/autosuggest.cjsx
app/config.default.coffee
app/config.hsl.coffee

Configurable and default false

Added location awareness in autosuggest/location searching.

---

package.json

Added engines block and enginesStrict=true to define clearly which node version we need.

Define minimal node version 5.0 needed for running the ui

---

app/page/summary.cjsx

Warning is on the summary page

fix: warning for using moment instead of number

---

app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/itinerary.scss

fix for the blue arrow overlapping the the walk distance in summary page.

Fix spacing

---

app/action/endpoint-actions.coffee
app/action/position-actions.coffee
app/action/search-actions.coffee
app/component/search/search-input.cjsx
app/component/search/search-modal.cjsx
app/component/search/search-two-fields-container.cjsx
app/component/search/suggestion-item.cjsx
app/page/summary.cjsx
app/store/endpoint-store.coffee
app/store/position-store.coffee
app/store/search-store.coffee

DT-676 add current position to results

---

app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/itinerary.scss
app/component/itinerary/wait-leg.cjsx
app/translations.coffee

Separate component for wait legs. Will for instance fix the current issue with `NaN m`

Wait leg component

---

app/component/itinerary/end-leg.cjsx
app/component/itinerary/itinerary-tabs.cjsx
app/component/itinerary/wait-leg.cjsx

Go to itinerary page. Now last leg of the itinerary can be clicked, and it will focus map.

Focus map when the last leg is clicked (previously did nothing)

---

.gitignore
package.json
webpack.config.js

- Load sass theme in webpack config based on env variable name.
- Git ignore themes other than hsl and default
- Git ignore config other than hsl, client and default. 
- Git ignore svg-sprite.*.svg other than svg-sprite.hsl.svg and sv-spring.default.svg.

Rutebanken load scss from config name

---

app/component/map/map.cjsx
app/component/map/stop/stop-marker-container.cjsx
app/component/map/stop/stop-marker-layer.cjsx

Fall back to stop marker container if URL.STOP_MAP property is not configured.

Fallback to stop marker container

---

app/component/navigation/offcanvas-menu.cjsx

Use "Log in" here.
See http://loginisnotaverb.com/ and compare Facebook ("Log In"), StackOverflow ("log in"), GitHub and Google (both "Sign in").

"Login" is not a verb

---

app/component/itinerary/wait-leg.cjsx
app/translations.coffee

Depends on proper moment configuration: #408

Use moment humanize in wait leg

---

app/component/itinerary/bicycle-leg.cjsx
app/component/itinerary/itinerary-legs.cjsx
app/translations.coffee

* This pull request includes changes from #413, so you might want to look at that first.
* In order to use moment's humanize method for other languages than 'fi', locale for moment should be set up based on the selected language, see #408

Separate itinerary leg component for bicycle

---

app/util/time-utils.coffee

Fix DT-773, durations >24h shown incorrectly

---

app/component/map/itinerary-line.cjsx
app/store/city-bike-store.coffee

Depends on getting the ID of the sharebike station from OTP in the result from "plan". https://github.com/opentripplanner/OpenTripPlanner/pull/2223

Show citybike station info in itinerary map view

---

app/component/departure/departure-time.cjsx
app/component/documentation/example-data.coffee
app/component/favourites/favourite-location-container.cjsx
app/component/favourites/favourite-location.cjsx
app/component/favourites/favourite-location.scss
app/component/favourites/favourite-locations-container.cjsx
app/queries.js
build/schema.json

Implements routing for favourite location tiles. [GraphQL PR](https://github.com/HSLdevcom/OpenTripPlanner/pull/43) required also.
Known issues:
- Double the necessary requests when opening page.
- All routing parameters not customizable.

Dt 719 favourite graphql

---

app/build-info.coffee
app/client.cjsx
app/component/util/piwik-provider.cjsx
app/html.cjsx
build-docker-image.sh

DT-716 performance info

---

app/component/favourites/favourite-location-container.cjsx
app/component/favourites/favourite-locations-container.cjsx
app/queries.js
build/schema.json

Match the use of the API to the latest GraphQL constructs

Fix graphql favourite plan

---

app/component/summary/summary-row.scss

Some additions for itinerary summaries. When reviewing this, consider:
- Livi and HSL use different fonts
- There are differences between android, ios, and windows phone
- on local mobile testing, hsl font will not load

add more space for itinerary summary times

---

app/translations.coffee

* Improve translation for no-favourites
* Add translations for favourite-target and search.

Norwegian translations for search and favourites

---

app/translations.coffee

Change to a more suitable norwegian translation for to-stop. It also fits better in the ui

Norwegian to-stop translation

---

app/component/favourites/add-favourite-container.cjsx
app/component/search/search.scss

fixes two issues:
-favourites search now does endpoint search
-missing tabrow when executing search

Dt 812 search gtfs data

---

app/translations.coffee

Update to latest changes, and fix a translation that wasn't appropriate in context.

Updates and fixes to french translation.

---

app/component/navigation/offcanvas-menu.cjsx
app/config.default.coffee
app/config.hsl.coffee
app/translations.coffee

Make it configurable to render some of the elements in the left menu (off canvas menu). This makes it possible to only render the language selector,

Configurable items in the left menu

---

app/component/summary/summary-row.cjsx
app/component/summary/summary-row.scss
app/server.cjsx

When real time is available for the itinerary, make the departure time green. This is a temporary solution until the full design is implemented.(with two departure times).

Green departure time if realtime

---

app/component/map/non-tile-layer/city-bike-marker.cjsx
app/component/map/popups/city-bike-popup.cjsx
app/component/map/tile-layer/tile-layer-container.cjsx

Please review with config useVectorTiles: true and useVectorTiles: false

Dt 914 citybike popup route here fix

---

app/component/summary/itinerary-summary-list-container.cjsx
app/component/summary/summary-plan-container.cjsx
app/component/summary/summary.scss
app/page/summary.cjsx

Improves the summary page when no route found

No route found

---

app/component/stop-cards/stop-card-header.cjsx
app/config.default.coffee
app/config.hsl.coffee
app/util/time-utils.coffee

Making it possible to not show the stop card header description in stop cards.

Configurable card header description for stop place card

---

app/component/itinerary/itinerary-plan-container.cjsx
test/itinerary.js
test/search.js

DT-955 summary to itinerary

---

app/server.cjsx

https://app.getsentry.com/digitransit/digitransit-ui/issues/125319444/

DT-975 add String.prototype.startsWith polyfill

---

app/translations.coffee

Adds missing strings linked to new splash screen and showing different current position based on state.

Update French translation against latest commits.

---

app/component/route/route-map-container.cjsx

pass in from, to in a format map expects them

---

app/component/documentation/example-data.coffee
app/component/favourites/favourite-location-container.cjsx
app/component/favourites/favourite-location.cjsx
app/component/favourites/favourite-location.scss
app/queries.js

Implements [DT-920](https://digitransit.atlassian.net/browse/DT-920)
Should test with mobiles and various route combinations.

Dt 920 show first vehicle

---

webpack.config.js

Now we have server relative urls for source maps in prod mode

Dt 982 fix sourcemap paths

---

app/component/navigation/index-navigation.scss

This class is not used anywhere in the project.

DT-1028 Remove unused fixed class rule

---

app/component/search/GeolocationOrInput.js

Fix typeof check

---

app/translations.coffee

In the context it is used, we think "Avganger" is better than "Sanntid".

Change norwegian translation for search

---

app/component/navigation/navigation.scss
app/component/splash/splash.scss

https://digitransit.atlassian.net/browse/DT-984
Conversion of splash screen to ES6 will happen separately.

Dt 984 splash style

---

app/action/ItinerarySearchActions.js
app/app.js
app/component/summary/TimeSelectorContainer.js
app/store/TimeStore.js
app/store/time-store.coffee

Time store was not working properly so now it's upgraded.
- When resetting on the first page, itinerary search is not done.
- Summary page does not track current time anymore.
- Only one loop of setTimeouts for time
- Converted to ES6

Fix time store

---

app/store/TimeStore.js

Fixes excessive time updating due to invalid reference

fix: reference to constant

---

app/component/front-page/front-page-panel.scss

Fixes spinner wobbling due to padding.

style: don't apply padding to spinner

---

app/component/util/util.scss
sass/themes/default/_theme.scss
sass/themes/hsl/_theme.scss

Make it possible to configure colors for standalone button in theme.

Add possibility to style standalone buttons in theme

---

app/component/itinerary/itinerary-tab.cjsx
app/component/itinerary/route-information.cjsx
app/config.default.coffee
app/config.hsl.coffee

Make route information configurable

CO2 and weather configurable

---

package.json

Generate gemini report by default when visual tests are run

---

app/component/search/search.scss

This is a temporary solution for the beta release desktop version.

DT-1025 No position fixed for search modal

---

app/component/route/route.scss

To center icons vertically in icons

Increase top padding for icons in button bar

---

app/server.cjsx

https://app.getsentry.com/digitransit/digitransit-ui/issues/130964363/

Add Array.prototype.includes polyfill

---

app/config.default.coffee
app/config.hsl.coffee
app/util/configure-moment.js
app/util/time-utils.coffee
package.json

https://digitransit.atlassian.net/browse/DT-1052

Make timezone configurable

---

app/server.cjsx

According to webpack stats plugin: `Stats can be a string or array`.
Support this in server.cjsx

Use array element or string when reading assetsByChunkName

---

app/component/favourites/favourite-location-container.cjsx
app/component/favourites/favourite-locations-container.cjsx
app/queries.js

Itineraries was sometimes null, also search parameters were different compared to the actual route search.
Conversion to ES6 in another PR.

Dt 1093 foobar

---

app/component/map/OriginPopup.js
app/component/map/non-tile-layer/city-bike-marker-container.cjsx

Fix actions

---

app/component/departure/NextDeparturesList.js
app/component/route/NearbyRouteListContainer.js

make nearby tab work in ie11

---

package.json
webpack.config.js

lineToLine should be false according to
https://webpack.github.io/docs/configuration.html#output-devtoollinetoli
ne

Fix source maps

---

server/server.js

See for details
http://babeljs.io/docs/plugins/transform-object-rest-spread/

Make Babel v6 work

---

app/config.joensuu.coffee

make bounding box larger

---

app/component/util/DesktopWrapper.js

make texts better

---

app/util/get-selector.js

Search from combined CSS selectors in getSelector

---

app/component/itinerary/ItineraryPlanContainer.js

Implements https://digitransit.atlassian.net/browse/DT-1097 by storing the state into browser history if available and closing fullscreen is a goBack.

feat: fullscreen back to un-fullscreen

---

app/component/route/RouteScheduleContainer.js

Use individual imports from lodash

---

app/component/navigation/MessageBar.js

Fix crash with missing message translation

---

app/translations.coffee

Update French translation to latest changes.

Update French translation.

---

app/component/summary/SummaryPlanContainer.js
app/component/summary/TimeNavigationButtons.js
app/util/geo-utils.js
package.json

Fix crash when routing returns no itinerary, seen at https://app.getsentry.com/digitransit/digitransit-ui/issues/135898639/

Fix crash no itinerary

---

app/component/map/tile-layer/TileLayerContainer.js

Fix error seen at https://app.getsentry.com/digitransit/digitransit-ui/issues/134401234/

handle undefined tile.el.layers on low zoom levels

---

app/component/itinerary/ItineraryPlanContainer.js
app/component/itinerary/itinerary.scss

Small fixes for improved usability.

Summary tuning

---

app/action/SearchActions.js
app/component/search/SuggestionItem.js

route search results were not sorted. additionally, some modes had icons but others didn't

Improve route sorting

---

app/component/map/non-tile-layer/StopMarker.js

This PR fixes a typo made in the summary map renewal, causing stop markers to have black stroke.

Fix stop markers

---

Dockerfile

Update to node 6

---

app/component/map/Map.js

Guard for missing config nodes

---

.gemini.conf.json
test/flow/nightwatch.json
test/flow/tests/itinerary-search/itinerary-search.js
test/flow/tests/stop/stop_place_map.js
test/flow/tests/terminal/terminal_place_map.js

Improve tests

---

app/component/itinerary/ItineraryPlanContainer.js
app/component/summary/SummaryPlanContainer.js
app/component/util/ModeFilter.js
app/component/util/util.scss
test/flow/page_object/customizeSearch.js

Restore airplane toggle

---

package.json
server/server.js

Fix app on node 6.5.0

---

app/server.js
app/store/PreferencesStore.js
app/store/localStorage.js

simplify language storage

---

package.json

https://github.com/Financial-Times/polyfill-service/pull/847
Object iterators are now included in the default es6 bundle

DT-1202 Update polyfill-service

---

app/component/map/Map.js

DT-1298 Add null check for map ref

---

app/component/route/route.scss
app/page/RoutePage.js

make error message visible, do not crash when pattern is not found

---

app/client.js

DT-1292 Fix differences between IE and Chrome

---

sass/themes/default/_theme.scss

DT-1359 quick fix for theme color problem

---

package.json
test/flow/nightwatch.json
test/flow/script/run-ui-tests.sh

The PR is done - it doesn't touch any js files.

iPhone emulator testing in SauceLabs

---

README.md
docs/JSBenchmark.md

Jetream results

---

test/flow/tests/smoke/title.js

reittiopas title - test fix

---

app/component/search/CurrentPositionSuggestionItem.js

Search dialog did not work (errors while changing tabs) and from startup screen could not type an address.

DT-1454: fix search dialog

---

app/config.turku.js

https://digitransit.atlassian.net/browse/DT-1374
https://digitransit.atlassian.net/browse/DT-1375
https://digitransit.atlassian.net/browse/DT-1377
https://digitransit.atlassian.net/browse/DT-1378
https://digitransit.atlassian.net/browse/DT-1379

Turku config changes

---

app/component/feedback/feedback-panel.cjsx
app/component/search/SearchInputContainer.js
app/component/search/SearchMainContainer.js
app/component/summary/OriginDestinationBar.js
test/flow/tests/smoke/itinerary-search.js

You can check node GC by adding following start flags:
--debug --trace-gc
Reason for memory leak is that componentWillUnmount is not called on server, therefore leaving unwanted listeners in heap.

Fix memory leak DT-1479

---

package.json

Remove duplicate dependency from package.json

---

app/component/search/SearchMainContainer.js

DT-1547 Fix compatibility with autowhatever

---

app/server.js

https://github.com/facebook/relay/issues/754

DT-1551 disable relay query caching

---

app/component/front-page/front-page.scss

Constrain max-height to 1000px.

DT-1566 Favourites/Nearby container extends below contents if window is taller than contents

---

package.json

chore(package): update node-sass to version 3.12.2

---

package.json

fix(package): update mqtt to version 2.1.1

---

package.json

chore(package): update node-sass to version 3.12.5

---

package.json

chore(package): update eslint to version 3.10.2

---

package.json

fix(package): update material-ui to version 0.16.4

---

package.json

fix(package): update mqtt to version 2.1.3

---

app/translations.js

Update French translation to latest master.

---

package.json

fix(package): update react-cookie to version 1.0.4

---

package.json

Merging greenkeeper stuff in here...

WIP - Merge dependencies

---

app/component/AboutPage.js
app/component/front-page.scss

Leave the rest of the task to wait until (disruption) modal is refactored to support back button.

DT-1607 add max width to about page content

---

app/component/LegAgencyInfo.js
app/config.matka.js

DT-1703 Livi prod changes

---

app/store/localStorage.js

This happens if user has denied cookies in browser settings.

handle SecurityError from localStorage

---

app/component/AboutPage.js

DT-1717 fix about page on safari

---

app/config.hsl.js
app/translations.js

DT-1692 add link to 'privacy policy'

---

app/component/navigation.scss
docs/ZIndex.md

DT-1694 fix z-index

---

package.json
yarn.lock

See:
https://github.com/sass/node-sass/issues/1669

DT-1730 Downgrade node-sass

---

webpack.config.js

Print warning in dev mode that not all browsers are supported

print warning if dev-mode

---

package.json

Downgrade lodash to IE11 compatible version 4.17.2

---

package.json
yarn.lock

See https://github.com/oliviertassinari/react-swipeable-views/issues/234

DT-1786 downgrade react-swipeable-views

---

app/MuiTheme.js
app/action/EndpointActions.js
app/client.js
app/component/DepartureRowContainer.js
app/component/NearbyRouteListContainer.js
app/component/NearbyRoutesPanel.js
app/component/NearestRoutesContainer.js
app/component/PlaceAtDistanceContainer.js
app/component/PlaceAtDistanceListContainer.js
app/component/SearchInputContainer.js
app/component/SuggestionItem.js
app/component/SummaryPage.js
app/component/TopLevel.js
app/server.js
app/staticMessages.js
app/store/MessageStore.js
app/util/Feedback.js
app/util/configure-moment.js
app/util/searchUtils.js

DT-1768 use relay defaults from config

---

app/component/StopPageMeta.js

Add desc so that the localized message is used.

Fix stop meta data

---

app/component/GeopositionSelector.js
app/component/OriginSelector.js

Route action payload

---

app/configurations/config.default.js
app/configurations/config.hsl.js
app/configurations/config.turku.js
test/flow/page_object/messageBar.js
test/flow/tests/terminal/terminal_place_map.js

DT-1776 remove welcome messages

---

docs/Architecture.md

Fixed a typo

---

app/component/SummaryNavigation.js

600 is the size of the left nav also

feat: fix the max width of customize search offcanvas

---

app/store/ModeStore.js

Use modes defined in config for nearest panel

Remove citybikes from nearest panel

---

app/component/SearchMainContainer.js
app/component/map/MarkerPopupBottom.js
app/util/searchUtils.js

Fix the time used in the search already when moving to summary page. 
Previously the time was set to the _initial time of component instantiation_ which would not update correctly. Going to the summary page without time also works since the time is set for that time. Perhaps would be better to redirect to a page with the time also fixed.

DT-1702 UI displays wrong route when itinerary map is enlarged

---

app/configurations/config.hameenlinna.js
app/configurations/config.hsl.js
app/configurations/config.joensuu.js
app/configurations/config.kuopio.js
app/configurations/config.lappeenranta.js
app/configurations/config.matka.js
app/configurations/config.oulu.js
app/configurations/config.turku.js

removes configuration that becomes wrong when static is mixed with dynamic setup

removes configurable config that are not meant to be configured

---

webpack.config.js

Use CONFIG to do a static mapping when it is defined during build.

Static config

---

app/component/navigation.scss

Signed-off-by: Morten Friesgaard <friesgaard@gmail.com>

fixes error in scss

---

app/component/BicycleLeg.js
app/component/CarLeg.js
app/component/Distance.js
app/component/SummaryRow.js
app/component/ViaLeg.js
app/component/WalkLeg.js
app/configurations/config.default.js
app/util/browser.js
app/util/geo-utils.js

The branch from which initial PR was created got pushed all kinds of stuff
afterwards. Measuring related changes extracted by this commit.

Clean merge of imperial distance changes

---

app/component/ItineraryPageMap.js
app/component/SummaryPage.js
app/component/TransitLeg.js

Opens the stop details popup when it's clicked on the itinerary view. When using on mobile, opens the popup only if the view is in fullscreen map mode. If the view returns to the minimized state, the popup closes.

DT-1906: As a user I want to see itinerary's stops on the map with next departures and be able go stop timetables

---

app/component/ItineraryTimePicker.js
app/util/browser.js

Now allows 2-digit input on samsung browser

fixed bug with samsung default browser

---

package.json

chore(package): update async to version 2.4.1

---

package.json

fix(package): update raven-js to version 3.15.0

---

package.json

fix(package): update fluxible-addons-react to version 0.2.12

---

server/reittiopasParameterMiddleware.js
test/flow/tests/redirect/search-from-hsl.js

makes hsl front page search work again

call with correct number of params

---

package.json

fix(package): update mqtt to version 2.8.1

---

package.json

fix(package): update offline-plugin to version 4.8.1

---

package.json

fix(package): update body-parser to version 1.17.2

---

package.json

chore(package): update nightwatch to version 0.9.15

---

app/server.js
package.json
server/server.js
yarn.lock

proxies dev server generated bundle.js to that it's possible to run dev-server through ngrok or some other proxy.

Proxy dev server

---

app/configurations/config.matka.js

Reverts HSLdevcom/digitransit-ui#1676

Revert "Add note about midsummer traffic for matka.fi"

---

package.json

chore(package): update webpack-dev-server to version 2.5.1

---

package.json

chore(package): update babel-loader to version 7.1.1

---

package.json

fix(package): update recompose to version 0.24.0

---

package.json

fix(package): update material-ui to version 0.18.6

---

package.json

chore(package): update css-loader to version 0.28.4

---

package.json

fix(package): update react-container-dimensions to version 1.3.2

---

package.json

fix(package): update mqtt to version 2.9.3

---

app/configurations/config.kuopio.js

- Restore original university name
- Set better university location

Final changes to Kuopio theme

---

app/configurations/config.default.js

Fix piwik ids

---

app/action/realTimeClientAction.js

Same fix needed here as for siri2gfsrt

allow colon characters in start time in MQTT messages

---

app/component/ItineraryTab.js
app/component/PrintableItinerary.js
app/component/itinerary.scss
app/routes.js

Added a basic page for the printable Itinerary.

DT-928: Add basic page in routes.js for printing page for itinerary

---

app/component/ItineraryTab.js
app/component/PrintableItinerary.js
app/component/SecondaryButton.js
app/component/SummaryPage.js
app/component/itinerary.scss
app/component/util.scss
app/routes.js

Added legs for the printable itinerary page.
JIRA link: https://digitransit.atlassian.net/browse/DT-2067
Zeplin link: https://app.zeplin.io/project/57ea6b227dcc263b567e1e6f/screen/59899077b004ca82e3618e0c

DT-2067: Add legs for printed page

---

app/component/ItineraryTimePicker.js
app/component/TimeSelectors.js

bugs fixed:
-fix time changes from 12 to 21 bug
-fix minutes missing digit bug
bugs created:
-probably several ;)

Try to make time input less bad

---

app/configurations/config.default.js

just to get it separated from matka

piwik id for oulu

---

app/component/map/Map.js

Add default value for loaded

---

app/component/map/tile-layer/TileLayerContainer.js

Also make sure they don't reopen after closing them when time updates

DT-2187 Make sure popups receive updated time

---

app/util/Raven.js

I am working on changing some of the information logged to sentry. Testing is currently practically impossible because we're rate limited almost all the time.

set sample rate to 0.1

---

package.json

fix(package): update polyfill-service to version 3.21.2

---

package.json

chore(package): update eslint-plugin-prettier to version 2.3.1

---

package.json

chore(package): update eslint-plugin-react to version 7.3.0

---

.travis.yml

disabling tests until we reach a more stable state

disable visual & flow tests for now

---

app/component/FavouritesPanel.js
app/component/IndexPage.js
app/component/NearbyRoutesPanel.js
app/component/OriginSelector.js
app/component/PanelOrSelectLocation.js
app/routes.js

also: 
-change routing config so that route search url works
-use router to navigate when origin is selected instead of action

Fix bugs in opening nearby panel

---

app/component/OriginSelector.js
app/util/path.js

When going from index to itinerary search we want to push.

improve history handling

---

app/action/PositionActions.js
app/component/DTAutosuggestPanel.js
app/component/MessageBar.js
app/store/MessageStore.js
app/translations.js
app/util/geolocationMessages.js

- Do not show messages with empty content
- Don't do buggy stuff when language change reduces set of valid messages
- Allow tab switching/message reading multiple times in the message bar
- Simplify message store
- Show 'how do you wish to start?' only at first geolocation denied event per session

Improve message bar and messages shown on it

---

app/component/DTAutosuggestPanel.js
app/component/DTSearchAutosuggest.js

- Autosuggest input sometimes dropped quickly typed chars
- Show destination/dark overlay on desktop only after user starts typing
- Don't render empty result between updates

Fix autosuggest bugs, optimize

---

app/component/search.scss

JIRA link: https://digitransit.atlassian.net/browse/DT-2254

DT-2254: On mobile the top marginal of origin box shuld be smaller

---

app/component/FrontPagePanelSmall.js
app/component/IndexPage.js
app/component/front-page.scss
app/component/search.scss
sass/base/_elements.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2249

DT-2249: Make front page minimum map size larger

---

app/component/RouteMapContainer.js
app/component/StopPageMap.js
sass/base/_elements.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2272

DT-2272: Map expand button is in the wrong place (Stop and Route views)

---

app/component/search.scss
package.json
yarn.lock

JIRA Link: https://digitransit.atlassian.net/browse/DT-2259

Dt 2259: Front page placeholder "Lähtöpaikka, Linja tai pysäkki" text should be darker

---

.travis.yml

Tests must be fixed in a separate task

Disable flow tests temporarily

---

app/client.js
app/component/DesktopView.js
app/component/ErrorBoundary.js
app/component/TopLevel.js
app/translations.js

Add error boundaries

---

app/component/front-page.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2308

DT-2308: White fade in nearby table turns to black in Safari

---

app/component/front-page.scss
app/component/map/Map.js
app/component/map/MapWithTracking.js
app/component/map/PositionMarker.js

… or 'b' on top of POS icon on itinerary summary map

DT-2332, DT-2330

---

app/component/IndexPage.js
app/component/StopPageMap.js

- Stop page map did not change the icon when maximized
- Index page changed icons using inverted logic

Fix maximize map button bugs

---

app/component/add-favourite-container.scss
app/component/origin-destination-bar.scss
app/component/search.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2335

DT-2335: Fix Sidebar and Favourite Place search width

---

app/action/PositionActions.js
app/component/GeopositionSelector.js
app/component/map/MapWithTracking.js

Do not zoom until position ready
Do not rely on permission api to provide event on prompt (it does not with ff for example)

Map tuning

---

app/component/TopLevel.js
sass/base/_helper-classes.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2319

DT-2319: When there is a notification open the layout breaks on Desktop and Mobile mode

---

app/component/FavouriteLocationsContainer.js
app/util/otpStrings.js
app/util/path.js

For example forward slash is breaking navigation currently

Navigation fix for addresses with special chars

---

app/component/ItineraryPageMap.js
app/component/MobileItineraryWrapper.js
app/component/itinerary.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2343

DT-2343: Fixed expand button

---

app/component/origin-destination-bar.scss
app/component/search.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2339

DT-2339: Itinenary page's 'swap endpoints' and 'add via point' icons do not align with search fields on mobile layout

---

app/component/search.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2342

DT-2342: Search dropdown style errors

---

app/component/navigation.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2349

DT-2349: Text overflows in Messagebar and covers closing icon

---

app/component/DepartureTime.js
app/component/RouteNumber.js
app/component/RouteStop.js
app/component/route.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2273
NOTE: Chosen route view is broken due to the removed CSS, will create a separate issue to fix it.

DT-2273: Bad route page layout on medium resolution devices using mobile layout.

---

app/component/departures-table.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2365

DT-2365: Check the nearby table's spaces around table cells

---

app/component/departures-table.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2367

DT-2367: Nearby Table-Headers broken in IE11

---

app/component/RouteListHeader.js
app/component/TripListHeader.js
app/component/departures-table.scss
app/component/route.scss

Route page + nearby table fixes

Small ie11 fix for nearby table

---

app/component/map/map.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2371

DT-2371: Two sidebars in a a stop popup when using tablet breakpoint

---

app/component/AddFavouriteContainer.js
app/component/route.scss
app/component/search.scss
app/component/summary-row.scss
sass/themes/default/_theme.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2092

DT-2092: Only use text/background colors that fulfil the WCAG contrast requirements

---

app/component/CustomizeSearch.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2372

DT-2372: Settings panel shows numeral defaults as NaN

---

app/component/FavouritesPanel.js
app/component/NextDeparturesList.js
app/component/NextDeparturesListHeader.js
app/component/departures-table.scss
app/component/favourite-location.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2375

DT-2375: Favourite Nearby table broken

---

app/component/route.scss
app/component/stop.scss
app/component/summary.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2383

DT-2383: Firefox renders wrong map size in route and itinerary pages

---

app/component/MessageBar.js

Because server does not know which messages user has seen

Do not render messagebar on server side

---

app/component/PrintableItinerary.js

Fixed walk itinerary printing bug.

DT-2385: When user tries to print an itinerary with only walking mode, the application crashes

---

app/action/realTimeClientAction.js
app/configurations/config.default.js

Use LIJ HFP feed as realtime vehicle position data source

Update MQTT url and topic

---

app/action/realTimeClientAction.js

HPF MQTT feed has different mode identifier in topic for trains

Fix HFP trains

---

app/component/navigation.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2455

DT-2455: Remove message bar from print pages

---

app/component/CustomizeSearch.js
app/component/QuickSettingsPanel.js
app/component/SaveCustomizedSettingsButton.js
app/component/SummaryNavigation.js
app/component/SummaryPage.js
app/component/summary.scss
app/store/localStorage.js
app/translations.js
app/util/planParamUtil.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2465

DT-2465: Fix QuickSettings bugs

---

app/component/CustomizeSearch.js
app/configurations/config.default.js
app/translations.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2473

DT-2473: Missing translations in settings

---

app/component/quickSettingsPanel.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2530

DT-2530: Update dropdown styles in Quick Settings Panel

---

app/component/ItineraryTimePicker.js
app/component/TimeSelectors.js
app/component/quickSettingsPanel.scss
app/component/summary.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2537

DT-2537: Small UI Fixes for Quick Settings Bar

---

app/component/SummaryNavigation.js
app/component/departures-table.scss
app/component/summary-row.scss
app/component/summary.scss

JIRA Link: https://digitransit.atlassian.net/browse/DT-2539

DT-2539: Overflow is clipped in the route number with over 3 characters

---

app/component/RoutePage.js
app/component/RoutePatternSelect.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2203
Especially useful for tram lines, for example 9 and 8.

DT-2203: As a user, I don't want to see on timetable patterns which do not have trips on selected day

---

app/component/map/map.scss
app/component/navigation.scss
app/component/search.scss
docs/ZIndex.md
sass/base/_elements.scss

Layout bugs

---

app/component/IndexPage.js

Hsl frontpage already has footer, so DT footer is not needed in it.
Added option to hide the footer.

Hsl-fi-77: Added option to hide footer via router

---

app/component/RoutePage.js
app/component/RoutePatternSelect.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2598

DT-2598: Route page's Timetable view is broken

---

app/component/RoutePatternSelect.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2622

DT-2622: Special routes with departures only on designated days are missing the direction dropdown

---

app/component/map/map.scss
sass/base/_elements.scss

As a side effect center map icons position was wrong

Fixed map being 100vh, causing a scrollbar to appear on the page

---

package.json
test/flow.sh
yarn.lock

Also, print free mem just before yarn build starts

Update uglifyjs plugin

---

.gemini.conf.js
package.json
test/flow.sh
test/visual.sh
webpack.config.js
yarn.lock

To get rid of webpack build failures

Run test server in dev mode

---

app/config.js
app/localStorageHistory.js
test/unit/localStorageHistory.test.js

Some changes made in #2285 (or related libraries) broke the PWA install of Reittiopas on iOS. The purpose of this pull request is to fix the breaking change and update the status bar color.

Fix the PWA install on iOS

---

.travis.yml

* I don't think coverage numbers are correct at the moment
* codecov reports "random" coverage numbers in github comments
-> Don't run code coverage for now, until those above points have been fixed 
reverse: https://github.com/HSLdevcom/digitransit-ui/pull/2277/files#diff-354f30a63fb0907d4ad57269548329e3

removed test coverage for now

---

app/component/DTAutosuggestPanel.js
app/component/Favourite.js
app/component/Icon.js
app/component/OriginDestinationBar.js
app/component/ToggleButton.js
app/util/modeUtils.js
app/util/queryUtils.js
package.json
test/unit/OriginDestinationBar.test.js
test/unit/helpers/mock-context.js
test/unit/queryUtils.test.js
yarn.lock

The purpose of this pull request is to enable swapping the order of via points when the origin and destination are swapped.
Link to the JIRA task: https://digitransit.atlassian.net/browse/DCW-18

DCW-18: support for via point order swapping

---

app/component/CustomizeSearch.js
app/component/DTAutosuggestPanel.js
app/component/Favourite.js
app/component/Icon.js
app/component/OriginDestinationBar.js
app/component/ToggleButton.js
app/util/modeUtils.js
app/util/queryUtils.js
package.json
test/unit/OriginDestinationBar.test.js
test/unit/helpers/mock-context.js
test/unit/queryUtils.test.js
yarn.lock

The purpose of this pull request is to change the walking speed indicator from m/min to km/h. Note that no speed indicator is available for cycling speed, so the rest of the specified work must be done after the new settings panel becomes available.
Link to the JIRA task: https://digitransit.atlassian.net/browse/DCW-32
Screenshot:

DCW-32: change the walking speed indicator from m/min to km/h

---

app/component/CustomizeSearch.js
app/component/QuickSettingsPanel.js
app/component/SummaryPage.js
app/configurations/config.default.js
app/configurations/config.oulu.js
app/util/planParamUtil.js

* small refactoring to allow different defaultSettings for configs
* increase walkBoardCost for Oulu

Increase walkBoardCost for Oulu

---

app/action/realTimeClientAction.js
app/component/CustomizeSearchNew.js
app/component/IconWithTail.js
app/component/ItineraryLegs.js
app/component/RouteNumber.js
app/component/SummaryNavigation.js
app/component/SummaryPage.js
app/component/TransitLeg.js
app/component/WalkLeg.js
app/component/map/MapWithTracking.js
test/unit/action/realTimeClientAction.test.js

The purpose of this pull request is to remove some of the clutter from the browser's console output while developing. The ultimate target should be to have no warnings at all under normal use of the software.

Fix common console warnings

---

app/component/SummaryPlanContainer.js

Searching earlier routes with arriveBy = false and searching later routes with arriveBy = true makes additional queries to OTP. Add / reduce 5 minutes to / from search time if OTP queries doesn't produce desired results. This way those earlier and later buttons will always do something.

Make sure search time changes when user clicks earlier / later buttons

---

app/component/CustomizeSearchNew.js
app/component/IndexPage.js
app/component/StreetModeSelectorPopup.js
app/component/StyleGuidePage.js
app/component/customize-search.scss
app/component/front-page.scss
app/component/map/MapWithTracking.js
app/component/street-mode-selector-panel.scss
app/component/street-mode-selector-popup.scss
app/component/street-mode-selector.scss

The purpose of this pull request is to update the UI styles to match those specified. The street mode selector popup now more closely matches the settings screen street mode selector.
Related JIRA ticket: https://digitransit.atlassian.net/browse/DCW-44
Screenshot:

DCW-44: UI style tuning

---

app/component/ItineraryTab.js
app/component/itinerary.scss
app/configurations/config.hsl.js
app/translations.js

- Position and style changed as designers instruct
- Change HSL specific translation
- Make rendering conditional (now enabled in HSL config)

Tune disclaimer

---

app/component/CustomizeSearchNew.js
app/component/PreferredRoutes.js
app/component/RouteDetails.js
package.json
test/unit/component/CustomizeSearchNew.test.js
test/unit/helpers/mock-context.js
yarn.lock

The purpose of this pull request is to fix a bug in the selected prefer/avoid routes not showing up in the settings screen. Included unit tests to demonstrate the problem.

Regression: fix showing preferred routes

---

README.md
docs/Docker.md

* Removed outdated information
* Got rid of specific browser versions and a demo gif that would require constant maintenance of the documentation

Updated README and other documentation

---

app/component/departures-table.scss
sass/themes/default/_theme.scss
sass/themes/hsl/_theme.scss

Should make google font look slightly more similar to the HSL on in the near you table

Made default font sizes slightly bigger in near you table

---

app/component/AddFavouriteContainer.js
app/component/FavouriteLocationsContainer.js
app/component/FavouriteRouteListContainer.js
app/component/FavouritesPanel.js
app/component/NextDeparturesList.js
app/component/OriginSelector.js
test/unit/component/FavouriteRouteListContainer.test.js

The purpose of this pull request is to prevent the UI from crashing if the user has saved a favourite route which is no longer available in the data. Some console warnings were removed in the process.

DT-2778: fix crash when favourite route is no longer available

---

app/component/map/MapWithTracking.js
app/configurations/config.default.js

* Set default value for textLogo
* Make defaultMapCenter non-required prop as it's only used in hsl config

Fix warning

---

package.json
test/flow/tests/stop/stop_timetable.js
webpack.config.babel.js
yarn.lock

https://twitter.com/sebmarkbage/status/1060053812075872256

Switch to terser

---

app/component/RoutesAndPlatformsForStops.js
test/unit/RoutesAndPlatformsForStops.test.js
test/unit/test-data/dt2715a.js
test/unit/test-data/dt2715b.js

JIRA Link: https://digitransit.atlassian.net/browse/DT-2840

DT-2840: Add Arrives/Terminates indicator text to the routes and lines tab

---

app/translations.js
app/util/timeUtils.js
test/unit/timeUtils.test.js

New splash text

---

app/configurations/config.default.js
app/configurations/config.hameenlinna.js
app/configurations/config.joensuu.js
app/configurations/config.jyvaskyla.js
app/configurations/config.kotka.js
app/configurations/config.kouvola.js
app/configurations/config.kuopio.js
app/configurations/config.lahti.js
app/configurations/config.lappeenranta.js
app/configurations/config.matka.js
app/configurations/config.mikkeli.js
app/configurations/config.oulu.js
app/configurations/config.rovaniemi.js
app/configurations/config.tampere.js
app/translations.js
build/template.waltti.js

The purpose of this pull request is to prepare for the upcoming change in Liikennevirasto.

DT-2857: replace Liikennevirasto with Traficom where applicable

---

app/component/AppBarLarge.js
app/component/Favourite.js
app/component/Icon.js
app/component/Modal.js
test/flow/page_object/route.js
test/flow/tests/route/route-page.js
test/flow/tests/smoke/alerts.js
test/unit/AppBarLarge.test.js
test/unit/component/Modal.test.js

The purpose of this pull request is to remove the pointer events setting for icons as it easily causes bugs. This functionality is no longer needed as titles have been removed from the svgs.
JIRA link: https://digitransit.atlassian.net/browse/DT-2841

DT-2841: fix disabled home button for Safari and IE11

---

app/configurations/config.hsl.js

- Update HSL ticket sales url to contain tracking tags

Update URL to contain tags

---

app/configurations/config.default.js
app/util/mqttClient.js

- Update HSL MQTT to test endpoint

Change next-dev to test mqtt

---

.travis.yml
test/flow/nightwatch.json
test/flow/script/run-ui-tests.sh

- Run smoke tests in sequence to avoid random failures

More reliable smoke testing

---

app/component/FavouritesPanel.js

From https://github.com/HSLdevcom/digitransit-ui/pull/2716
- Compare contents instead of object references to avoid continuos updates which will make the favorite panel unusable as the information is not visible
- Fixes #2714

Fix FilteredFavouritesPanel

---

app/component/RoutePatternSelect.js

- Added dropdown when there's only 1 pattern

DT-2977: Toggling directions in Route Pattern selection causes an onClick error

---

app/component/CardHeader.js
app/component/CityBikeCard.js
app/translations.js
app/util/citybikes.js
sass/base/_elements.scss
test/unit/component/CardHeader.test.js
test/unit/component/CityBikeCard.test.js
test/unit/util/citybikes.test.js

Reverts HSLdevcom/digitransit-ui#2730

Revert "DT-2954"

---

app/configurations/config.hsl.js

Enable HSL weekly route timetables

---

app/translations.js

Give specific date for new zones

---

.travis.yml
app/component/BubbleDialog.js
app/component/SelectMapLayersDialog.js
app/component/bubble-dialog.scss
app/component/map/GeoJSON.js
app/configurations/config.hsl.js
sass/base/_helper-classes.scss
test/unit/component/map/GeoJSON.test.js

- Show zone map layer and tooltip for disabling it

Zone tooltip

---

app/util/mqttClient.js
test/unit/util/mqttClient.test.js

- Translate metro -> subway when reading metro hfp data

Translate metro from hfp topic to subway

---

app/component/RoutePatternSelect.js
app/component/route.scss

- Fixed the issue where the pattern title doesn't show on iOS safari
- JIRA Link: https://digitransit.atlassian.net/browse/DT-3003

DT-3003: Text disappears in the route view with two patterns (iOS Safari)

---

app/configurations/config.default.js
app/configurations/config.hsl.js
app/configurations/config.matka.js

- Correct samocat station info links
- Add all helsinki networks in matka.fi too
- Disable vantaa network until  bikes and api become available

Reconfigure citybikes

---

app/configurations/realtimeUtils.js

- Use a default wss port for lmj mqtt to avoid issues with networks blocking connections to weird port numbers

Change lmj mqtt port

---

app/configurations/config.matka.js

- Update feedback link for opas.matka.fi

Update feedback link for matka

---

app/component/bubble-dialog.scss
app/configurations/config.tampere.js

- Add map layer tooltip to tampere's config (and fix tooltip style)

Add maplayer tooltip to tampere

---

app/configurations/config.hsl.js
app/configurations/config.matka.js

- Enable vantaa citybikes in hsl and matka configs

Enable vantaa citybikes

---

app/util/mqttClient.js

- Check that there are existing topics before unsubscribing

Don't unsubscribe unless there are existing topics

---

app/component/IndexPage.js
app/component/map/MapWithTracking.js

- Added destination marker on the map when destination has been set but origin hasn't
- JIRA Link: https://digitransit.atlassian.net/browse/DT-3066

DT-3066: Destination marker is not rendered on front page

---

app/configurations/realtimeUtils.js
app/store/RealTimeInformationStore.js
app/util/mqttClient.js
test/unit/util/mqttClient.test.js

- Migrated HFP 1.0 to HFP 2.0.
- Ticket: https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3079

Dt 3079 - Migrate to HFP 2.0 in Reittiopas 

---

app/component/CustomizeSearchNew.js

- Sort tickets in settings in a way that always produces same result and the order is reasonable

Fix ticket sorting

---

app/component/MessageBarMessage.js
app/configurations/config.default.js
app/store/MessageStore.js
app/store/sessionStorage.js
app/util/browser.js
package.json
test/unit/helpers/init.js
test/unit/localStorage.test.js
test/unit/sessionStorage.test.js
yarn.lock

- Added cookie banner for unsupported browsers.
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&modal=detail&selectedIssue=DT-3032

DT-3032: Allow triggering cookie banner when user uses a non-supported browser

---

build/add-theme.js

- updated scripts for creating new instance
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3116

DT-3116: Update the scripts for creating a new digitransit instance

---

.eslintrc.js
app/action/PositionActions.js
app/component/AdminPage.js
app/component/MessageBar.js
app/component/TripLink.js
app/component/map/popups/TicketSalesPopup.js
app/component/map/tile-layer/CityBikes.js
app/component/map/tile-layer/ParkAndRide.js
app/component/map/tile-layer/Stops.js
app/component/map/tile-layer/TicketSales.js
app/localStorageHistory.js
app/server.js
app/store/localStorage.js
app/store/sessionStorage.js
build/generate-schema.js
server/proxyTester.js
test/flow/custom_commands/debug.js
test/unit/helpers/init.js
test/visual/components.js

- Throw eslint error from using console commands

Throw eslint error from using console commands

---

app/configurations/config.matka.js
app/configurations/config.oulu.js
app/configurations/config.turku.js

- Add oulu's citybike network to oulu and matka configurations
- Change turku's citybike network name and enable it also in matka configuration

Oulu citybikes

---

app/configurations/config.default.js
app/configurations/config.hsl.js

- Use finland-citybike-map tiles for matka configuration

Use finland-citybike-map in matka conf

---

Dockerfile
docs/Docker.md

- Remove references to PIWIK_ADDRESS and PIWIK_ID in documentation as they are not used in code anymore

Remove references to PIWIK_ADDRESS and PIWIK_ID

---

server/reittiopasParameterMiddleware.js
test/unit/reittiopasParameterMiddleware.test.js

- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3135

DT-3135: URL parameters are ignored when linked from external page

---

build/check_translations.js

Fixes the useful script for searching missing / unnecessary translations

Translation checker fix from robbi5

---

app/util/browser.js

Do not prompt users of new edge versions to change the browser

---

app/configurations/config.hsl.js
app/util/browser.js

- Start testing the new yleisviesti url in dev 
- Check safari browser version and warn users of old versions

Some minor updates

---

app/component/RouteScheduleContainer.js
app/component/Timetable.js
app/configurations/config.default.js
app/configurations/config.hsl.js
app/configurations/config.tampere.js
app/configurations/timetableConfigUtils.js
server/server.js
test/unit/component/Timetable.test.js
test/unit/util/timetableConfigUtils.test.js

- Added stop pdf links to Tampere
- Refactored code a little bit so that it is easier to add stop pdf links to other
- https://digitransit.atlassian.net/secure/RapidBoard.jspa?rapidView=7&projectKey=DT&modal=detail&selectedIssue=DT-3095

DT-3095: Tampere, add static each stop pdf to stop page

---

Dockerfile
app/configurations/config.hsl.js
app/configurations/config.matka.js
docs/Docker.md
docs/Installation.md

- Add STATIC_MESSAGE_URL env variable for defining static message URL
- Update docs about available env variables

Add STATIC_MESSAGE_URL env and clean docs

---

app/component/SummaryPage.js
app/component/map/MapWithTracking.js
app/store/MessageStore.js
app/util/messageUtils.js
test/unit/util/messageUtils.test.js

- Added support for the banner in the itinerary view based on either origin or destination location. 

DT-3156: Enable general communication banner (=yleisviestipalvelu) for itinerary view to support targeting for destination area

---

app/configurations/config.tampere.js
app/configurations/realtimeUtils.js

- remove tre train routing
- remove experimental hsl vehicle location data source

Proper UI configurations for new release

---

app/configurations/realtimeUtils.js
app/util/gtfsRtParser.js
test/unit/util/gtfsRtParser.test.js

- Use vehicle position data in turku
- Fix vehicle position message parsing issue when data is missing

Add FOLI vehicles and fix parsing for missing info

---

.travis.yml

- Fix code coverage by default ubuntu version in travis

Revert travis OS definition to fix code coverage

---

app/util/planParamUtil.js

- Fixes earlier and later queries when locale has not been in set in URI

Fallback to using cookie locale if it is missing from query

---

app/component/map/VehicleMarkerContainer.js

DT-3242 vehicle icons should be the top layer

---

.travis.yml

- attempt to fix test coverage

build: DTM-169 try changing build environment to fix test coverage

---

app/component/MessageBar.js

- Only show alerts with feedIds specified in config in message bar

Messagebar alerts fix

---

app/component/ItinerarySummaryListContainer.js
app/component/QuickSettingsPanel.js
app/configurations/config.default.js
app/translations.js
app/util/planParamUtil.js
test/unit/component/QuickSettingsPanel.test.js
test/unit/component/SummaryPlanContainer.test.js

- Display different error message when no routes are found and user has changed settings

User notifier change

---

app/component/ItinerarySummaryListContainer.js
app/component/QuickSettingsPanel.js
app/configurations/config.default.js
app/translations.js
app/util/planParamUtil.js
test/unit/component/QuickSettingsPanel.test.js
test/unit/component/SummaryPlanContainer.test.js

- Notify user about changed routing settings if no routes found

Notify user if no routes found and settings changed

---

app/configurations/config.tampere.js

- Config changes to enable train routing in Tampere

DT-3283: Enable train routing in Tampere

---

app/component/AlertPopUp.js
app/component/QuickSettingsPanel.js
app/configurations/config.tampere.js
app/translations.js

- Add missing TampereVR feedId to tampere config
- Disallow bicycles on trains in tampere

Add tamperevr feedid

---

app/component/IntermediateLeg.js
app/component/ZoneIcon.js

Adjusting zone icon in route page

Adjusting zone icon in route page

---

app/store/FavouriteRoutesStore.js
app/util/searchUtils.js

This fix solves an issue where outdated favorite routes breaks line search 

Fix for DT-3285: Outdated favourite routes break line search

---

app/configurations/config.tampere.js

This reverts commit a01a63858a81bf783b2143959746e01d88da6695.
-

Revert "Static banner message for Tampere"

---

app/component/ItineraryTab.js
app/configurations/config.default.js
app/configurations/config.tampere.js
app/util/fareUtils.js

Checks if mode of the leg is rail, walk or wait. Usage in configure file, default false, true in Tampere

Dt 3293 Show information about different ticket seller when itinerary include only a trainin Tampere.

---

server/server.js

- Add cookie option to oidc session 
- To test sessions locally over http, set httpOnly and secure flag to false. Also it's recommended to change SESSION_SECRET when testing.

DT-3305: Configure HSLID sessions which do not expire

---

app/configurations/config.jyvaskyla.js

Updated About this service section in jyvaskyla
-

updated about this service section

---

docs/ZIndex.md
sass/base/_base.scss

fix: z-index for spinner, so that spinner shows in route page.

z-index for spinner

---

app/component/quickSettingsPanel.scss

fix: quicksettingspanel overflow issue in mobile

---

app/configurations/realtimeUtils.js
app/util/mqttClient.js
test/unit/util/mqttClient.test.js

- Removed subscription to extra topics in HSL config as it created too much load on the MQTT broker

fix: remove route id variation related changes to lessen load

---

server/server.js

- Creates session when user logs in
- Delete session on logout 

DT-3327: Fix login unstability

---

app/component/DepartureListContainer.js
app/component/DepartureRowContainer.js
app/component/NextDeparturesList.js
app/component/PatternLink.js
app/component/RouteAlertsRow.js
app/component/RouteHeader.js
app/component/RoutePage.js
app/component/RoutesAndPlatformsForStops.js
app/util/routePatternSelectUtil.js
app/util/searchUtils.js

- Checking is re-routing allowed by comparing length of location's path name with length of modified path name

fix: should consider selected pattern

---

app/component/DTSearchAutosuggest.js
app/component/SuggestionItem.js
app/component/TopLevel.js
app/translations.js

DT-3262 and DT-3263

---

app/configurations/config.hsl.js

- Removes use of Samocat network in HSL config
<b> At some point we might want to remove the code related to showing different texts for scooter legs/stations as it is not being for anything at the moment but there is a chance that it will be used somewhere in the world in the future so maybe we should leave it as it is for now </b> …

chore: remove samocat network from hsl conf

---

app/component/AddFavouriteContainer.js
app/component/MessageBarMessage.js
app/store/FavouriteStore.js
package.json
test/unit/component/AddFavouriteContainer.test.js
yarn.lock

- Use uuid as identifier for favourites
- Update uuidv4 package

DT-3340: Add unique identifier for favourites

---

app/component/AddFavouriteContainer.js
app/component/ExampleData.js
app/component/FavouriteLocation.js
app/component/FavouriteLocationsContainer.js
app/component/FavouritesPanel.js
app/component/OriginSelector.js
app/component/SuggestionItem.js
app/store/FavouriteStore.js
app/util/searchUtils.js
app/util/suggestionUtils.js
test/unit/component/AddFavouriteContainer.test.js

- Change locationName to name in favourite data model.

DT-3396: Update favourite data model

---

app/component/FavouriteRouteContainer.js
app/component/TopLevel.js
app/store/FavouriteStore.js
app/util/apiUtils.js
server/server.js

- Create endpoint for fav-service.
- Use fav-service if user has logged in and favourite host env is defined.
- Fix deleting favourite routes.

DT-3200: Synchronize localstorage favorites with backend data storage

---

digitransit-util/packages/digitransit-util-day-range-allowed-diff/CHANGELOG.md
digitransit-util/packages/digitransit-util-day-range-pattern/CHANGELOG.md
digitransit-util/packages/digitransit-util-enrich-patterns/CHANGELOG.md
digitransit-util/packages/digitransit-util-route-pattern-option-text/CHANGELOG.md
digitransit-util/packages/digitransit-util-route-pattern-option-text/index.js
digitransit-util/packages/digitransit-util/CHANGELOG.md
digitransit-util/packages/digitransit-util/package.json
lerna.json
package.json

-In Hämeenlinna there is routes without headsign.

DT-3422 If pattern headsign is "null", use the last stop's name of pattern

---

app/configurations/config.kuopio.js

- Enables tickets in Kuopio configuration

feat: enable tickets in Kuopio config

---

app/component/RouteAlertsRow.js
test/unit/component/RouteAlertsRow.test.js

- Fixes route links from top bar disruption listing
- Added default pattern/direction and allowed sorting

fix: route alert links

---

app/configurations/config.kuopio.js

This reverts commit d08498e4679a0a46ba8611990eab9a831999e4c5.
- Reverts kuopio's fare configuration temporarily before a release

Revert "feat: enable tickets in Kuopio config"

---

app/store/FavouriteStore.js

fix: favourites

---

app/component/QuickSettingsPanel.js
app/component/SummaryNavigation.js

- Removed unnecessary components e.g. quick settings and mode selector

DT-3452: Remove 'Quicksettings' from itinerary page

---

app/component/AddFavouriteContainer.js
app/component/EmptyFavouriteLocationSlot.js
app/component/FavouriteLocation.js
app/component/FavouriteLocationsContainer.js
app/component/IndexPage.js
app/component/favourite-location.scss
app/component/front-page.scss
app/configurations/config.default.js
app/configurations/config.hsl.js
app/store/FavouriteStore.js
package.json
server/server.js
yarn.lock

- Add old favourite panel to front page

DT-3445: Render favorites bar into control panel

---

.gitignore
app/configurations/config.kuopio.js

- Re-enables Kuopio's fares
- Adds relay files generated by relay modern to gitignore as we have branches that use relay modern

Enable kuopio fares

---

app/component/BackButton.js
app/component/DesktopView.js
app/component/SummaryPage.js
app/component/navigation.scss

- Removed "home"-button
- Use BackButton-component instead of Link-component

DT-3358: New header in itinerary page

---

app/component/BackButton.js
app/component/DesktopView.js
app/component/TopLevel.js

- Pressing back button not loose origin

DT-3471: Back button loose origin 

---

app/component/DTAutosuggest.js
app/component/DTAutosuggestPanel.js

- Focus origin field automatically on front page if the field is empty.
- Focus destination field when user selects origin.

DT-3443: Fix focus handling bugs in From/To search fields

---

app/component/DTSearchAutosuggest.js

- Clicking on search field now displays suggestion dropdown after every click
- Pressing tab after using the clear button to clear an input field now shows the true state instead of remaining empty

fix: search regressions

---

app/component/DTAutosuggest.js

- Clicking on search field now displays suggestion dropdown after every click
- Pressing tab after using the clear button to clear an input field now shows the true state instead of remaining empty

DT-3458-next: fix: search regressions

---

app/component/AppBarContainer.js
app/component/TopLevel.js
app/component/navigation.scss
app/configurations/config.default.js
app/configurations/config.hsl.js

- "Top navigation" is now configurable by config-file (default value  is appBarStyle: 'default').

DT-3375: Make displaying of navbar configurable

---

app/component/IndexPage.js
app/component/map/IndexPageMap.js
app/component/map/Map.js
app/component/map/MapContainer.js
app/component/map/MapWithTracking.js
app/component/map/map.scss
app/component/map/tile-layer/TileLayerContainer.js
app/component/navigation.scss
app/configurations/config.default.js
app/configurations/config.hsl.js
app/util/withBreakpoint.js
test/unit/component/map/MapWithTracking.test.js

- Making elements on map configurable instead of removing

DT-3470: Preliminary map changes

---

app/component/BusLeg.js
app/component/DepartureRowContainer.js
app/configurations/config.hsl.js

-  fix gtfsId on test data related to RouteNumber

chore: fix gtfsId on test data

---

app/component/AppBarSmall.js
app/component/BackButton.js
app/component/CardHeader.js
app/component/DesktopView.js
app/component/RoutePage.js
app/component/StopCardHeader.js
app/component/StopPageHeader.js
test/unit/component/StopCardHeader.test.js

- Fixing back button color and behaviour

DT-3472: Fix back button color in route and stop pages

---

app/component/DTAutosuggest.js
app/component/SuggestionItem.js
app/translations.js
app/util/suggestionUtils.js

- First suggestion in the Autosuggest dropdown is now announced on NVDA every time it changes
- NVDA now only announces the amount of found suggestions when it is relevant

Dynamic searchinput ariacontent

---

app/routes.js

- Fixes map when viewing some itinerary suggestion

fix: itinerary page map

---

app/component/RouteHeader.js
app/component/RouteNumber.js
test/unit/component/RouteNumber.test.js

Reverts HSLdevcom/digitransit-ui#3192

Revert "Dt 3484"

---

app/component/map/popups/LocationPopup.js

- feat: read ticket zones from geocoder

DT-3477 feat: read ticket zones from geocoder

---

app/component/map/popups/LocationPopup.js

- read ticket zones from geocoder

DT-3477 Next: read ticket zones from geocoder

---

app/component/CallAgencyLeg.js
app/component/FavouriteLocation.js
app/component/NextDeparturesList.js
app/component/RouteHeader.js
app/component/RouteNumber.js
app/component/RouteNumberContainer.js
app/component/RoutePage.js
app/component/SummaryRow.js
app/component/TransitLeg.js
app/component/ViaLeg.js
app/configurations/config.default.js
app/configurations/config.hsl.js

- revert U-line prefix changes while keeping style changes

fix: revert U-line prefix changes

---

app/routes.js

- Return 404 for missing files from /js/, /css/ and /assets/ subdirectories instead of just for the missing files from those root paths

fix: return 404 for missing js, css and asset paths that contain /

---

app/configurations/config.kuopio.js
app/configurations/config.matka.js

- Enables citybikes in kuopio config
- Adds kuopio citybikes to matka config

Dt 3188 next

---

app/component/Availability.js
app/component/CityBikeAvailability.js
app/component/CityBikeContent.js
app/component/map/popups/ParkAndRideAvailability.js
app/configurations/config.default.js
app/configurations/config.kuopio.js
test/unit/component/Availability.test.js
test/unit/component/CityBikeAvailability.test.js
test/unit/component/map/popups/ParkAndRideAvailability.test.js

- Adds configuration option for hiding spacesAvailable information from citybike stations
- It is normally shown in station popup
- Hides spacesAvailable info in Kuopio conf

Dt 3490 next

---

app/component/map/GeoJSON.js
docs/GeoJson.md
test/unit/component/map/GeoJSON.test.js

Popup menu for all geoJson features

DT-3505-next

---

app/component/PatternStopsContainer.js
app/component/RouteListHeader.js
app/component/RouteStop.js
app/component/RouteStopListContainer.js
app/configurations/config.default.js

Optional next departure column in route page

refactor: toggle "next" column of the Route panel

---

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json
digitransit-component/packages/digitransit-component-autosuggest/package.json
digitransit-component/packages/digitransit-component/package.json
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
digitransit-search-util/packages/digitransit-search-util-get-geocoding-results/package.json

- Fixing version numbering for publish shared components to npm

Digitransit - npm shared component - version numbering 

---

app/component/map/tile-layer/TileLayerContainer.js

Hi there!
Working on popups we had some trouble understanding the render method of the `TileLayerContainer` component as it was quite complex. We tried to make it a bit more comprehensible by splitting it into different methods and introducing new variables.
Hope you'll find it useful!
- Check that the implementation matches the design, when such one is …

Refactor: TileLayerContainer

---

package.json

- Small yarn script for building digitransit-components

DT-3520: yarn script for building components

---

app/util/DTSearchContextInitializer.js
app/util/DTSearchUtils.js
app/util/searchContext.js
digitransit-component/packages/digitransit-component-autosuggest-panel/index.js
digitransit-component/packages/digitransit-component-autosuggest-panel/package.json
digitransit-component/packages/digitransit-component-autosuggest/index.js
digitransit-component/packages/digitransit-component-autosuggest/package.json
digitransit-component/packages/digitransit-component/package.json
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
digitransit-search-util/packages/digitransit-search-util-helpers/index.js
digitransit-search-util/packages/digitransit-search-util-helpers/package.json

DT-3521: Remove config from shared components

---

app/server.js

- PR #3235 introduced a problem with server-side rendering and this odd fix reverts to the original state.

fix: put catch method back into its previous state

---

sass/base/_base.scss

- Adding new style to _base.scss

DT-3527: style errors on HSL navbar

---

app/component/map/IndexPageMap.js
app/component/map/MapWithTracking.js
app/component/map/PolygonWithText.js
app/component/map/tile-layer/TileLayerContainer.js

DT-3401: selecting a location (destination/origin) from map on mobile

---

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json
digitransit-component/packages/digitransit-component-autosuggest/package.json
digitransit-component/packages/digitransit-component-control-panel/package.json
digitransit-component/packages/digitransit-component-suggestion-item/package.json
digitransit-component/packages/digitransit-component/package.json

chore: versioning

---

app/component/map/Map.js
app/component/map/map.scss
app/configurations/config.default.js
app/configurations/config.hsl.js

- Moved and re-shaped map elements

DT-3397 fix how to show map elements

---

app/routes.js

- Removing map from mobile's front page

DT-3538: remove map from mobile's front page

---

app/component/SummaryPage.js

- Removing map from itinerary summary page

DT-3545: removing map from itinerary summary page

---

app/component/SummaryPage.js

- revert map back to itinerary detail on mobile

DT-3553: revert map back to itinerary detail on mobile

---

app/action/PositionActions.js
app/component/DTOldSearchSavingAutosuggest.js
app/component/map/popups/LocationPopup.js
app/configurations/config.default.js
app/util/searchUtils.js
test/unit/DTOldSearchSavingAutosuggest.test.js

- Refactor Pelias API specific functionality into `searchUtils.js` only to simplify configuration object and to make it easier to use other geocoding APIs

Refactor Pelias API usage into one module

---

digitransit-search-util/packages/digitransit-search-util-query-utils/index.js
digitransit-search-util/packages/digitransit-search-util-query-utils/package.json

- Initial documentation for shared query utils

DT-3574: documentation for query utils

---

app/component/AppBarHsl.js

- Added query params to language urls

DT-3562: Language selection erases URL parameters

---

app/component/CityBikeNetworkSelector.js
app/util/citybikes.js
app/util/planParamUtil.js

- Fix citybike network selection

DT-3559: fix citybike network selection

---

app/MuiTheme.js
app/component/RoutingSettingsButtons.js
app/component/StyleGuidePage.js
app/component/map/non-tile-layer/StopMarker.js
app/configurations/config.hsl.js
app/util/mapIconUtils.js
digitransit-component/packages/digitransit-component-autosuggest-panel/helpers/styles.scss
digitransit-component/packages/digitransit-component-autosuggest-panel/index.js
digitransit-component/packages/digitransit-component-autosuggest-panel/package.json
sass/base/_base.scss
sass/themes/default/_theme.scss
sass/themes/hsl/_theme.scss

- Make DTAutosuggestpanel font text to 16px ***Will be done in DT-3539***
- Where to text (as well as other headings in indexPage) from spans etc to h2, or h3 ***Done in DT-3551***
- new base url for fonts:

DT-3569: Font styling

---

app/component/MobileView.js
app/component/TerminalPageTabContainer.js
app/component/map/Map.js
app/component/map/map.scss
app/component/stop-cards.scss
app/component/stop.scss
sass/base/_elements.scss

- Stop page mobile layout
- Fixed bug with maximizing map on stations
- Moved openStreetMap logo to bottom left according to layout

DT-3571: Stop page mobile layout

---

app/component/CityBikeNetworkSelector.js
app/component/FareZoneSelector.js
app/component/SearchSettingsDropdown.js
app/component/StreetModeSelectorPanel.js
app/component/customize-search.scss
app/component/customizesearch/AccessibilityOptionSection.js
app/component/customizesearch/TransferOptionsSection.js
app/component/customizesearch/TransportModesSection.js
app/component/searchSettingsDropdown.scss
app/component/toggle.scss
app/translations.js
static/assets/svg-sprite.default.svg
static/assets/svg-sprite.hsl.svg

- Font changes
- Margin tweaks
- Sort fare zone options
- Add checkmark icon to selected dropdown option
- Update untoggled toggle colors

DT-3570: Search settings tweaks

---

app/component/map/map.scss

- fix broken vehicle popup layout

DT-3561: fix broken vehicle popup layout

---

app/component/map/map.scss
app/component/map/popups/LocationPopup.js
app/component/map/tile-layer/TileLayerContainer.js

- fix location popup address and styles

DT-3573: fix location popup address and styles

---

app/component/IndexPage.js

- Geolocation doesn't fail anymore while applying it on first time
- Tested on Mac: Chrome, Firefox. 

DT-3575: Fix applying geolocation for the first time

---

app/component/AppBarHsl.js
app/component/IndexPage.js
test/unit/AppBarHsl.test.js

DT-3550: Smoother front page loading

---

app/component/AppBarHsl.js

-  Change navbar hsl logo link to direct to uusi.hsl.fi front page

DT-3581: Change navbar hsl logo link

---

app/component/map/map.scss

- fix location popup on mobile

DT-3586: fix location popup on mobile

---

app/component/Duration.js
app/component/ItineraryLegs.js
app/component/ItinerarySummary.js
app/component/ItineraryTab.js
app/component/SummaryPage.js
app/component/SummaryPlanContainer.js
app/component/SummaryRow.js
app/component/TimeFrame.js
app/component/itinerary.scss

- Itinerary details are rendered as a full control panel content in desktop

DT-3567: Show itinerary details as a full control panel content

---

digitransit-component/packages/digitransit-component-autosuggest/package.json
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json
yarn.lock

- Favourite stops and stations now shows up in location search

DT-3606: Favorite stations do not show up in location search

---

app/component/AppBarHsl.js
package.json
yarn.lock

- Upgrading @hsl-fi/site-header to version 0.2.1

DT-3596: upgrading @hsl-fi/site-header to version 0.2.1

---

digitransit-component/packages/digitransit-component-autosuggest-panel/helpers/styles.scss
digitransit-component/packages/digitransit-component-autosuggest-panel/package.json
digitransit-component/packages/digitransit-component-suggestion-item/helpers/styles.scss
digitransit-component/packages/digitransit-component-suggestion-item/package.json
digitransit-component/packages/digitransit-component-traffic-now-link/helpers/styles.scss
digitransit-component/packages/digitransit-component-traffic-now-link/index.js
digitransit-component/packages/digitransit-component-traffic-now-link/package.json

DT-3597:  Finalised styles for AutosuggestPanel, SuggestionItemist, and Traffic now link

---

app/component/IndexPage.js
digitransit-component/packages/digitransit-component-control-panel/helpers/styles.js
digitransit-component/packages/digitransit-component-control-panel/index.js
digitransit-component/packages/digitransit-component-control-panel/package.json

- Fine tuning: separator line and gray backround on Safari

DT-3602: Style fine tuning: front page

---

app/component/route.scss
sass/themes/hsl/_theme.scss

- Small style fixes according to design

DT-3598: Style fine tuning: route page

---

app/component/front-page.scss
yarn.lock

- Removed unnecessary padding and margins from stops-near-you-div and h2 inside it.

DT-3613: style fix for stops-near-you div

---

app/component/map/map.scss

- fix stop popup layout in stop page

DT-3607: fix stop popup layout in stop page

---

app/component/AppBarHsl.js

DT-3615: Update hsl.fi navi links

---

app/component/BackButton.js
app/component/SelectFromMapHeader.js
app/component/navigation.scss

- Fixing position of Back button

DT-3614: position of BackButton on 'Select from map'-page

---

app/component/IndexPage.js
app/component/QuickSettingsPanel.js
app/component/front-page.scss
app/component/quickSettingsPanel.scss
digitransit-component/packages/digitransit-component-datetimepicker/helpers/Datetimepicker.js
digitransit-component/packages/digitransit-component-datetimepicker/helpers/styles.scss
digitransit-component/packages/digitransit-component-datetimepicker/package.json

DT-3612: Style fine tuning: datetimepicker

---

digitransit-component/packages/digitransit-component-datetimepicker/helpers/Datetimepicker.js
digitransit-component/packages/digitransit-component-datetimepicker/helpers/styles.scss

- Small style fix: make time icon part of clickable button

DT-3612: datetimepicker style fix

---

app/component/MobileItineraryWrapper.js
app/component/SummaryPage.js

- Fixes issue where switching shown itinerary on mobile layout crashed UI
- Fixes issue where entering an itinerary page directly on mobile sometimes crashed UI

Summary page map fixes for mobile view

---

app/configurations/config.hsl.js

DT-3625: Update Traffic now link's uri

---

app/configurations/config.default.js

- Updated default config's zoom levels for map to 9 - 18

DT-3591: Update zoom levels

---

digitransit-component/packages/digitransit-component-datetimepicker/helpers/styles.scss
digitransit-component/packages/digitransit-component-datetimepicker/package.json

DT-3622: Datetimepicker focus style is broken

---

app/component/map/popups/marker-popup.scss
app/component/map/tile-layer/MarkerSelectPopup.js

- Improve styling when scrollbar appears
- Not a perfect fix but better than before, eight arrow margins get squished

DT-3636: New popup styles broken on firefox

---

app/component/RouteScheduleHeader.js

- Fixing error which crashed the page

DT-3620: prevent to crash

---

digitransit-component/packages/digitransit-component-autosuggest-panel/package.json

DT-3639: Version test

---

app/component/CustomizeSearchNew.js
app/component/customize-search.scss

- Add scrollbar to itinerary settings and tweak the scrolling

DT-3635: add scrollbar to itinerary settings and tweak the scrolling

---

digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js

- Don't order favourites in search.

DT-3642: Order of favorites in search

---

app/component/Loading.js
package.json
sass/themes/default/_theme.scss
yarn.lock

DT-3640: Use spinner component from uusi.hsl.fi

---

app/configurations/config.hsl.js

DT-3656: disable feedbackly

---

digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/index.js
digitransit-search-util/packages/digitransit-search-util-execute-search-immidiate/package.json

-search component now checks for favourites in instace where you want to show select from own positions option.

DT-3673: Hide select from own location if no favourites 

---

app/configurations/config.default.js
app/configurations/config.hsl.js
app/util/apiUtils.js
package.json
server/server.js
yarn.lock

- Add endpoint to get weather data.

DT-3658: opendata.fmi.fi intergration to get weather data

---

app/component/ItinerarySummaryListContainer.js
app/component/itinerary.scss
app/translations.js

- Add updated finnish translations for no routes found situation.
- Update summary notification styling.

DT-3501: No routes found situation

---

server/passport-openid-connect/Strategy.js
server/passport-openid-connect/openidConnect.js
server/server.js

DT-3674: Fix sso callback
